startCategory(cFin(_)).
[dhjetë] :: [c2,-sl0].%[dhjetë] :: [c2,-sl0,-fl], [epsLi([=c2,+sl0,+fl,c2,-sl0],dot)]
[dhjetë] :: [c2,-sl0,-fl].
[dhjetë] :: [c3].%[dhjetë] :: [c2,-sl0,-fl], [epsLi([=c2,+sl0,+fl,c2,-sl0],dot),epsLi([=c2,+sl0,c3],dot)]
[dhjetë] :: [c2].%[dhjetë] :: [c2,-sl0,-fl], [epsLi([=c2,+fl,c2],dot),epsLi([=c2,+sl0,+fl,c2,-sl0],dot),epsLi([=c2,+sl0,c2],dot)]
[dhjetë] :: [cFin].%[dhjetë] :: [c2,-sl0,-fl], [epsLi([=c2,+sl0,+fl,c2,-sl0],dot),epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[dhjetë] :: [=c1,+el,c3].%[dhjetë] :: [=c1,+el,c2,-sl0], [epsLi([=c2,+sl0,c3],dot)]
[dhjetë] :: [=c1,+el,c2].%[dhjetë] :: [=c1,+el,c2,-sl0], [epsLi([=c2,+sl0,c2],dot)]
[dhjetë] :: [=c1,+el,c2,-sl0].
[dhjetë] :: [=c1,+el,cFin].%[dhjetë] :: [=c1,+el,c2,-sl0], [epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[dhjetë_e] :: [=c1,=c2el,c3].%[dhjetë_e] :: [=c1,=c2el,c2,-sl0], [epsLi([=c2,+sl0,c3],dot)]
[dhjetë_e] :: [=c1,=c2el,c2].%[dhjetë_e] :: [=c1,=c2el,c2,-sl0], [epsLi([=c2,+sl0,c2],dot)]
[dhjetë_e] :: [=c1,=c2el,c2,-sl0].
[dhjetë_e] :: [=c1,=c2el,cFin].%[dhjetë_e] :: [=c1,=c2el,c2,-sl0], [epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[dy] :: [c1,-al].%[dy] :: [c1,-al,-dl], [epsLi([=c1,+al,+dl,c1,-al],dot)]
[dy] :: [c1,-al,-dl].
[dy] :: [c1].%[dy] :: [c1,-al,-dl], [epsLi([=c1,+dl,c1],dot),epsLi([=c1,+al,+dl,c1,-al],dot),epsLi([=c1,+al,c1],dot)]
[dy] :: [c3].%[dy] :: [c1,-al,-dl], [epsLi([=c1,+dl,c1],dot),epsLi([=c1,+al,+dl,c1,-al],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,c3],dot)]
[dy] :: [c2,-fl].%[dy] :: [c1,-al,-dl], [epsLi([=c1,+dl,c1],dot),epsLi([=c1,+al,+dl,c1,-al],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,c2,-fl],dot)]
[dy] :: [c3fl].%[dy] :: [c1,-al,-dl], [epsLi([=c1,+dl,c1],dot),epsLi([=c1,+al,+dl,c1,-al],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,c2,-fl],dot),epsLi([=c2,+fl,c3fl],dot)]
[dy] :: [c2].%[dy] :: [c1,-al,-dl], [epsLi([=c1,+dl,c1],dot),epsLi([=c1,+al,+dl,c1,-al],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,c2,-fl],dot),epsLi([=c2,+fl,c2],dot)]
[dy] :: [cFin].%[dy] :: [c1,-al,-dl], [epsLi([=c1,+dl,c1],dot),epsLi([=c1,+al,+dl,c1,-al],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,c3],dot),epsLi([=c3,cFin],dot)]
[gjashtë] :: [c1,-bl].%[gjashtë] :: [c1,-bl,-el], [epsLi([=c1,+bl,+el,c1,-bl],dot)]
[gjashtë] :: [c1,-bl,-el].
[gjashtë] :: [c1].%[gjashtë] :: [c1,-bl,-el], [epsLi([=c1,+el,c1],dot),epsLi([=c1,+bl,+el,c1,-bl],dot),epsLi([=c1,+bl,c1],dot)]
[gjashtë] :: [c3].%[gjashtë] :: [c1,-bl,-el], [epsLi([=c1,+el,c1],dot),epsLi([=c1,+bl,+el,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c3],dot)]
[gjashtë] :: [c2,-fl].%[gjashtë] :: [c1,-bl,-el], [epsLi([=c1,+el,c1],dot),epsLi([=c1,+bl,+el,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-fl],dot)]
[gjashtë] :: [c3fl].%[gjashtë] :: [c1,-bl,-el], [epsLi([=c1,+el,c1],dot),epsLi([=c1,+bl,+el,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-fl],dot),epsLi([=c2,+fl,c3fl],dot)]
[gjashtë] :: [c2].%[gjashtë] :: [c1,-bl,-el], [epsLi([=c1,+el,c1],dot),epsLi([=c1,+bl,+el,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-fl],dot),epsLi([=c2,+fl,c2],dot)]
[gjashtë] :: [cFin].%[gjashtë] :: [c1,-bl,-el], [epsLi([=c1,+el,c1],dot),epsLi([=c1,+bl,+el,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c3],dot),epsLi([=c3,cFin],dot)]
[katër] :: [c1].%[katër] :: [c1,-bl], [epsLi([=c1,+bl,c1],dot)]
[katër] :: [c1,-bl].
[katër] :: [c3].%[katër] :: [c1,-bl], [epsLi([=c1,+bl,c1],dot),epsLi([=c1,c3],dot)]
[katër] :: [c2,-fl].%[katër] :: [c1,-bl], [epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-fl],dot)]
[katër] :: [cFin].%[katër] :: [c1,-bl], [epsLi([=c1,+bl,c1],dot),epsLi([=c1,c3],dot),epsLi([=c3,cFin],dot)]
[katër] :: [c3fl].%[katër] :: [c1,-bl], [epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-fl],dot),epsLi([=c2,+fl,c3fl],dot)]
[katër] :: [c2].%[katër] :: [c1,-bl], [epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-fl],dot),epsLi([=c2,+fl,c2],dot)]
[mbëdhjete] :: [=c1,+al,c3].%[mbëdhjete] :: [=c1,+al,c2,-sl0], [epsLi([=c2,+sl0,c3],dot)]
[mbëdhjete] :: [=c1,+al,c2].%[mbëdhjete] :: [=c1,+al,c2,-sl0], [epsLi([=c2,+sl0,c2],dot)]
[mbëdhjete] :: [=c1,+al,c2,-sl0].
[mbëdhjete] :: [=c1,+al,cFin].%[mbëdhjete] :: [=c1,+al,c2,-sl0], [epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[mbëdhjetë] :: [=c1,+bl,c3].%[mbëdhjetë] :: [=c1,+bl,c2,-sl0], [epsLi([=c2,+sl0,c3],dot)]
[mbëdhjetë] :: [=c1,+bl,c2].%[mbëdhjetë] :: [=c1,+bl,c2,-sl0], [epsLi([=c2,+sl0,c2],dot)]
[mbëdhjetë] :: [=c1,+bl,c2,-sl0].
[mbëdhjetë] :: [=c1,+bl,cFin].%[mbëdhjetë] :: [=c1,+bl,c2,-sl0], [epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[një] :: [c1,-bl].%[një] :: [c1,-bl,-dl], [epsLi([=c1,+bl,+dl,c1,-bl],dot)]
[një] :: [c1,-bl,-dl].
[një] :: [c1].%[një] :: [c1,-bl,-dl], [epsLi([=c1,+dl,c1],dot),epsLi([=c1,+bl,+dl,c1,-bl],dot),epsLi([=c1,+bl,c1],dot)]
[një] :: [c3].%[një] :: [c1,-bl,-dl], [epsLi([=c1,+dl,c1],dot),epsLi([=c1,+bl,+dl,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c3],dot)]
[një] :: [c2,-fl].%[një] :: [c1,-bl,-dl], [epsLi([=c1,+dl,c1],dot),epsLi([=c1,+bl,+dl,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-fl],dot)]
[një] :: [c3fl].%[një] :: [c1,-bl,-dl], [epsLi([=c1,+dl,c1],dot),epsLi([=c1,+bl,+dl,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-fl],dot),epsLi([=c2,+fl,c3fl],dot)]
[një] :: [c2].%[një] :: [c1,-bl,-dl], [epsLi([=c1,+dl,c1],dot),epsLi([=c1,+bl,+dl,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-fl],dot),epsLi([=c2,+fl,c2],dot)]
[një] :: [cFin].%[një] :: [c1,-bl,-dl], [epsLi([=c1,+dl,c1],dot),epsLi([=c1,+bl,+dl,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c3],dot),epsLi([=c3,cFin],dot)]
[nëntë] :: [c1,-bl].%[nëntë] :: [c1,-bl,-el], [epsLi([=c1,+bl,+el,c1,-bl],dot)]
[nëntë] :: [c1,-bl,-el].
[nëntë] :: [c1].%[nëntë] :: [c1,-bl,-el], [epsLi([=c1,+el,c1],dot),epsLi([=c1,+bl,+el,c1,-bl],dot),epsLi([=c1,+bl,c1],dot)]
[nëntë] :: [c3].%[nëntë] :: [c1,-bl,-el], [epsLi([=c1,+el,c1],dot),epsLi([=c1,+bl,+el,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c3],dot)]
[nëntë] :: [c2,-fl].%[nëntë] :: [c1,-bl,-el], [epsLi([=c1,+el,c1],dot),epsLi([=c1,+bl,+el,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-fl],dot)]
[nëntë] :: [c3fl].%[nëntë] :: [c1,-bl,-el], [epsLi([=c1,+el,c1],dot),epsLi([=c1,+bl,+el,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-fl],dot),epsLi([=c2,+fl,c3fl],dot)]
[nëntë] :: [c2].%[nëntë] :: [c1,-bl,-el], [epsLi([=c1,+el,c1],dot),epsLi([=c1,+bl,+el,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-fl],dot),epsLi([=c2,+fl,c2],dot)]
[nëntë] :: [cFin].%[nëntë] :: [c1,-bl,-el], [epsLi([=c1,+el,c1],dot),epsLi([=c1,+bl,+el,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c3],dot),epsLi([=c3,cFin],dot)]
[pesë] :: [c1,-bl].%[pesë] :: [c1,-bl,-el], [epsLi([=c1,+bl,+el,c1,-bl],dot)]
[pesë] :: [c1,-bl,-el].
[pesë] :: [c1].%[pesë] :: [c1,-bl,-el], [epsLi([=c1,+el,c1],dot),epsLi([=c1,+bl,+el,c1,-bl],dot),epsLi([=c1,+bl,c1],dot)]
[pesë] :: [c3].%[pesë] :: [c1,-bl,-el], [epsLi([=c1,+el,c1],dot),epsLi([=c1,+bl,+el,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c3],dot)]
[pesë] :: [c2,-fl].%[pesë] :: [c1,-bl,-el], [epsLi([=c1,+el,c1],dot),epsLi([=c1,+bl,+el,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-fl],dot)]
[pesë] :: [c3fl].%[pesë] :: [c1,-bl,-el], [epsLi([=c1,+el,c1],dot),epsLi([=c1,+bl,+el,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-fl],dot),epsLi([=c2,+fl,c3fl],dot)]
[pesë] :: [c2].%[pesë] :: [c1,-bl,-el], [epsLi([=c1,+el,c1],dot),epsLi([=c1,+bl,+el,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-fl],dot),epsLi([=c2,+fl,c2],dot)]
[pesë] :: [cFin].%[pesë] :: [c1,-bl,-el], [epsLi([=c1,+el,c1],dot),epsLi([=c1,+bl,+el,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c3],dot),epsLi([=c3,cFin],dot)]
[qind] :: [=cnix,=c1,cFin].%[qind] :: [=cnix,=c1,c3], [epsLi([=c3,cFin],dot)]
[qind] :: [=cnix,=c1,c3].
[qind_e] :: [=c3fl,=c1,cFin].%[qind_e] :: [=c3fl,=c1,c3], [epsLi([=c3,cFin],dot)]
[qind_e] :: [=c3fl,=c1,c3].
[shtatë] :: [c1,-bl].%[shtatë] :: [c1,-bl,-el], [epsLi([=c1,+bl,+el,c1,-bl],dot)]
[shtatë] :: [c1,-bl,-el].
[shtatë] :: [c1].%[shtatë] :: [c1,-bl,-el], [epsLi([=c1,+el,c1],dot),epsLi([=c1,+bl,+el,c1,-bl],dot),epsLi([=c1,+bl,c1],dot)]
[shtatë] :: [c3].%[shtatë] :: [c1,-bl,-el], [epsLi([=c1,+el,c1],dot),epsLi([=c1,+bl,+el,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c3],dot)]
[shtatë] :: [c2,-fl].%[shtatë] :: [c1,-bl,-el], [epsLi([=c1,+el,c1],dot),epsLi([=c1,+bl,+el,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-fl],dot)]
[shtatë] :: [c3fl].%[shtatë] :: [c1,-bl,-el], [epsLi([=c1,+el,c1],dot),epsLi([=c1,+bl,+el,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-fl],dot),epsLi([=c2,+fl,c3fl],dot)]
[shtatë] :: [c2].%[shtatë] :: [c1,-bl,-el], [epsLi([=c1,+el,c1],dot),epsLi([=c1,+bl,+el,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-fl],dot),epsLi([=c2,+fl,c2],dot)]
[shtatë] :: [cFin].%[shtatë] :: [c1,-bl,-el], [epsLi([=c1,+el,c1],dot),epsLi([=c1,+bl,+el,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c3],dot),epsLi([=c3,cFin],dot)]
[tetë] :: [c1,-bl].%[tetë] :: [c1,-bl,-el], [epsLi([=c1,+bl,+el,c1,-bl],dot)]
[tetë] :: [c1,-bl,-el].
[tetë] :: [c1].%[tetë] :: [c1,-bl,-el], [epsLi([=c1,+el,c1],dot),epsLi([=c1,+bl,+el,c1,-bl],dot),epsLi([=c1,+bl,c1],dot)]
[tetë] :: [c3].%[tetë] :: [c1,-bl,-el], [epsLi([=c1,+el,c1],dot),epsLi([=c1,+bl,+el,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c3],dot)]
[tetë] :: [c2,-fl].%[tetë] :: [c1,-bl,-el], [epsLi([=c1,+el,c1],dot),epsLi([=c1,+bl,+el,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-fl],dot)]
[tetë] :: [c3fl].%[tetë] :: [c1,-bl,-el], [epsLi([=c1,+el,c1],dot),epsLi([=c1,+bl,+el,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-fl],dot),epsLi([=c2,+fl,c3fl],dot)]
[tetë] :: [c2].%[tetë] :: [c1,-bl,-el], [epsLi([=c1,+el,c1],dot),epsLi([=c1,+bl,+el,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-fl],dot),epsLi([=c2,+fl,c2],dot)]
[tetë] :: [cFin].%[tetë] :: [c1,-bl,-el], [epsLi([=c1,+el,c1],dot),epsLi([=c1,+bl,+el,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c3],dot),epsLi([=c3,cFin],dot)]
[tre] :: [c1].%[tre] :: [c1,-bl], [epsLi([=c1,+bl,c1],dot)]
[tre] :: [c1,-bl].
[tre] :: [c3].%[tre] :: [c1,-bl], [epsLi([=c1,+bl,c1],dot),epsLi([=c1,c3],dot)]
[tre] :: [c2,-fl].%[tre] :: [c1,-bl], [epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-fl],dot)]
[tre] :: [cFin].%[tre] :: [c1,-bl], [epsLi([=c1,+bl,c1],dot),epsLi([=c1,c3],dot),epsLi([=c3,cFin],dot)]
[tre] :: [c3fl].%[tre] :: [c1,-bl], [epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-fl],dot),epsLi([=c2,+fl,c3fl],dot)]
[tre] :: [c2].%[tre] :: [c1,-bl], [epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-fl],dot),epsLi([=c2,+fl,c2],dot)]
[tridhjetë] :: [c2,-sl0].%[tridhjetë] :: [c2,-sl0,-fl], [epsLi([=c2,+sl0,+fl,c2,-sl0],dot)]
[tridhjetë] :: [c2,-sl0,-fl].
[tridhjetë] :: [c3].%[tridhjetë] :: [c2,-sl0,-fl], [epsLi([=c2,+sl0,+fl,c2,-sl0],dot),epsLi([=c2,+sl0,c3],dot)]
[tridhjetë] :: [c2].%[tridhjetë] :: [c2,-sl0,-fl], [epsLi([=c2,+fl,c2],dot),epsLi([=c2,+sl0,+fl,c2,-sl0],dot),epsLi([=c2,+sl0,c2],dot)]
[tridhjetë] :: [cFin].%[tridhjetë] :: [c2,-sl0,-fl], [epsLi([=c2,+sl0,+fl,c2,-sl0],dot),epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[tridhjetë_e] :: [=c1,c3].%[tridhjetë_e] :: [=c1,c2,-sl0], [epsLi([=c2,+sl0,c3],dot)]
[tridhjetë_e] :: [=c1,c2].%[tridhjetë_e] :: [=c1,c2,-sl0], [epsLi([=c2,+sl0,c2],dot)]
[tridhjetë_e] :: [=c1,c2,-sl0].
[tridhjetë_e] :: [=c1,cFin].%[tridhjetë_e] :: [=c1,c2,-sl0], [epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[zet] :: [=c1,+dl,c3].%[zet] :: [=c1,+dl,c2,-sl0], [epsLi([=c2,+sl0,c3],dot)]
[zet] :: [=c1,+dl,c2].%[zet] :: [=c1,+dl,c2,-sl0], [epsLi([=c2,+sl0,c2],dot)]
[zet] :: [=c1,+dl,c2,-sl0].
[zet] :: [=c1,+dl,cFin].%[zet] :: [=c1,+dl,c2,-sl0], [epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[zet_e] :: [=c1,=c2dl,c3].%[zet_e] :: [=c1,=c2dl,c2,-sl0], [epsLi([=c2,+sl0,c3],dot)]
[zet_e] :: [=c1,=c2dl,c2].%[zet_e] :: [=c1,=c2dl,c2,-sl0], [epsLi([=c2,+sl0,c2],dot)]
[zet_e] :: [=c1,=c2dl,c2,-sl0].
[zet_e] :: [=c1,=c2dl,cFin].%[zet_e] :: [=c1,=c2dl,c2,-sl0], [epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[dhjetë] :: [c3fl].%[dhjetë] :: [c2,-sl0,-fl], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+fl,c3fl],dot)]
[dy] :: [c2dl].%[dy] :: [c1,-al,-dl], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+dl,c2dl],dot)]
[gjashtë] :: [c2el].%[gjashtë] :: [c1,-bl,-el], [epsLi([=c1,+bl,c1],dot),epsLi([=c1,+el,c2el],dot)]
[një] :: [c2dl].%[një] :: [c1,-bl,-dl], [epsLi([=c1,+bl,c1],dot),epsLi([=c1,+dl,c2dl],dot)]
[nëntë] :: [c2el].%[nëntë] :: [c1,-bl,-el], [epsLi([=c1,+bl,c1],dot),epsLi([=c1,+el,c2el],dot)]
[pesë] :: [c2el].%[pesë] :: [c1,-bl,-el], [epsLi([=c1,+bl,c1],dot),epsLi([=c1,+el,c2el],dot)]
[shtatë] :: [c2el].%[shtatë] :: [c1,-bl,-el], [epsLi([=c1,+bl,c1],dot),epsLi([=c1,+el,c2el],dot)]
[tetë] :: [c2el].%[tetë] :: [c1,-bl,-el], [epsLi([=c1,+bl,c1],dot),epsLi([=c1,+el,c2el],dot)]
[tridhjetë] :: [c3fl].%[tridhjetë] :: [c2,-sl0,-fl], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+fl,c3fl],dot)]
[] :: [cnix].
