startCategory(cFin(_)).
[otor] :: [c3il].%[otor] :: [c1,-el,-al,-il], [epsLi([=c1,+el,c1],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,+il,c3il],dot)]
[ostar] :: [c3il].%[ostar] :: [c1,-al,-dl,-il], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+dl,c1],dot),epsLi([=c1,+il,c3il],dot)]
[jobe] :: [c3il].%[jobe] :: [c1,-cl,-al,-il], [epsLi([=c1,+cl,c1],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,+il,c3il],dot)]
[ester] :: [c3il].%[ester] :: [c1,-al,-dl,-il], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+dl,c1],dot),epsLi([=c1,+il,c3il],dot)]
[bin] :: [c2,-sl0].%[bin] :: [c2,-sl0,-gl], [epsLi([=c2,+sl0,+gl,c2,-sl0],dot)]
[bin] :: [c2,-sl0,-gl].
[bin] :: [c3].%[bin] :: [c2,-sl0,-gl], [epsLi([=c2,+sl0,+gl,c2,-sl0],dot),epsLi([=c2,+sl0,c3],dot)]
[bin] :: [c2].%[bin] :: [c2,-sl0,-gl], [epsLi([=c2,+gl,c2],dot),epsLi([=c2,+sl0,+gl,c2,-sl0],dot),epsLi([=c2,+sl0,c2],dot)]
[bin] :: [cFin].%[bin] :: [c2,-sl0,-gl], [epsLi([=c2,+sl0,+gl,c2,-sl0],dot),epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[bin] :: [=c1,c3].%[bin] :: [=c1,c2,-sl0], [epsLi([=c2,+sl0,c3],dot)]
[bin] :: [=c1,c2].%[bin] :: [=c1,c2,-sl0], [epsLi([=c2,+sl0,c2],dot)]
[bin] :: [=c1,c2,-sl0].
[bin] :: [=c1,cFin].%[bin] :: [=c1,c2,-sl0], [epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[deque] :: [c2,-sl0].%[deque] :: [c2,-sl0,-gl], [epsLi([=c2,+sl0,+gl,c2,-sl0],dot)]
[deque] :: [c2,-sl0,-gl].
[deque] :: [c3].%[deque] :: [c2,-sl0,-gl], [epsLi([=c2,+sl0,+gl,c2,-sl0],dot),epsLi([=c2,+sl0,c3],dot)]
[deque] :: [c2].%[deque] :: [c2,-sl0,-gl], [epsLi([=c2,+gl,c2],dot),epsLi([=c2,+sl0,+gl,c2,-sl0],dot),epsLi([=c2,+sl0,c2],dot)]
[deque] :: [cFin].%[deque] :: [c2,-sl0,-gl], [epsLi([=c2,+sl0,+gl,c2,-sl0],dot),epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[deque] :: [=c1,+al,c3].%[deque] :: [=c1,+al,c2,-sl0], [epsLi([=c2,+sl0,c3],dot)]
[deque] :: [=c1,+al,c2].%[deque] :: [=c1,+al,c2,-sl0], [epsLi([=c2,+sl0,c2],dot)]
[deque] :: [=c1,+al,c2,-sl0].
[deque] :: [=c1,+al,cFin].%[deque] :: [=c1,+al,c2,-sl0], [epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[dui] :: [c1,-hl].%[dui] :: [c1,-hl,-al], [epsLi([=c1,+hl,+al,c1,-hl],dot)]
[dui] :: [c1,-hl,-al].
[dui] :: [c3hl].%[dui] :: [c1,-hl,-al], [epsLi([=c1,+hl,+al,c1,-hl],dot),epsLi([=c1,+hl,c3hl],dot)]
[dui] :: [c1].%[dui] :: [c1,-hl,-al], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+hl,+al,c1,-hl],dot),epsLi([=c1,+hl,c1],dot)]
[dui] :: [c3].%[dui] :: [c1,-hl,-al], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+hl,+al,c1,-hl],dot),epsLi([=c1,+hl,c1],dot),epsLi([=c1,c3],dot)]
[dui] :: [c2,-gl].%[dui] :: [c1,-hl,-al], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+hl,+al,c1,-hl],dot),epsLi([=c1,+hl,c1],dot),epsLi([=c1,c2,-gl],dot)]
[dui] :: [c3gl].%[dui] :: [c1,-hl,-al], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+hl,+al,c1,-hl],dot),epsLi([=c1,+hl,c1],dot),epsLi([=c1,c2,-gl],dot),epsLi([=c2,+gl,c3gl],dot)]
[dui] :: [c2].%[dui] :: [c1,-hl,-al], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+hl,+al,c1,-hl],dot),epsLi([=c1,+hl,c1],dot),epsLi([=c1,c2,-gl],dot),epsLi([=c2,+gl,c2],dot)]
[dui] :: [cFin].%[dui] :: [c1,-hl,-al], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+hl,+al,c1,-hl],dot),epsLi([=c1,+hl,c1],dot),epsLi([=c1,c3],dot),epsLi([=c3,cFin],dot)]
[dí] :: [=c1,+dl,c3].%[dí] :: [=c1,+dl,c2,-sl0], [epsLi([=c2,+sl0,c3],dot)]
[dí] :: [=c1,+dl,c2].%[dí] :: [=c1,+dl,c2,-sl0], [epsLi([=c2,+sl0,c2],dot)]
[dí] :: [=c1,+dl,c2,-sl0].
[dí] :: [=c1,+dl,cFin].%[dí] :: [=c1,+dl,c2,-sl0], [epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[dí] :: [=c1,=c2dl,c3].%[dí] :: [=c1,=c2dl,c2,-sl0], [epsLi([=c2,+sl0,c3],dot)]
[dí] :: [=c1,=c2dl,c2].%[dí] :: [=c1,=c2dl,c2,-sl0], [epsLi([=c2,+sl0,c2],dot)]
[dí] :: [=c1,=c2dl,c2,-sl0].
[dí] :: [=c1,=c2dl,cFin].%[dí] :: [=c1,=c2dl,c2,-sl0], [epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[enta] :: [=c1,+el,c3].%[enta] :: [=c1,+el,c2,-sl0], [epsLi([=c2,+sl0,c3],dot)]
[enta] :: [=c1,+el,c2].%[enta] :: [=c1,+el,c2,-sl0], [epsLi([=c2,+sl0,c2],dot)]
[enta] :: [=c1,+el,c2,-sl0].
[enta] :: [=c1,+el,cFin].%[enta] :: [=c1,+el,c2,-sl0], [epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[enta] :: [=c1,=c2el,c3].%[enta] :: [=c1,=c2el,c2,-sl0], [epsLi([=c2,+sl0,c3],dot)]
[enta] :: [=c1,=c2el,c2].%[enta] :: [=c1,=c2el,c2,-sl0], [epsLi([=c2,+sl0,c2],dot)]
[enta] :: [=c1,=c2el,c2,-sl0].
[enta] :: [=c1,=c2el,cFin].%[enta] :: [=c1,=c2el,c2,-sl0], [epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[esnete] :: [c2,-sl0].%[esnete] :: [c2,-sl0,-gl], [epsLi([=c2,+sl0,+gl,c2,-sl0],dot)]
[esnete] :: [c2,-sl0,-gl].
[esnete] :: [c3].%[esnete] :: [c2,-sl0,-gl], [epsLi([=c2,+sl0,+gl,c2,-sl0],dot),epsLi([=c2,+sl0,c3],dot)]
[esnete] :: [c2].%[esnete] :: [c2,-sl0,-gl], [epsLi([=c2,+gl,c2],dot),epsLi([=c2,+sl0,+gl,c2,-sl0],dot),epsLi([=c2,+sl0,c2],dot)]
[esnete] :: [cFin].%[esnete] :: [c2,-sl0,-gl], [epsLi([=c2,+sl0,+gl,c2,-sl0],dot),epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[esnete] :: [=c1,c3].%[esnete] :: [=c1,c2,-sl0], [epsLi([=c2,+sl0,c3],dot)]
[esnete] :: [=c1,c2].%[esnete] :: [=c1,c2,-sl0], [epsLi([=c2,+sl0,c2],dot)]
[esnete] :: [=c1,c2,-sl0].
[esnete] :: [=c1,cFin].%[esnete] :: [=c1,c2,-sl0], [epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[ester] :: [c1,-al].%[ester] :: [c1,-al,-dl,-il], [epsLi([=c1,+al,+dl,+il,c1,-al],dot)]
[ester] :: [c1,-al,-dl,-il].
[ester] :: [c1].%[ester] :: [c1,-al,-dl,-il], [epsLi([=c1,+il,c1],dot),epsLi([=c1,+dl,c1],dot),epsLi([=c1,+dl,+il,c1,-dl],dot),epsLi([=c1,+al,+dl,+il,c1,-al],dot),epsLi([=c1,+al,c1],dot)]
[ester] :: [c3gl].%[ester] :: [c1,-al,-dl,-il], [epsLi([=c1,+al,+dl,+il,c1,-al],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,c2,-gl],dot),epsLi([=c2,+gl,c3gl],dot)]
[ester] :: [c2].%[ester] :: [c1,-al,-dl,-il], [epsLi([=c1,+al,+dl,+il,c1,-al],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,c2,-gl],dot),epsLi([=c2,+gl,c2],dot)]
[ester] :: [c2,-gl].%[ester] :: [c1,-al,-dl,-il], [epsLi([=c1,+dl,c1],dot),epsLi([=c1,+dl,+il,c1,-dl],dot),epsLi([=c1,+il,c1],dot),epsLi([=c1,+al,+dl,+il,c1,-al],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,c2,-gl],dot)]
[ester] :: [cFin].%[ester] :: [c1,-al,-dl,-il], [epsLi([=c1,+al,+dl,+il,c1,-al],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,c3],dot),epsLi([=c3,cFin],dot)]
[ester] :: [c3].%[ester] :: [c1,-al,-dl,-il], [epsLi([=c1,+dl,c1],dot),epsLi([=c1,+dl,+il,c1,-dl],dot),epsLi([=c1,+il,c1],dot),epsLi([=c1,+al,+dl,+il,c1,-al],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,c3],dot)]
[gres] :: [cFin].%[gres] :: [c3], [epsLi([=c3,cFin],dot)]
[gres] :: [c3].
[gres] :: [=c3gl,=c3fl,cFin].%[gres] :: [=c3gl,=c3fl,c3], [epsLi([=c3,cFin],dot)]
[gres] :: [=c3gl,=c3fl,c3].
[grés] :: [=c1,+il,cFin].%[grés] :: [=c1,+il,c3], [epsLi([=c3,cFin],dot)]
[grés] :: [=c1,+il,c3].
[grés] :: [=c3gl,=c3il,cFin].%[grés] :: [=c3gl,=c3il,c3], [epsLi([=c3,cFin],dot)]
[grés] :: [=c3gl,=c3il,c3].
[jobe] :: [c1,-cl].%[jobe] :: [c1,-cl,-al,-il], [epsLi([=c1,+cl,+al,+il,c1,-cl],dot)]
[jobe] :: [c1,-cl,-al,-il].
[jobe] :: [c2cl].%[jobe] :: [c1,-cl,-al,-il], [epsLi([=c1,+cl,+al,+il,c1,-cl],dot),epsLi([=c1,+cl,c2cl],dot)]
[jobe] :: [c1].%[jobe] :: [c1,-cl,-al,-il], [epsLi([=c1,+il,c1],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,+al,+il,c1,-al],dot),epsLi([=c1,+cl,+al,+il,c1,-cl],dot),epsLi([=c1,+cl,c1],dot)]
[jobe] :: [c3gl].%[jobe] :: [c1,-cl,-al,-il], [epsLi([=c1,+cl,+al,+il,c1,-cl],dot),epsLi([=c1,+cl,c1],dot),epsLi([=c1,c2,-gl],dot),epsLi([=c2,+gl,c3gl],dot)]
[jobe] :: [c2].%[jobe] :: [c1,-cl,-al,-il], [epsLi([=c1,+cl,+al,+il,c1,-cl],dot),epsLi([=c1,+cl,c1],dot),epsLi([=c1,c2,-gl],dot),epsLi([=c2,+gl,c2],dot)]
[jobe] :: [c2,-gl].%[jobe] :: [c1,-cl,-al,-il], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+al,+il,c1,-al],dot),epsLi([=c1,+il,c1],dot),epsLi([=c1,+cl,+al,+il,c1,-cl],dot),epsLi([=c1,+cl,c1],dot),epsLi([=c1,c2,-gl],dot)]
[jobe] :: [cFin].%[jobe] :: [c1,-cl,-al,-il], [epsLi([=c1,+cl,+al,+il,c1,-cl],dot),epsLi([=c1,+cl,c1],dot),epsLi([=c1,c3],dot),epsLi([=c3,cFin],dot)]
[jobe] :: [c3].%[jobe] :: [c1,-cl,-al,-il], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+al,+il,c1,-al],dot),epsLi([=c1,+il,c1],dot),epsLi([=c1,+cl,+al,+il,c1,-cl],dot),epsLi([=c1,+cl,c1],dot),epsLi([=c1,c3],dot)]
[nebel] :: [c1,-al].%[nebel] :: [c1,-al,-il], [epsLi([=c1,+al,+il,c1,-al],dot)]
[nebel] :: [c1,-al,-il].
[nebel] :: [c1].%[nebel] :: [c1,-al,-il], [epsLi([=c1,+il,c1],dot),epsLi([=c1,+al,+il,c1,-al],dot),epsLi([=c1,+al,c1],dot)]
[nebel] :: [c3].%[nebel] :: [c1,-al,-il], [epsLi([=c1,+il,c1],dot),epsLi([=c1,+al,+il,c1,-al],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,c3],dot)]
[nebel] :: [c2,-gl].%[nebel] :: [c1,-al,-il], [epsLi([=c1,+il,c1],dot),epsLi([=c1,+al,+il,c1,-al],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,c2,-gl],dot)]
[nebel] :: [c3gl].%[nebel] :: [c1,-al,-il], [epsLi([=c1,+il,c1],dot),epsLi([=c1,+al,+il,c1,-al],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,c2,-gl],dot),epsLi([=c2,+gl,c3gl],dot)]
[nebel] :: [c2].%[nebel] :: [c1,-al,-il], [epsLi([=c1,+il,c1],dot),epsLi([=c1,+al,+il,c1,-al],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,c2,-gl],dot),epsLi([=c2,+gl,c2],dot)]
[nebel] :: [cFin].%[nebel] :: [c1,-al,-il], [epsLi([=c1,+il,c1],dot),epsLi([=c1,+al,+il,c1,-al],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,c3],dot),epsLi([=c3,cFin],dot)]
[nta] :: [=c1,+cl,c3].%[nta] :: [=c1,+cl,c2,-sl0], [epsLi([=c2,+sl0,c3],dot)]
[nta] :: [=c1,+cl,c2].%[nta] :: [=c1,+cl,c2,-sl0], [epsLi([=c2,+sl0,c2],dot)]
[nta] :: [=c1,+cl,c2,-sl0].
[nta] :: [=c1,+cl,cFin].%[nta] :: [=c1,+cl,c2,-sl0], [epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[nta] :: [=c1,=c2cl,c3].%[nta] :: [=c1,=c2cl,c2,-sl0], [epsLi([=c2,+sl0,c3],dot)]
[nta] :: [=c1,=c2cl,c2].%[nta] :: [=c1,=c2cl,c2,-sl0], [epsLi([=c2,+sl0,c2],dot)]
[nta] :: [=c1,=c2cl,c2,-sl0].
[nta] :: [=c1,=c2cl,cFin].%[nta] :: [=c1,=c2cl,c2,-sl0], [epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[ostar] :: [c1,-al].%[ostar] :: [c1,-al,-dl,-il], [epsLi([=c1,+al,+dl,+il,c1,-al],dot)]
[ostar] :: [c1,-al,-dl,-il].
[ostar] :: [c1].%[ostar] :: [c1,-al,-dl,-il], [epsLi([=c1,+il,c1],dot),epsLi([=c1,+dl,c1],dot),epsLi([=c1,+dl,+il,c1,-dl],dot),epsLi([=c1,+al,+dl,+il,c1,-al],dot),epsLi([=c1,+al,c1],dot)]
[ostar] :: [c3gl].%[ostar] :: [c1,-al,-dl,-il], [epsLi([=c1,+al,+dl,+il,c1,-al],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,c2,-gl],dot),epsLi([=c2,+gl,c3gl],dot)]
[ostar] :: [c2].%[ostar] :: [c1,-al,-dl,-il], [epsLi([=c1,+al,+dl,+il,c1,-al],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,c2,-gl],dot),epsLi([=c2,+gl,c2],dot)]
[ostar] :: [c2,-gl].%[ostar] :: [c1,-al,-dl,-il], [epsLi([=c1,+dl,c1],dot),epsLi([=c1,+dl,+il,c1,-dl],dot),epsLi([=c1,+il,c1],dot),epsLi([=c1,+al,+dl,+il,c1,-al],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,c2,-gl],dot)]
[ostar] :: [cFin].%[ostar] :: [c1,-al,-dl,-il], [epsLi([=c1,+al,+dl,+il,c1,-al],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,c3],dot),epsLi([=c3,cFin],dot)]
[ostar] :: [c3].%[ostar] :: [c1,-al,-dl,-il], [epsLi([=c1,+dl,c1],dot),epsLi([=c1,+dl,+il,c1,-dl],dot),epsLi([=c1,+il,c1],dot),epsLi([=c1,+al,+dl,+il,c1,-al],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,c3],dot)]
[otor] :: [c1,-el].%[otor] :: [c1,-el,-al,-il], [epsLi([=c1,+el,+al,+il,c1,-el],dot)]
[otor] :: [c1,-el,-al,-il].
[otor] :: [c1].%[otor] :: [c1,-el,-al,-il], [epsLi([=c1,+il,c1],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,+al,+il,c1,-al],dot),epsLi([=c1,+el,+al,+il,c1,-el],dot),epsLi([=c1,+el,c1],dot)]
[otor] :: [c2el].%[otor] :: [c1,-el,-al,-il], [epsLi([=c1,+el,+al,+il,c1,-el],dot),epsLi([=c1,+el,c2el],dot)]
[otor] :: [c3gl].%[otor] :: [c1,-el,-al,-il], [epsLi([=c1,+el,+al,+il,c1,-el],dot),epsLi([=c1,+el,c1],dot),epsLi([=c1,c2,-gl],dot),epsLi([=c2,+gl,c3gl],dot)]
[otor] :: [c2].%[otor] :: [c1,-el,-al,-il], [epsLi([=c1,+el,+al,+il,c1,-el],dot),epsLi([=c1,+el,c1],dot),epsLi([=c1,c2,-gl],dot),epsLi([=c2,+gl,c2],dot)]
[otor] :: [c2,-gl].%[otor] :: [c1,-el,-al,-il], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+al,+il,c1,-al],dot),epsLi([=c1,+il,c1],dot),epsLi([=c1,+el,+al,+il,c1,-el],dot),epsLi([=c1,+el,c1],dot),epsLi([=c1,c2,-gl],dot)]
[otor] :: [cFin].%[otor] :: [c1,-el,-al,-il], [epsLi([=c1,+el,+al,+il,c1,-el],dot),epsLi([=c1,+el,c1],dot),epsLi([=c1,c3],dot),epsLi([=c3,cFin],dot)]
[otor] :: [c3].%[otor] :: [c1,-el,-al,-il], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+al,+il,c1,-al],dot),epsLi([=c1,+il,c1],dot),epsLi([=c1,+el,+al,+il,c1,-el],dot),epsLi([=c1,+el,c1],dot),epsLi([=c1,c3],dot)]
[panchardí] :: [c2,-sl0].%[panchardí] :: [c2,-sl0,-gl], [epsLi([=c2,+sl0,+gl,c2,-sl0],dot)]
[panchardí] :: [c2,-sl0,-gl].
[panchardí] :: [c3].%[panchardí] :: [c2,-sl0,-gl], [epsLi([=c2,+sl0,+gl,c2,-sl0],dot),epsLi([=c2,+sl0,c3],dot)]
[panchardí] :: [c2].%[panchardí] :: [c2,-sl0,-gl], [epsLi([=c2,+gl,c2],dot),epsLi([=c2,+sl0,+gl,c2,-sl0],dot),epsLi([=c2,+sl0,c2],dot)]
[panchardí] :: [cFin].%[panchardí] :: [c2,-sl0,-gl], [epsLi([=c2,+sl0,+gl,c2,-sl0],dot),epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[panchardí] :: [=c1,c3].%[panchardí] :: [=c1,c2,-sl0], [epsLi([=c2,+sl0,c3],dot)]
[panchardí] :: [=c1,c2].%[panchardí] :: [=c1,c2,-sl0], [epsLi([=c2,+sl0,c2],dot)]
[panchardí] :: [=c1,c2,-sl0].
[panchardí] :: [=c1,cFin].%[panchardí] :: [=c1,c2,-sl0], [epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[panche] :: [c1,-al].%[panche] :: [c1,-al,-il], [epsLi([=c1,+al,+il,c1,-al],dot)]
[panche] :: [c1,-al,-il].
[panche] :: [c1].%[panche] :: [c1,-al,-il], [epsLi([=c1,+il,c1],dot),epsLi([=c1,+al,+il,c1,-al],dot),epsLi([=c1,+al,c1],dot)]
[panche] :: [c3].%[panche] :: [c1,-al,-il], [epsLi([=c1,+il,c1],dot),epsLi([=c1,+al,+il,c1,-al],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,c3],dot)]
[panche] :: [c2,-gl].%[panche] :: [c1,-al,-il], [epsLi([=c1,+il,c1],dot),epsLi([=c1,+al,+il,c1,-al],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,c2,-gl],dot)]
[panche] :: [c3gl].%[panche] :: [c1,-al,-il], [epsLi([=c1,+il,c1],dot),epsLi([=c1,+al,+il,c1,-al],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,c2,-gl],dot),epsLi([=c2,+gl,c3gl],dot)]
[panche] :: [c2].%[panche] :: [c1,-al,-il], [epsLi([=c1,+il,c1],dot),epsLi([=c1,+al,+il,c1,-al],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,c2,-gl],dot),epsLi([=c2,+gl,c2],dot)]
[panche] :: [cFin].%[panche] :: [c1,-al,-il], [epsLi([=c1,+il,c1],dot),epsLi([=c1,+al,+il,c1,-al],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,c3],dot),epsLi([=c3,cFin],dot)]
[sgrés] :: [=c1,+hl,cFin].%[sgrés] :: [=c1,+hl,c3], [epsLi([=c3,cFin],dot)]
[sgrés] :: [=c1,+hl,c3].
[sgrés] :: [=c3gl,=c3hl,cFin].%[sgrés] :: [=c3gl,=c3hl,c3], [epsLi([=c3,cFin],dot)]
[sgrés] :: [=c3gl,=c3hl,c3].
[trianda] :: [c2,-sl0].%[trianda] :: [c2,-sl0,-gl], [epsLi([=c2,+sl0,+gl,c2,-sl0],dot)]
[trianda] :: [c2,-sl0,-gl].
[trianda] :: [c3].%[trianda] :: [c2,-sl0,-gl], [epsLi([=c2,+sl0,+gl,c2,-sl0],dot),epsLi([=c2,+sl0,c3],dot)]
[trianda] :: [c2].%[trianda] :: [c2,-sl0,-gl], [epsLi([=c2,+gl,c2],dot),epsLi([=c2,+sl0,+gl,c2,-sl0],dot),epsLi([=c2,+sl0,c2],dot)]
[trianda] :: [cFin].%[trianda] :: [c2,-sl0,-gl], [epsLi([=c2,+sl0,+gl,c2,-sl0],dot),epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[trianda] :: [=c1,c3].%[trianda] :: [=c1,c2,-sl0], [epsLi([=c2,+sl0,c3],dot)]
[trianda] :: [=c1,c2].%[trianda] :: [=c1,c2,-sl0], [epsLi([=c2,+sl0,c2],dot)]
[trianda] :: [=c1,c2,-sl0].
[trianda] :: [=c1,cFin].%[trianda] :: [=c1,c2,-sl0], [epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[trin] :: [c1,-al].%[trin] :: [c1,-al,-il], [epsLi([=c1,+al,+il,c1,-al],dot)]
[trin] :: [c1,-al,-il].
[trin] :: [c1].%[trin] :: [c1,-al,-il], [epsLi([=c1,+il,c1],dot),epsLi([=c1,+al,+il,c1,-al],dot),epsLi([=c1,+al,c1],dot)]
[trin] :: [c3].%[trin] :: [c1,-al,-il], [epsLi([=c1,+il,c1],dot),epsLi([=c1,+al,+il,c1,-al],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,c3],dot)]
[trin] :: [c2,-gl].%[trin] :: [c1,-al,-il], [epsLi([=c1,+il,c1],dot),epsLi([=c1,+al,+il,c1,-al],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,c2,-gl],dot)]
[trin] :: [c3gl].%[trin] :: [c1,-al,-il], [epsLi([=c1,+il,c1],dot),epsLi([=c1,+al,+il,c1,-al],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,c2,-gl],dot),epsLi([=c2,+gl,c3gl],dot)]
[trin] :: [c2].%[trin] :: [c1,-al,-il], [epsLi([=c1,+il,c1],dot),epsLi([=c1,+al,+il,c1,-al],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,c2,-gl],dot),epsLi([=c2,+gl,c2],dot)]
[trin] :: [cFin].%[trin] :: [c1,-al,-il], [epsLi([=c1,+il,c1],dot),epsLi([=c1,+al,+il,c1,-al],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,c3],dot),epsLi([=c3,cFin],dot)]
[yedeque] :: [c2,-sl0].%[yedeque] :: [c2,-sl0,-gl], [epsLi([=c2,+sl0,+gl,c2,-sl0],dot)]
[yedeque] :: [c2,-sl0,-gl].
[yedeque] :: [c3].%[yedeque] :: [c2,-sl0,-gl], [epsLi([=c2,+sl0,+gl,c2,-sl0],dot),epsLi([=c2,+sl0,c3],dot)]
[yedeque] :: [c2].%[yedeque] :: [c2,-sl0,-gl], [epsLi([=c2,+gl,c2],dot),epsLi([=c2,+sl0,+gl,c2,-sl0],dot),epsLi([=c2,+sl0,c2],dot)]
[yedeque] :: [cFin].%[yedeque] :: [c2,-sl0,-gl], [epsLi([=c2,+sl0,+gl,c2,-sl0],dot),epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[yeque] :: [c3fl].%[yeque] :: [c1,-fl], [epsLi([=c1,+fl,c3fl],dot)]
[yeque] :: [c1].%[yeque] :: [c1,-fl], [epsLi([=c1,+fl,c1],dot)]
[yeque] :: [c1,-fl].
[yeque] :: [c3].%[yeque] :: [c1,-fl], [epsLi([=c1,+fl,c1],dot),epsLi([=c1,c3],dot)]
[yeque] :: [c2,-gl].%[yeque] :: [c1,-fl], [epsLi([=c1,+fl,c1],dot),epsLi([=c1,c2,-gl],dot)]
[yeque] :: [cFin].%[yeque] :: [c1,-fl], [epsLi([=c1,+fl,c1],dot),epsLi([=c1,c3],dot),epsLi([=c3,cFin],dot)]
[yeque] :: [c3gl].%[yeque] :: [c1,-fl], [epsLi([=c1,+fl,c1],dot),epsLi([=c1,c2,-gl],dot),epsLi([=c2,+gl,c3gl],dot)]
[yeque] :: [c2].%[yeque] :: [c1,-fl], [epsLi([=c1,+fl,c1],dot),epsLi([=c1,c2,-gl],dot),epsLi([=c2,+gl,c2],dot)]
[bin] :: [c3gl].%[bin] :: [c2,-sl0,-gl], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+gl,c3gl],dot)]
[deque] :: [c3gl].%[deque] :: [c2,-sl0,-gl], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+gl,c3gl],dot)]
[esnete] :: [c3gl].%[esnete] :: [c2,-sl0,-gl], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+gl,c3gl],dot)]
[ester] :: [c2dl].%[ester] :: [c1,-al,-dl,-il], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+dl,+il,c1,-dl],dot),epsLi([=c1,+dl,c2dl],dot)]
[ester] :: [c1,-dl].%[ester] :: [c1,-al,-dl,-il], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+dl,+il,c1,-dl],dot)]
[jobe] :: [c1,-al].%[jobe] :: [c1,-cl,-al,-il], [epsLi([=c1,+cl,c1],dot),epsLi([=c1,+al,+il,c1,-al],dot)]
[nebel] :: [c3il].%[nebel] :: [c1,-al,-il], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+il,c3il],dot)]
[ostar] :: [c2dl].%[ostar] :: [c1,-al,-dl,-il], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+dl,+il,c1,-dl],dot),epsLi([=c1,+dl,c2dl],dot)]
[ostar] :: [c1,-dl].%[ostar] :: [c1,-al,-dl,-il], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+dl,+il,c1,-dl],dot)]
[otor] :: [c1,-al].%[otor] :: [c1,-el,-al,-il], [epsLi([=c1,+el,c1],dot),epsLi([=c1,+al,+il,c1,-al],dot)]
[panchardí] :: [c3gl].%[panchardí] :: [c2,-sl0,-gl], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+gl,c3gl],dot)]
[panche] :: [c3il].%[panche] :: [c1,-al,-il], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+il,c3il],dot)]
[trianda] :: [c3gl].%[trianda] :: [c2,-sl0,-gl], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+gl,c3gl],dot)]
[trin] :: [c3il].%[trin] :: [c1,-al,-il], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+il,c3il],dot)]
[yedeque] :: [c3gl].%[yedeque] :: [c2,-sl0,-gl], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+gl,c3gl],dot)]
