startCategory(cFin(_)).
[tři] :: [c3fl].%[tři] :: [c1,-bl,-al,-fl], [epsLi([=c1,+bl,c1],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,+fl,c3fl],dot)]
[sedm] :: [c3gl].%[sedm] :: [c1,-al,-dl,-gl], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+dl,c1],dot),epsLi([=c1,+gl,c3gl],dot)]
[osm] :: [c3gl].%[osm] :: [c1,-al,-dl,-gl], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+dl,c1],dot),epsLi([=c1,+gl,c3gl],dot)]
[cet] :: [=c1,+bl,c3].%[cet] :: [=c1,+bl,c2,-sl0], [epsLi([=c2,+sl0,c3],dot)]
[cet] :: [=c1,+bl,c2].%[cet] :: [=c1,+bl,c2,-sl0], [epsLi([=c2,+sl0,c2],dot)]
[cet] :: [=c1,+bl,c2,-sl0].
[cet] :: [=c1,+bl,cFin].%[cet] :: [=c1,+bl,c2,-sl0], [epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[cet] :: [=c1,=c2bl,c3].%[cet] :: [=c1,=c2bl,c2,-sl0], [epsLi([=c2,+sl0,c3],dot)]
[cet] :: [=c1,=c2bl,c2].%[cet] :: [=c1,=c2bl,c2,-sl0], [epsLi([=c2,+sl0,c2],dot)]
[cet] :: [=c1,=c2bl,c2,-sl0].
[cet] :: [=c1,=c2bl,cFin].%[cet] :: [=c1,=c2bl,c2,-sl0], [epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[deset] :: [c2,-el].%[deset] :: [c2,-el,-sl0], [epsLi([=c2,+el,+sl0,c2,-el],dot)]
[deset] :: [c2,-el,-sl0].
[deset] :: [c2].%[deset] :: [c2,-el,-sl0], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c2],dot)]
[deset] :: [c3el].%[deset] :: [c2,-el,-sl0], [epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c3el],dot)]
[desát] :: [=c1,+dl,c3].%[desát] :: [=c1,+dl,c2,-sl0], [epsLi([=c2,+sl0,c3],dot)]
[desát] :: [=c1,+dl,c2].%[desát] :: [=c1,+dl,c2,-sl0], [epsLi([=c2,+sl0,c2],dot)]
[desát] :: [=c1,+dl,c2,-sl0].
[desát] :: [=c1,+dl,cFin].%[desát] :: [=c1,+dl,c2,-sl0], [epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[desát] :: [=c1,=c2dl,c3].%[desát] :: [=c1,=c2dl,c2,-sl0], [epsLi([=c2,+sl0,c3],dot)]
[desát] :: [=c1,=c2dl,c2].%[desát] :: [=c1,=c2dl,c2,-sl0], [epsLi([=c2,+sl0,c2],dot)]
[desát] :: [=c1,=c2dl,c2,-sl0].
[desát] :: [=c1,=c2dl,cFin].%[desát] :: [=c1,=c2dl,c2,-sl0], [epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[devadesát] :: [c2,-el].%[devadesát] :: [c2,-el,-sl0], [epsLi([=c2,+el,+sl0,c2,-el],dot)]
[devadesát] :: [c2,-el,-sl0].
[devadesát] :: [c2].%[devadesát] :: [c2,-el,-sl0], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c2],dot)]
[devadesát] :: [c3el].%[devadesát] :: [c2,-el,-sl0], [epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c3el],dot)]
[devadesát] :: [=c1,c3].%[devadesát] :: [=c1,c2,-sl0], [epsLi([=c2,+sl0,c3],dot)]
[devadesát] :: [=c1,c2].%[devadesát] :: [=c1,c2,-sl0], [epsLi([=c2,+sl0,c2],dot)]
[devadesát] :: [=c1,c2,-sl0].
[devadesát] :: [=c1,cFin].%[devadesát] :: [=c1,c2,-sl0], [epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[devatenáct] :: [c2,-el].%[devatenáct] :: [c2,-el,-sl0], [epsLi([=c2,+el,+sl0,c2,-el],dot)]
[devatenáct] :: [c2,-el,-sl0].
[devatenáct] :: [c2].%[devatenáct] :: [c2,-el,-sl0], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c2],dot)]
[devatenáct] :: [c3el].%[devatenáct] :: [c2,-el,-sl0], [epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c3el],dot)]
[devět] :: [c3gl].%[devět] :: [c1,-gl], [epsLi([=c1,+gl,c3gl],dot)]
[devět] :: [c1].%[devět] :: [c1,-gl], [epsLi([=c1,+gl,c1],dot)]
[devět] :: [c1,-gl].
[devět] :: [c2,-el].%[devět] :: [c1,-gl], [epsLi([=c1,+gl,c1],dot),epsLi([=c1,c2,-el],dot)]
[devět] :: [c3].%[devět] :: [c1,-gl], [epsLi([=c1,+gl,c1],dot),epsLi([=c1,c3],dot)]
[devět] :: [c2].%[devět] :: [c1,-gl], [epsLi([=c1,+gl,c1],dot),epsLi([=c1,c2,-el],dot),epsLi([=c2,+el,c2],dot)]
[devět] :: [c3el].%[devět] :: [c1,-gl], [epsLi([=c1,+gl,c1],dot),epsLi([=c1,c2,-el],dot),epsLi([=c2,+el,c3el],dot)]
[devět] :: [cFin].%[devět] :: [c1,-gl], [epsLi([=c1,+gl,c1],dot),epsLi([=c1,c3],dot),epsLi([=c3,cFin],dot)]
[dva] :: [c1,-bl].%[dva] :: [c1,-bl,-al], [epsLi([=c1,+bl,+al,c1,-bl],dot)]
[dva] :: [c1,-bl,-al].
[dva] :: [c2bl].%[dva] :: [c1,-bl,-al], [epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+bl,c2bl],dot)]
[dva] :: [c1].%[dva] :: [c1,-bl,-al], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+bl,c1],dot)]
[dva] :: [c2,-el].%[dva] :: [c1,-bl,-al], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-el],dot)]
[dva] :: [c3].%[dva] :: [c1,-bl,-al], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c3],dot)]
[dva] :: [cFin].%[dva] :: [c1,-bl,-al], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c3],dot),epsLi([=c3,cFin],dot)]
[dva] :: [c2].%[dva] :: [c1,-bl,-al], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-el],dot),epsLi([=c2,+el,c2],dot)]
[dva] :: [c3el].%[dva] :: [c1,-bl,-al], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-el],dot),epsLi([=c2,+el,c3el],dot)]
[dvě_stě] :: [cFin].%[dvě_stě] :: [c3], [epsLi([=c3,cFin],dot)]
[dvě_stě] :: [c3].
[dvě_stě] :: [=c3el,cFin].%[dvě_stě] :: [=c3el,c3], [epsLi([=c3,cFin],dot)]
[dvě_stě] :: [=c3el,c3].
[jedenáct] :: [c2,-el].%[jedenáct] :: [c2,-el,-sl0], [epsLi([=c2,+el,+sl0,c2,-el],dot)]
[jedenáct] :: [c2,-el,-sl0].
[jedenáct] :: [c2].%[jedenáct] :: [c2,-el,-sl0], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c2],dot)]
[jedenáct] :: [c3el].%[jedenáct] :: [c2,-el,-sl0], [epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c3el],dot)]
[jedna] :: [c2,-el].%[jedna] :: [c1], [epsLi([=c1,c2,-el],dot)]
[jedna] :: [c3].%[jedna] :: [c1], [epsLi([=c1,c3],dot)]
[jedna] :: [c1].
[jedna] :: [cFin].%[jedna] :: [c1], [epsLi([=c1,c3],dot),epsLi([=c3,cFin],dot)]
[jedna] :: [c2].%[jedna] :: [c1], [epsLi([=c1,c2,-el],dot),epsLi([=c2,+el,c2],dot)]
[jedna] :: [c3el].%[jedna] :: [c1], [epsLi([=c1,c2,-el],dot),epsLi([=c2,+el,c3el],dot)]
[náct] :: [=c1,+al,c3].%[náct] :: [=c1,+al,c2,-sl0], [epsLi([=c2,+sl0,c3],dot)]
[náct] :: [=c1,+al,c2].%[náct] :: [=c1,+al,c2,-sl0], [epsLi([=c2,+sl0,c2],dot)]
[náct] :: [=c1,+al,c2,-sl0].
[náct] :: [=c1,+al,cFin].%[náct] :: [=c1,+al,c2,-sl0], [epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[osm] :: [c1,-al].%[osm] :: [c1,-al,-dl,-gl], [epsLi([=c1,+al,+dl,+gl,c1,-al],dot)]
[osm] :: [c1,-al,-dl,-gl].
[osm] :: [c1].%[osm] :: [c1,-al,-dl,-gl], [epsLi([=c1,+gl,c1],dot),epsLi([=c1,+dl,c1],dot),epsLi([=c1,+dl,+gl,c1,-dl],dot),epsLi([=c1,+al,+dl,+gl,c1,-al],dot),epsLi([=c1,+al,c1],dot)]
[osm] :: [cFin].%[osm] :: [c1,-al,-dl,-gl], [epsLi([=c1,+al,+dl,+gl,c1,-al],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,c3],dot),epsLi([=c3,cFin],dot)]
[osm] :: [c3].%[osm] :: [c1,-al,-dl,-gl], [epsLi([=c1,+dl,c1],dot),epsLi([=c1,+dl,+gl,c1,-dl],dot),epsLi([=c1,+gl,c1],dot),epsLi([=c1,+al,+dl,+gl,c1,-al],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,c3],dot)]
[osm] :: [c2].%[osm] :: [c1,-al,-dl,-gl], [epsLi([=c1,+al,+dl,+gl,c1,-al],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,c2,-el],dot),epsLi([=c2,+el,c2],dot)]
[osm] :: [c3el].%[osm] :: [c1,-al,-dl,-gl], [epsLi([=c1,+al,+dl,+gl,c1,-al],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,c2,-el],dot),epsLi([=c2,+el,c3el],dot)]
[osm] :: [c2,-el].%[osm] :: [c1,-al,-dl,-gl], [epsLi([=c1,+dl,c1],dot),epsLi([=c1,+dl,+gl,c1,-dl],dot),epsLi([=c1,+gl,c1],dot),epsLi([=c1,+al,+dl,+gl,c1,-al],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,c2,-el],dot)]
[padesát] :: [c2,-el].%[padesát] :: [c2,-el,-sl0], [epsLi([=c2,+el,+sl0,c2,-el],dot)]
[padesát] :: [c2,-el,-sl0].
[padesát] :: [c2].%[padesát] :: [c2,-el,-sl0], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c2],dot)]
[padesát] :: [c3el].%[padesát] :: [c2,-el,-sl0], [epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c3el],dot)]
[padesát] :: [=c1,c3].%[padesát] :: [=c1,c2,-sl0], [epsLi([=c2,+sl0,c3],dot)]
[padesát] :: [=c1,c2].%[padesát] :: [=c1,c2,-sl0], [epsLi([=c2,+sl0,c2],dot)]
[padesát] :: [=c1,c2,-sl0].
[padesát] :: [=c1,cFin].%[padesát] :: [=c1,c2,-sl0], [epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[patnáct] :: [c2,-el].%[patnáct] :: [c2,-el,-sl0], [epsLi([=c2,+el,+sl0,c2,-el],dot)]
[patnáct] :: [c2,-el,-sl0].
[patnáct] :: [c2].%[patnáct] :: [c2,-el,-sl0], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c2],dot)]
[patnáct] :: [c3el].%[patnáct] :: [c2,-el,-sl0], [epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c3el],dot)]
[pět] :: [c3gl].%[pět] :: [c1,-gl], [epsLi([=c1,+gl,c3gl],dot)]
[pět] :: [c1].%[pět] :: [c1,-gl], [epsLi([=c1,+gl,c1],dot)]
[pět] :: [c1,-gl].
[pět] :: [c2,-el].%[pět] :: [c1,-gl], [epsLi([=c1,+gl,c1],dot),epsLi([=c1,c2,-el],dot)]
[pět] :: [c3].%[pět] :: [c1,-gl], [epsLi([=c1,+gl,c1],dot),epsLi([=c1,c3],dot)]
[pět] :: [c2].%[pět] :: [c1,-gl], [epsLi([=c1,+gl,c1],dot),epsLi([=c1,c2,-el],dot),epsLi([=c2,+el,c2],dot)]
[pět] :: [c3el].%[pět] :: [c1,-gl], [epsLi([=c1,+gl,c1],dot),epsLi([=c1,c2,-el],dot),epsLi([=c2,+el,c3el],dot)]
[pět] :: [cFin].%[pět] :: [c1,-gl], [epsLi([=c1,+gl,c1],dot),epsLi([=c1,c3],dot),epsLi([=c3,cFin],dot)]
[sedm] :: [c1,-al].%[sedm] :: [c1,-al,-dl,-gl], [epsLi([=c1,+al,+dl,+gl,c1,-al],dot)]
[sedm] :: [c1,-al,-dl,-gl].
[sedm] :: [c1].%[sedm] :: [c1,-al,-dl,-gl], [epsLi([=c1,+gl,c1],dot),epsLi([=c1,+dl,c1],dot),epsLi([=c1,+dl,+gl,c1,-dl],dot),epsLi([=c1,+al,+dl,+gl,c1,-al],dot),epsLi([=c1,+al,c1],dot)]
[sedm] :: [cFin].%[sedm] :: [c1,-al,-dl,-gl], [epsLi([=c1,+al,+dl,+gl,c1,-al],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,c3],dot),epsLi([=c3,cFin],dot)]
[sedm] :: [c3].%[sedm] :: [c1,-al,-dl,-gl], [epsLi([=c1,+dl,c1],dot),epsLi([=c1,+dl,+gl,c1,-dl],dot),epsLi([=c1,+gl,c1],dot),epsLi([=c1,+al,+dl,+gl,c1,-al],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,c3],dot)]
[sedm] :: [c2].%[sedm] :: [c1,-al,-dl,-gl], [epsLi([=c1,+al,+dl,+gl,c1,-al],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,c2,-el],dot),epsLi([=c2,+el,c2],dot)]
[sedm] :: [c3el].%[sedm] :: [c1,-al,-dl,-gl], [epsLi([=c1,+al,+dl,+gl,c1,-al],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,c2,-el],dot),epsLi([=c2,+el,c3el],dot)]
[sedm] :: [c2,-el].%[sedm] :: [c1,-al,-dl,-gl], [epsLi([=c1,+dl,c1],dot),epsLi([=c1,+dl,+gl,c1,-dl],dot),epsLi([=c1,+gl,c1],dot),epsLi([=c1,+al,+dl,+gl,c1,-al],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,c2,-el],dot)]
[set] :: [=c1,+gl,cFin].%[set] :: [=c1,+gl,c3], [epsLi([=c3,cFin],dot)]
[set] :: [=c1,+gl,c3].
[set] :: [=c3el,=c3gl,cFin].%[set] :: [=c3el,=c3gl,c3], [epsLi([=c3,cFin],dot)]
[set] :: [=c3el,=c3gl,c3].
[sta] :: [=c1,+fl,cFin].%[sta] :: [=c1,+fl,c3], [epsLi([=c3,cFin],dot)]
[sta] :: [=c1,+fl,c3].
[sta] :: [=c3el,=c3fl,cFin].%[sta] :: [=c3el,=c3fl,c3], [epsLi([=c3,cFin],dot)]
[sta] :: [=c3el,=c3fl,c3].
[sto] :: [cFin].%[sto] :: [c3], [epsLi([=c3,cFin],dot)]
[sto] :: [c3].
[sto] :: [=c3el,cFin].%[sto] :: [=c3el,c3], [epsLi([=c3,cFin],dot)]
[sto] :: [=c3el,c3].
[tři] :: [c1,-bl].%[tři] :: [c1,-bl,-al,-fl], [epsLi([=c1,+bl,+fl,c1,-bl],dot),epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+bl,+al,+fl,c1,-bl],dot)]
[tři] :: [c1,-bl,-al,-fl].
[tři] :: [c2bl].%[tři] :: [c1,-bl,-al,-fl], [epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+bl,+fl,c1,-bl],dot),epsLi([=c1,+bl,+al,+fl,c1,-bl],dot),epsLi([=c1,+bl,c2bl],dot)]
[tři] :: [c1].%[tři] :: [c1,-bl,-al,-fl], [epsLi([=c1,+fl,c1],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,+al,+fl,c1,-al],dot),epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+bl,+fl,c1,-bl],dot),epsLi([=c1,+bl,+al,+fl,c1,-bl],dot),epsLi([=c1,+bl,c1],dot)]
[tři] :: [cFin].%[tři] :: [c1,-bl,-al,-fl], [epsLi([=c1,+bl,+al,+fl,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c3],dot),epsLi([=c3,cFin],dot)]
[tři] :: [c3].%[tři] :: [c1,-bl,-al,-fl], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+al,+fl,c1,-al],dot),epsLi([=c1,+bl,+fl,c1,-bl],dot),epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+fl,c1],dot),epsLi([=c1,+bl,+al,+fl,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c3],dot)]
[tři] :: [c2].%[tři] :: [c1,-bl,-al,-fl], [epsLi([=c1,+bl,+al,+fl,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-el],dot),epsLi([=c2,+el,c2],dot)]
[tři] :: [c3el].%[tři] :: [c1,-bl,-al,-fl], [epsLi([=c1,+bl,+al,+fl,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-el],dot),epsLi([=c2,+el,c3el],dot)]
[tři] :: [c2,-el].%[tři] :: [c1,-bl,-al,-fl], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+al,+fl,c1,-al],dot),epsLi([=c1,+bl,+fl,c1,-bl],dot),epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+fl,c1],dot),epsLi([=c1,+bl,+al,+fl,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-el],dot)]
[čtrnáct] :: [c2,-el].%[čtrnáct] :: [c2,-el,-sl0], [epsLi([=c2,+el,+sl0,c2,-el],dot)]
[čtrnáct] :: [c2,-el,-sl0].
[čtrnáct] :: [c2].%[čtrnáct] :: [c2,-el,-sl0], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c2],dot)]
[čtrnáct] :: [c3el].%[čtrnáct] :: [c2,-el,-sl0], [epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c3el],dot)]
[čtyři] :: [c1,-bl].%[čtyři] :: [c1,-bl,-fl], [epsLi([=c1,+bl,+fl,c1,-bl],dot)]
[čtyři] :: [c1,-bl,-fl].
[čtyři] :: [c2bl].%[čtyři] :: [c1,-bl,-fl], [epsLi([=c1,+bl,+fl,c1,-bl],dot),epsLi([=c1,+bl,c2bl],dot)]
[čtyři] :: [c1].%[čtyři] :: [c1,-bl,-fl], [epsLi([=c1,+fl,c1],dot),epsLi([=c1,+bl,+fl,c1,-bl],dot),epsLi([=c1,+bl,c1],dot)]
[čtyři] :: [c2,-el].%[čtyři] :: [c1,-bl,-fl], [epsLi([=c1,+fl,c1],dot),epsLi([=c1,+bl,+fl,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-el],dot)]
[čtyři] :: [c3].%[čtyři] :: [c1,-bl,-fl], [epsLi([=c1,+fl,c1],dot),epsLi([=c1,+bl,+fl,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c3],dot)]
[čtyři] :: [cFin].%[čtyři] :: [c1,-bl,-fl], [epsLi([=c1,+fl,c1],dot),epsLi([=c1,+bl,+fl,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c3],dot),epsLi([=c3,cFin],dot)]
[čtyři] :: [c2].%[čtyři] :: [c1,-bl,-fl], [epsLi([=c1,+fl,c1],dot),epsLi([=c1,+bl,+fl,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-el],dot),epsLi([=c2,+el,c2],dot)]
[čtyři] :: [c3el].%[čtyři] :: [c1,-bl,-fl], [epsLi([=c1,+fl,c1],dot),epsLi([=c1,+bl,+fl,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-el],dot),epsLi([=c2,+el,c3el],dot)]
[šedesát] :: [c2,-el].%[šedesát] :: [c2,-el,-sl0], [epsLi([=c2,+el,+sl0,c2,-el],dot)]
[šedesát] :: [c2,-el,-sl0].
[šedesát] :: [c2].%[šedesát] :: [c2,-el,-sl0], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c2],dot)]
[šedesát] :: [c3el].%[šedesát] :: [c2,-el,-sl0], [epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c3el],dot)]
[šedesát] :: [=c1,c3].%[šedesát] :: [=c1,c2,-sl0], [epsLi([=c2,+sl0,c3],dot)]
[šedesát] :: [=c1,c2].%[šedesát] :: [=c1,c2,-sl0], [epsLi([=c2,+sl0,c2],dot)]
[šedesát] :: [=c1,c2,-sl0].
[šedesát] :: [=c1,cFin].%[šedesát] :: [=c1,c2,-sl0], [epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[šest] :: [c1,-al].%[šest] :: [c1,-al,-gl], [epsLi([=c1,+al,+gl,c1,-al],dot)]
[šest] :: [c1,-al,-gl].
[šest] :: [c1].%[šest] :: [c1,-al,-gl], [epsLi([=c1,+gl,c1],dot),epsLi([=c1,+al,+gl,c1,-al],dot),epsLi([=c1,+al,c1],dot)]
[šest] :: [c2,-el].%[šest] :: [c1,-al,-gl], [epsLi([=c1,+gl,c1],dot),epsLi([=c1,+al,+gl,c1,-al],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,c2,-el],dot)]
[šest] :: [c3].%[šest] :: [c1,-al,-gl], [epsLi([=c1,+gl,c1],dot),epsLi([=c1,+al,+gl,c1,-al],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,c3],dot)]
[šest] :: [cFin].%[šest] :: [c1,-al,-gl], [epsLi([=c1,+gl,c1],dot),epsLi([=c1,+al,+gl,c1,-al],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,c3],dot),epsLi([=c3,cFin],dot)]
[šest] :: [c2].%[šest] :: [c1,-al,-gl], [epsLi([=c1,+gl,c1],dot),epsLi([=c1,+al,+gl,c1,-al],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,c2,-el],dot),epsLi([=c2,+el,c2],dot)]
[šest] :: [c3el].%[šest] :: [c1,-al,-gl], [epsLi([=c1,+gl,c1],dot),epsLi([=c1,+al,+gl,c1,-al],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,c2,-el],dot),epsLi([=c2,+el,c3el],dot)]
[deset] :: [cFin].%[deset] :: [c2,-el,-sl0], [epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[deset] :: [c3].%[deset] :: [c2,-el,-sl0], [epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot)]
[devadesát] :: [cFin].%[devadesát] :: [c2,-el,-sl0], [epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[devadesát] :: [c3].%[devadesát] :: [c2,-el,-sl0], [epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot)]
[devatenáct] :: [cFin].%[devatenáct] :: [c2,-el,-sl0], [epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[devatenáct] :: [c3].%[devatenáct] :: [c2,-el,-sl0], [epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot)]
[jedenáct] :: [cFin].%[jedenáct] :: [c2,-el,-sl0], [epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[jedenáct] :: [c3].%[jedenáct] :: [c2,-el,-sl0], [epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot)]
[osm] :: [c2dl].%[osm] :: [c1,-al,-dl,-gl], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+dl,+gl,c1,-dl],dot),epsLi([=c1,+dl,c2dl],dot)]
[osm] :: [c1,-dl].%[osm] :: [c1,-al,-dl,-gl], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+dl,+gl,c1,-dl],dot)]
[padesát] :: [cFin].%[padesát] :: [c2,-el,-sl0], [epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[padesát] :: [c3].%[padesát] :: [c2,-el,-sl0], [epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot)]
[patnáct] :: [cFin].%[patnáct] :: [c2,-el,-sl0], [epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[patnáct] :: [c3].%[patnáct] :: [c2,-el,-sl0], [epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot)]
[sedm] :: [c2dl].%[sedm] :: [c1,-al,-dl,-gl], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+dl,+gl,c1,-dl],dot),epsLi([=c1,+dl,c2dl],dot)]
[sedm] :: [c1,-dl].%[sedm] :: [c1,-al,-dl,-gl], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+dl,+gl,c1,-dl],dot)]
[tři] :: [c1,-al].%[tři] :: [c1,-bl,-al,-fl], [epsLi([=c1,+bl,c1],dot),epsLi([=c1,+al,+fl,c1,-al],dot)]
[čtrnáct] :: [cFin].%[čtrnáct] :: [c2,-el,-sl0], [epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[čtrnáct] :: [c3].%[čtrnáct] :: [c2,-el,-sl0], [epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot)]
[čtyři] :: [c3fl].%[čtyři] :: [c1,-bl,-fl], [epsLi([=c1,+bl,c1],dot),epsLi([=c1,+fl,c3fl],dot)]
[šedesát] :: [cFin].%[šedesát] :: [c2,-el,-sl0], [epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[šedesát] :: [c3].%[šedesát] :: [c2,-el,-sl0], [epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot)]
[šest] :: [c3gl].%[šest] :: [c1,-al,-gl], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+gl,c3gl],dot)]
