startCategory(c4).
[y] :: ([=c1,=cee,c3]).
[y] :: ([=c1,=cee,c4]).
[y] :: ([=c1,=cee,c2]).
[y] :: ([=c1,+ee,c3]).
[y] :: ([=c1,+ee,c4]).
[y] :: ([=c1,+ee,c2]).
[ty] :: ([=c1,=ctee,c3]).
[ty] :: ([=c1,=ctee,c4]).
[ty] :: ([=c1,=ctee,c2]).
[ty] :: ([=c1,+tee,c3]).
[ty] :: ([=c1,+tee,c4]).
[ty] :: ([=c1,+tee,c2]).
[two] :: ([c4]).
[two] :: ([c3]).
[two] :: ([c2]).
[two] :: ([c1]).
[twenty] :: ([=c1,c3]).
[twenty] :: ([=c1,c4]).
[twenty] :: ([=c1,c2]).
[twenty] :: ([c3]).
[twenty] :: ([c4]).
[twenty] :: ([c2]).
[twelve] :: ([c3]).
[twelve] :: ([c4]).
[twelve] :: ([c2]).
[three] :: ([c4]).
[three] :: ([c3]).
[three] :: ([c2]).
[three] :: ([c1]).
[thousand] :: ([=cnix,=c3,c4]).
[thousand] :: ([=c3,=c3,c4]).
[thirty] :: ([=c1,c3]).
[thirty] :: ([=c1,c4]).
[thirty] :: ([=c1,c2]).
[thirty] :: ([c3]).
[thirty] :: ([c4]).
[thirty] :: ([c2]).
[thirteen] :: ([c3]).
[thirteen] :: ([c4]).
[thirteen] :: ([c2]).
[ten] :: ([c3]).
[ten] :: ([c4]).
[ten] :: ([c2]).
[teen] :: ([=c1,+tee,c3]).
[teen] :: ([=c1,+tee,c4]).
[teen] :: ([=c1,+tee,c2]).
[six] :: ([c4]).
[six] :: ([c3]).
[six] :: ([ctee]).
[six] :: ([c1]).
[six] :: ([c2]).
[six] :: ([c1,-tee]).
[seven] :: ([c4]).
[seven] :: ([c3]).
[seven] :: ([ctee]).
[seven] :: ([c1]).
[seven] :: ([c2]).
[seven] :: ([c1,-tee]).
[one] :: ([c4]).
[one] :: ([c3]).
[one] :: ([c2]).
[one] :: ([c1]).
[nine] :: ([c4]).
[nine] :: ([c3]).
[nine] :: ([ctee]).
[nine] :: ([c1]).
[nine] :: ([c2]).
[nine] :: ([c1,-tee]).
[hundredand] :: ([=c2,=c1,c4]).
[hundredand] :: ([=c2,=c1,c3]).
[hundred] :: ([=cnix,=c1,c4]).
[hundred] :: ([=cnix,=c1,c3]).
[four] :: ([c4]).
[four] :: ([c3]).
[four] :: ([ctee]).
[four] :: ([c1]).
[four] :: ([c2]).
[four] :: ([c1,-tee]).
[five] :: ([c4]).
[five] :: ([c3]).
[five] :: ([c2]).
[five] :: ([c1]).
[fifty] :: ([=c1,c3]).
[fifty] :: ([=c1,c4]).
[fifty] :: ([=c1,c2]).
[fifty] :: ([c3]).
[fifty] :: ([c4]).
[fifty] :: ([c2]).
[fifteen] :: ([c3]).
[fifteen] :: ([c4]).
[fifteen] :: ([c2]).
[eleven] :: ([c3]).
[eleven] :: ([c4]).
[eleven] :: ([c2]).
[eight] :: ([c3]).
[eight] :: ([c4]).
[eight] :: ([c2]).
[eight] :: ([c1]).
[eight] :: ([cee]).
[eight] :: ([c1,-ee]).
[een] :: ([=c1,+ee,c3]).
[een] :: ([=c1,+ee,c4]).
[een] :: ([=c1,+ee,c2]).
[] :: ([cnix]).
