startCategory(cFin(_)).
[makumi_maviri_nenhatu] :: [cFin].%[makumi_maviri_nenhatu] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[makumi_maviri_nenhatu] :: [c3].%[makumi_maviri_nenhatu] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot)]
[makumi_maviri_nenhanhatu] :: [cFin].%[makumi_maviri_nenhanhatu] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[makumi_maviri_nenhanhatu] :: [c3].%[makumi_maviri_nenhanhatu] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot)]
[makumi_maviri_nena] :: [cFin].%[makumi_maviri_nena] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[makumi_maviri_nena] :: [c3].%[makumi_maviri_nena] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot)]
[makumi_maviri_nembiri] :: [cFin].%[makumi_maviri_nembiri] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[makumi_maviri_nembiri] :: [c3].%[makumi_maviri_nembiri] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot)]
[makumi_maviri_neimwe] :: [cFin].%[makumi_maviri_neimwe] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[makumi_maviri_neimwe] :: [c3].%[makumi_maviri_neimwe] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot)]
[makumi_maviri] :: [cFin].%[makumi_maviri] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[makumi_maviri] :: [c3].%[makumi_maviri] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot)]
[makumi_mana_nenhatu] :: [cFin].%[makumi_mana_nenhatu] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[makumi_mana_nenhatu] :: [c3].%[makumi_mana_nenhatu] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot)]
[makumi_mana_nenhanhatu] :: [cFin].%[makumi_mana_nenhanhatu] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[makumi_mana_nenhanhatu] :: [c3].%[makumi_mana_nenhanhatu] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot)]
[makumi_mana_nena] :: [cFin].%[makumi_mana_nena] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[makumi_mana_nena] :: [c3].%[makumi_mana_nena] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot)]
[makumi_mana_nembiri] :: [cFin].%[makumi_mana_nembiri] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[makumi_mana_nembiri] :: [c3].%[makumi_mana_nembiri] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot)]
[makumi_mana_neimwe] :: [cFin].%[makumi_mana_neimwe] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[makumi_mana_neimwe] :: [c3].%[makumi_mana_neimwe] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot)]
[makumi_mana] :: [cFin].%[makumi_mana] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[makumi_mana] :: [c3].%[makumi_mana] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot)]
[gumi_nenhatu] :: [cFin].%[gumi_nenhatu] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[gumi_nenhatu] :: [c3].%[gumi_nenhatu] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot)]
[gumi_nenhanhatu] :: [cFin].%[gumi_nenhanhatu] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[gumi_nenhanhatu] :: [c3].%[gumi_nenhanhatu] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot)]
[gumi_nembiri] :: [cFin].%[gumi_nembiri] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[gumi_nembiri] :: [c3].%[gumi_nembiri] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot)]
[gumi_neina] :: [cFin].%[gumi_neina] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[gumi_neina] :: [c3].%[gumi_neina] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot)]
[gumi_neimwe] :: [cFin].%[gumi_neimwe] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[gumi_neimwe] :: [c3].%[gumi_neimwe] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot)]
[gumi] :: [cFin].%[gumi] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[gumi] :: [c3].%[gumi] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot)]
[china] :: [c2,-el].%[china] :: [c1], [epsLi([=c1,c2,-el],dot)]
[china] :: [c2,-cl].%[china] :: [c1], [epsLi([=c1,c2,-cl],dot)]
[china] :: [c3].%[china] :: [c1], [epsLi([=c1,c3],dot)]
[china] :: [c1].
[china] :: [cFin].%[china] :: [c1], [epsLi([=c1,c3],dot),epsLi([=c3,cFin],dot)]
[china] :: [c34scl].%[china] :: [c1], [epsLi([=c1,c2,-cl],dot),epsLi([=c2,+cl,c34scl],dot)]
[china] :: [c3cl].%[china] :: [c1], [epsLi([=c1,c2,-cl],dot),epsLi([=c2,+cl,c3cl],dot)]
[china] :: [c2].%[china] :: [c1], [epsLi([=c2,+el,c2],dot),epsLi([=c1,c2,-el],dot),epsLi([=c1,c2,-cl],dot),epsLi([=c2,+cl,c2],dot)]
[china] :: [c31sel].%[china] :: [c1], [epsLi([=c1,c2,-el],dot),epsLi([=c2,+el,c31sel],dot)]
[china] :: [c33sel].%[china] :: [c1], [epsLi([=c1,c2,-el],dot),epsLi([=c2,+el,c33sel],dot)]
[gumi] :: [c2,-cl].%[gumi] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot)]
[gumi] :: [c2,-cl,-el,-sl0].
[gumi] :: [c34scl].%[gumi] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot),epsLi([=c2,+cl,c34scl],dot)]
[gumi] :: [c3cl].%[gumi] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot),epsLi([=c2,+cl,c3cl],dot)]
[gumi] :: [c2].%[gumi] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+el,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot),epsLi([=c2,+cl,c2],dot)]
[gumi_ne] :: [=c25sal,c3].%[gumi_ne] :: [=c25sal,c2,-sl0], [epsLi([=c2,+sl0,c3],dot)]
[gumi_ne] :: [=c25sal,c2].%[gumi_ne] :: [=c25sal,c2,-sl0], [epsLi([=c2,+sl0,c2],dot)]
[gumi_ne] :: [=c25sal,c2,-sl0].
[gumi_ne] :: [=c25sal,cFin].%[gumi_ne] :: [=c25sal,c2,-sl0], [epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[gumi_neimwe] :: [c2,-cl].%[gumi_neimwe] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot)]
[gumi_neimwe] :: [c2,-cl,-el,-sl0].
[gumi_neimwe] :: [c34scl].%[gumi_neimwe] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot),epsLi([=c2,+cl,c34scl],dot)]
[gumi_neimwe] :: [c3cl].%[gumi_neimwe] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot),epsLi([=c2,+cl,c3cl],dot)]
[gumi_neimwe] :: [c2].%[gumi_neimwe] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+el,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot),epsLi([=c2,+cl,c2],dot)]
[gumi_neina] :: [c2,-cl].%[gumi_neina] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot)]
[gumi_neina] :: [c2,-cl,-el,-sl0].
[gumi_neina] :: [c34scl].%[gumi_neina] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot),epsLi([=c2,+cl,c34scl],dot)]
[gumi_neina] :: [c3cl].%[gumi_neina] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot),epsLi([=c2,+cl,c3cl],dot)]
[gumi_neina] :: [c2].%[gumi_neina] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+el,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot),epsLi([=c2,+cl,c2],dot)]
[gumi_nembiri] :: [c2,-cl].%[gumi_nembiri] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot)]
[gumi_nembiri] :: [c2,-cl,-el,-sl0].
[gumi_nembiri] :: [c34scl].%[gumi_nembiri] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot),epsLi([=c2,+cl,c34scl],dot)]
[gumi_nembiri] :: [c3cl].%[gumi_nembiri] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot),epsLi([=c2,+cl,c3cl],dot)]
[gumi_nembiri] :: [c2].%[gumi_nembiri] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+el,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot),epsLi([=c2,+cl,c2],dot)]
[gumi_nenhanhatu] :: [c2,-cl].%[gumi_nenhanhatu] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot)]
[gumi_nenhanhatu] :: [c2,-cl,-el,-sl0].
[gumi_nenhanhatu] :: [c34scl].%[gumi_nenhanhatu] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot),epsLi([=c2,+cl,c34scl],dot)]
[gumi_nenhanhatu] :: [c3cl].%[gumi_nenhanhatu] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot),epsLi([=c2,+cl,c3cl],dot)]
[gumi_nenhanhatu] :: [c2].%[gumi_nenhanhatu] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+el,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot),epsLi([=c2,+cl,c2],dot)]
[gumi_nenhatu] :: [c2,-cl].%[gumi_nenhatu] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot)]
[gumi_nenhatu] :: [c2,-cl,-el,-sl0].
[gumi_nenhatu] :: [c34scl].%[gumi_nenhatu] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot),epsLi([=c2,+cl,c34scl],dot)]
[gumi_nenhatu] :: [c3cl].%[gumi_nenhatu] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot),epsLi([=c2,+cl,c3cl],dot)]
[gumi_nenhatu] :: [c2].%[gumi_nenhatu] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+el,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot),epsLi([=c2,+cl,c2],dot)]
[ma] :: [=c31s,cFin].%[ma] :: [=c31s,c3], [epsLi([=c3,cFin],dot)]
[ma] :: [=c31s,c3].
[ma] :: [=c32s,cFin].%[ma] :: [=c32s,c3], [epsLi([=c3,cFin],dot)]
[ma] :: [=c32s,c3].
[ma] :: [=c33s,cFin].%[ma] :: [=c33s,c3], [epsLi([=c3,cFin],dot)]
[ma] :: [=c33s,c3].
[makumi_ma] :: [=c21s,c3].%[makumi_ma] :: [=c21s,c2,-sl0], [epsLi([=c2,+sl0,c3],dot)]
[makumi_ma] :: [=c21s,c2].%[makumi_ma] :: [=c21s,c2,-sl0], [epsLi([=c2,+sl0,c2],dot)]
[makumi_ma] :: [=c21s,c2,-sl0].
[makumi_ma] :: [=c21s,cFin].%[makumi_ma] :: [=c21s,c2,-sl0], [epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[makumi_ma] :: [=c22s,c3].%[makumi_ma] :: [=c22s,c2,-sl0], [epsLi([=c2,+sl0,c3],dot)]
[makumi_ma] :: [=c22s,c2].%[makumi_ma] :: [=c22s,c2,-sl0], [epsLi([=c2,+sl0,c2],dot)]
[makumi_ma] :: [=c22s,c2,-sl0].
[makumi_ma] :: [=c22s,cFin].%[makumi_ma] :: [=c22s,c2,-sl0], [epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[makumi_ma] :: [=c23s,c3].%[makumi_ma] :: [=c23s,c2,-sl0], [epsLi([=c2,+sl0,c3],dot)]
[makumi_ma] :: [=c23s,c2].%[makumi_ma] :: [=c23s,c2,-sl0], [epsLi([=c2,+sl0,c2],dot)]
[makumi_ma] :: [=c23s,c2,-sl0].
[makumi_ma] :: [=c23s,cFin].%[makumi_ma] :: [=c23s,c2,-sl0], [epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[makumi_ma] :: [=c24s,c3].%[makumi_ma] :: [=c24s,c2,-sl0], [epsLi([=c2,+sl0,c3],dot)]
[makumi_ma] :: [=c24s,c2].%[makumi_ma] :: [=c24s,c2,-sl0], [epsLi([=c2,+sl0,c2],dot)]
[makumi_ma] :: [=c24s,c2,-sl0].
[makumi_ma] :: [=c24s,cFin].%[makumi_ma] :: [=c24s,c2,-sl0], [epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[makumi_ma] :: [=c25s,c3].%[makumi_ma] :: [=c25s,c2,-sl0], [epsLi([=c2,+sl0,c3],dot)]
[makumi_ma] :: [=c25s,c2].%[makumi_ma] :: [=c25s,c2,-sl0], [epsLi([=c2,+sl0,c2],dot)]
[makumi_ma] :: [=c25s,c2,-sl0].
[makumi_ma] :: [=c25s,cFin].%[makumi_ma] :: [=c25s,c2,-sl0], [epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[makumi_ma] :: [=c25sbl,c3].%[makumi_ma] :: [=c25sbl,c2,-sl0], [epsLi([=c2,+sl0,c3],dot)]
[makumi_ma] :: [=c25sbl,c2].%[makumi_ma] :: [=c25sbl,c2,-sl0], [epsLi([=c2,+sl0,c2],dot)]
[makumi_ma] :: [=c25sbl,c2,-sl0].
[makumi_ma] :: [=c25sbl,cFin].%[makumi_ma] :: [=c25sbl,c2,-sl0], [epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[makumi_ma] :: [=c26s,c3].%[makumi_ma] :: [=c26s,c2,-sl0], [epsLi([=c2,+sl0,c3],dot)]
[makumi_ma] :: [=c26s,c2].%[makumi_ma] :: [=c26s,c2,-sl0], [epsLi([=c2,+sl0,c2],dot)]
[makumi_ma] :: [=c26s,c2,-sl0].
[makumi_ma] :: [=c26s,cFin].%[makumi_ma] :: [=c26s,c2,-sl0], [epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[makumi_mana] :: [c2,-cl].%[makumi_mana] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot)]
[makumi_mana] :: [c2,-cl,-el,-sl0].
[makumi_mana] :: [c34scl].%[makumi_mana] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot),epsLi([=c2,+cl,c34scl],dot)]
[makumi_mana] :: [c3cl].%[makumi_mana] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot),epsLi([=c2,+cl,c3cl],dot)]
[makumi_mana] :: [c2].%[makumi_mana] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+el,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot),epsLi([=c2,+cl,c2],dot)]
[makumi_mana_ne] :: [=c25sal,c3].%[makumi_mana_ne] :: [=c25sal,c2,-sl0], [epsLi([=c2,+sl0,c3],dot)]
[makumi_mana_ne] :: [=c25sal,c2].%[makumi_mana_ne] :: [=c25sal,c2,-sl0], [epsLi([=c2,+sl0,c2],dot)]
[makumi_mana_ne] :: [=c25sal,c2,-sl0].
[makumi_mana_ne] :: [=c25sal,cFin].%[makumi_mana_ne] :: [=c25sal,c2,-sl0], [epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[makumi_mana_neimwe] :: [c2,-cl].%[makumi_mana_neimwe] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot)]
[makumi_mana_neimwe] :: [c2,-cl,-el,-sl0].
[makumi_mana_neimwe] :: [c34scl].%[makumi_mana_neimwe] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot),epsLi([=c2,+cl,c34scl],dot)]
[makumi_mana_neimwe] :: [c3cl].%[makumi_mana_neimwe] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot),epsLi([=c2,+cl,c3cl],dot)]
[makumi_mana_neimwe] :: [c2].%[makumi_mana_neimwe] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+el,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot),epsLi([=c2,+cl,c2],dot)]
[makumi_mana_nembiri] :: [c2,-cl].%[makumi_mana_nembiri] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot)]
[makumi_mana_nembiri] :: [c2,-cl,-el,-sl0].
[makumi_mana_nembiri] :: [c34scl].%[makumi_mana_nembiri] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot),epsLi([=c2,+cl,c34scl],dot)]
[makumi_mana_nembiri] :: [c3cl].%[makumi_mana_nembiri] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot),epsLi([=c2,+cl,c3cl],dot)]
[makumi_mana_nembiri] :: [c2].%[makumi_mana_nembiri] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+el,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot),epsLi([=c2,+cl,c2],dot)]
[makumi_mana_nena] :: [c2,-cl].%[makumi_mana_nena] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot)]
[makumi_mana_nena] :: [c2,-cl,-el,-sl0].
[makumi_mana_nena] :: [c34scl].%[makumi_mana_nena] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot),epsLi([=c2,+cl,c34scl],dot)]
[makumi_mana_nena] :: [c3cl].%[makumi_mana_nena] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot),epsLi([=c2,+cl,c3cl],dot)]
[makumi_mana_nena] :: [c2].%[makumi_mana_nena] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+el,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot),epsLi([=c2,+cl,c2],dot)]
[makumi_mana_nenhanhatu] :: [c2,-cl].%[makumi_mana_nenhanhatu] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot)]
[makumi_mana_nenhanhatu] :: [c2,-cl,-el,-sl0].
[makumi_mana_nenhanhatu] :: [c34scl].%[makumi_mana_nenhanhatu] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot),epsLi([=c2,+cl,c34scl],dot)]
[makumi_mana_nenhanhatu] :: [c3cl].%[makumi_mana_nenhanhatu] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot),epsLi([=c2,+cl,c3cl],dot)]
[makumi_mana_nenhanhatu] :: [c2].%[makumi_mana_nenhanhatu] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+el,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot),epsLi([=c2,+cl,c2],dot)]
[makumi_mana_nenhatu] :: [c2,-cl].%[makumi_mana_nenhatu] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot)]
[makumi_mana_nenhatu] :: [c2,-cl,-el,-sl0].
[makumi_mana_nenhatu] :: [c34scl].%[makumi_mana_nenhatu] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot),epsLi([=c2,+cl,c34scl],dot)]
[makumi_mana_nenhatu] :: [c3cl].%[makumi_mana_nenhatu] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot),epsLi([=c2,+cl,c3cl],dot)]
[makumi_mana_nenhatu] :: [c2].%[makumi_mana_nenhatu] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+el,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot),epsLi([=c2,+cl,c2],dot)]
[makumi_maviri] :: [c2,-cl].%[makumi_maviri] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot)]
[makumi_maviri] :: [c2,-cl,-el,-sl0].
[makumi_maviri] :: [c34scl].%[makumi_maviri] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot),epsLi([=c2,+cl,c34scl],dot)]
[makumi_maviri] :: [c3cl].%[makumi_maviri] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot),epsLi([=c2,+cl,c3cl],dot)]
[makumi_maviri] :: [c2].%[makumi_maviri] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+el,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot),epsLi([=c2,+cl,c2],dot)]
[makumi_maviri_ne] :: [=c25sal,c3].%[makumi_maviri_ne] :: [=c25sal,c2,-sl0], [epsLi([=c2,+sl0,c3],dot)]
[makumi_maviri_ne] :: [=c25sal,c2].%[makumi_maviri_ne] :: [=c25sal,c2,-sl0], [epsLi([=c2,+sl0,c2],dot)]
[makumi_maviri_ne] :: [=c25sal,c2,-sl0].
[makumi_maviri_ne] :: [=c25sal,cFin].%[makumi_maviri_ne] :: [=c25sal,c2,-sl0], [epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[makumi_maviri_neimwe] :: [c2,-cl].%[makumi_maviri_neimwe] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot)]
[makumi_maviri_neimwe] :: [c2,-cl,-el,-sl0].
[makumi_maviri_neimwe] :: [c34scl].%[makumi_maviri_neimwe] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot),epsLi([=c2,+cl,c34scl],dot)]
[makumi_maviri_neimwe] :: [c3cl].%[makumi_maviri_neimwe] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot),epsLi([=c2,+cl,c3cl],dot)]
[makumi_maviri_neimwe] :: [c2].%[makumi_maviri_neimwe] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+el,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot),epsLi([=c2,+cl,c2],dot)]
[makumi_maviri_nembiri] :: [c2,-cl].%[makumi_maviri_nembiri] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot)]
[makumi_maviri_nembiri] :: [c2,-cl,-el,-sl0].
[makumi_maviri_nembiri] :: [c34scl].%[makumi_maviri_nembiri] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot),epsLi([=c2,+cl,c34scl],dot)]
[makumi_maviri_nembiri] :: [c3cl].%[makumi_maviri_nembiri] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot),epsLi([=c2,+cl,c3cl],dot)]
[makumi_maviri_nembiri] :: [c2].%[makumi_maviri_nembiri] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+el,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot),epsLi([=c2,+cl,c2],dot)]
[makumi_maviri_nena] :: [c2,-cl].%[makumi_maviri_nena] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot)]
[makumi_maviri_nena] :: [c2,-cl,-el,-sl0].
[makumi_maviri_nena] :: [c34scl].%[makumi_maviri_nena] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot),epsLi([=c2,+cl,c34scl],dot)]
[makumi_maviri_nena] :: [c3cl].%[makumi_maviri_nena] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot),epsLi([=c2,+cl,c3cl],dot)]
[makumi_maviri_nena] :: [c2].%[makumi_maviri_nena] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+el,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot),epsLi([=c2,+cl,c2],dot)]
[makumi_maviri_nenhanhatu] :: [c2,-cl].%[makumi_maviri_nenhanhatu] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot)]
[makumi_maviri_nenhanhatu] :: [c2,-cl,-el,-sl0].
[makumi_maviri_nenhanhatu] :: [c34scl].%[makumi_maviri_nenhanhatu] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot),epsLi([=c2,+cl,c34scl],dot)]
[makumi_maviri_nenhanhatu] :: [c3cl].%[makumi_maviri_nenhanhatu] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot),epsLi([=c2,+cl,c3cl],dot)]
[makumi_maviri_nenhanhatu] :: [c2].%[makumi_maviri_nenhanhatu] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+el,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot),epsLi([=c2,+cl,c2],dot)]
[makumi_maviri_nenhatu] :: [c2,-cl].%[makumi_maviri_nenhatu] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot)]
[makumi_maviri_nenhatu] :: [c2,-cl,-el,-sl0].
[makumi_maviri_nenhatu] :: [c34scl].%[makumi_maviri_nenhatu] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot),epsLi([=c2,+cl,c34scl],dot)]
[makumi_maviri_nenhatu] :: [c3cl].%[makumi_maviri_nenhatu] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot),epsLi([=c2,+cl,c3cl],dot)]
[makumi_maviri_nenhatu] :: [c2].%[makumi_maviri_nenhatu] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+el,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+cl,+el,+sl0,c2,-cl],dot),epsLi([=c2,+cl,c2],dot)]
[mana] :: [=c2,+dl,c32s].
[mana_ne] :: [=c33sel,=c33sdl,c33s].
[maviri_ne] :: [=c33sel,=c33sdl,c31s].
[mazana_ma] :: [=c25sbl,cFin].%[mazana_ma] :: [=c25sbl,c3], [epsLi([=c3,cFin],dot)]
[mazana_ma] :: [=c25sbl,c3].
[mazana_ma] :: [=c34s,cFin].%[mazana_ma] :: [=c34s,c3], [epsLi([=c3,cFin],dot)]
[mazana_ma] :: [=c34s,c3].
[mazana_maviri] :: [cFin].%[mazana_maviri] :: [c3], [epsLi([=c3,cFin],dot)]
[mazana_maviri] :: [c3].
[motsi] :: [c2,-el].%[motsi] :: [c1], [epsLi([=c1,c2,-el],dot)]
[motsi] :: [c2,-cl].%[motsi] :: [c1], [epsLi([=c1,c2,-cl],dot)]
[motsi] :: [c3].%[motsi] :: [c1], [epsLi([=c1,c3],dot)]
[motsi] :: [c1].
[motsi] :: [cFin].%[motsi] :: [c1], [epsLi([=c1,c3],dot),epsLi([=c3,cFin],dot)]
[motsi] :: [c34scl].%[motsi] :: [c1], [epsLi([=c1,c2,-cl],dot),epsLi([=c2,+cl,c34scl],dot)]
[motsi] :: [c3cl].%[motsi] :: [c1], [epsLi([=c1,c2,-cl],dot),epsLi([=c2,+cl,c3cl],dot)]
[motsi] :: [c2].%[motsi] :: [c1], [epsLi([=c2,+el,c2],dot),epsLi([=c1,c2,-el],dot),epsLi([=c1,c2,-cl],dot),epsLi([=c2,+cl,c2],dot)]
[motsi] :: [c31sel].%[motsi] :: [c1], [epsLi([=c1,c2,-el],dot),epsLi([=c2,+el,c31sel],dot)]
[motsi] :: [c33sel].%[motsi] :: [c1], [epsLi([=c1,c2,-el],dot),epsLi([=c2,+el,c33sel],dot)]
[ne] :: [=c25sal,=c25sbl,c25s].
[ne] :: [=c34scl,=c25sbl,c34s].
[neimwe] :: [=c1,+bl,c21s].
[nembiri] :: [=c1,+bl,c22s].
[nena] :: [=c1,+bl,c24s].
[nenhanhatu] :: [=c1,+bl,c26s].
[nenhatu] :: [=c1,+bl,c23s].
[nomwe] :: [c1,-bl].%[nomwe] :: [c1,-bl,-al], [epsLi([=c1,+bl,+al,c1,-bl],dot)]
[nomwe] :: [c1,-bl,-al].
[nomwe] :: [c34sbl].%[nomwe] :: [c1,-bl,-al], [epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+bl,c34sbl],dot)]
[nomwe] :: [c25sbl].%[nomwe] :: [c1,-bl,-al], [epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+bl,c25sbl],dot)]
[nomwe] :: [c2bl].%[nomwe] :: [c1,-bl,-al], [epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+bl,c2bl],dot)]
[nomwe] :: [c3bl].%[nomwe] :: [c1,-bl,-al], [epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+bl,c3bl],dot)]
[nomwe] :: [c1].%[nomwe] :: [c1,-bl,-al], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+bl,c1],dot)]
[nomwe] :: [c2,-el].%[nomwe] :: [c1,-bl,-al], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-el],dot)]
[nomwe] :: [c2,-cl].%[nomwe] :: [c1,-bl,-al], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-cl],dot)]
[nomwe] :: [c3].%[nomwe] :: [c1,-bl,-al], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c3],dot)]
[nomwe] :: [cFin].%[nomwe] :: [c1,-bl,-al], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c3],dot),epsLi([=c3,cFin],dot)]
[nomwe] :: [c34scl].%[nomwe] :: [c1,-bl,-al], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-cl],dot),epsLi([=c2,+cl,c34scl],dot)]
[nomwe] :: [c3cl].%[nomwe] :: [c1,-bl,-al], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-cl],dot),epsLi([=c2,+cl,c3cl],dot)]
[nomwe] :: [c2].%[nomwe] :: [c1,-bl,-al], [epsLi([=c2,+el,c2],dot),epsLi([=c1,c2,-el],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-cl],dot),epsLi([=c2,+cl,c2],dot)]
[nomwe] :: [c31sel].%[nomwe] :: [c1,-bl,-al], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-el],dot),epsLi([=c2,+el,c31sel],dot)]
[nomwe] :: [c33sel].%[nomwe] :: [c1,-bl,-al], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-el],dot),epsLi([=c2,+el,c33sel],dot)]
[pfumbamwe] :: [c1,-bl].%[pfumbamwe] :: [c1,-bl,-al], [epsLi([=c1,+bl,+al,c1,-bl],dot)]
[pfumbamwe] :: [c1,-bl,-al].
[pfumbamwe] :: [c34sbl].%[pfumbamwe] :: [c1,-bl,-al], [epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+bl,c34sbl],dot)]
[pfumbamwe] :: [c25sbl].%[pfumbamwe] :: [c1,-bl,-al], [epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+bl,c25sbl],dot)]
[pfumbamwe] :: [c2bl].%[pfumbamwe] :: [c1,-bl,-al], [epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+bl,c2bl],dot)]
[pfumbamwe] :: [c3bl].%[pfumbamwe] :: [c1,-bl,-al], [epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+bl,c3bl],dot)]
[pfumbamwe] :: [c1].%[pfumbamwe] :: [c1,-bl,-al], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+bl,c1],dot)]
[pfumbamwe] :: [c2,-el].%[pfumbamwe] :: [c1,-bl,-al], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-el],dot)]
[pfumbamwe] :: [c2,-cl].%[pfumbamwe] :: [c1,-bl,-al], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-cl],dot)]
[pfumbamwe] :: [c3].%[pfumbamwe] :: [c1,-bl,-al], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c3],dot)]
[pfumbamwe] :: [cFin].%[pfumbamwe] :: [c1,-bl,-al], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c3],dot),epsLi([=c3,cFin],dot)]
[pfumbamwe] :: [c34scl].%[pfumbamwe] :: [c1,-bl,-al], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-cl],dot),epsLi([=c2,+cl,c34scl],dot)]
[pfumbamwe] :: [c3cl].%[pfumbamwe] :: [c1,-bl,-al], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-cl],dot),epsLi([=c2,+cl,c3cl],dot)]
[pfumbamwe] :: [c2].%[pfumbamwe] :: [c1,-bl,-al], [epsLi([=c2,+el,c2],dot),epsLi([=c1,c2,-el],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-cl],dot),epsLi([=c2,+cl,c2],dot)]
[pfumbamwe] :: [c31sel].%[pfumbamwe] :: [c1,-bl,-al], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-el],dot),epsLi([=c2,+el,c31sel],dot)]
[pfumbamwe] :: [c33sel].%[pfumbamwe] :: [c1,-bl,-al], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-el],dot),epsLi([=c2,+el,c33sel],dot)]
[piri] :: [c2,-el].%[piri] :: [c1], [epsLi([=c1,c2,-el],dot)]
[piri] :: [c2,-cl].%[piri] :: [c1], [epsLi([=c1,c2,-cl],dot)]
[piri] :: [c3].%[piri] :: [c1], [epsLi([=c1,c3],dot)]
[piri] :: [c1].
[piri] :: [cFin].%[piri] :: [c1], [epsLi([=c1,c3],dot),epsLi([=c3,cFin],dot)]
[piri] :: [c34scl].%[piri] :: [c1], [epsLi([=c1,c2,-cl],dot),epsLi([=c2,+cl,c34scl],dot)]
[piri] :: [c3cl].%[piri] :: [c1], [epsLi([=c1,c2,-cl],dot),epsLi([=c2,+cl,c3cl],dot)]
[piri] :: [c2].%[piri] :: [c1], [epsLi([=c2,+el,c2],dot),epsLi([=c1,c2,-el],dot),epsLi([=c1,c2,-cl],dot),epsLi([=c2,+cl,c2],dot)]
[piri] :: [c31sel].%[piri] :: [c1], [epsLi([=c1,c2,-el],dot),epsLi([=c2,+el,c31sel],dot)]
[piri] :: [c33sel].%[piri] :: [c1], [epsLi([=c1,c2,-el],dot),epsLi([=c2,+el,c33sel],dot)]
[sere] :: [c1,-bl].%[sere] :: [c1,-bl,-al], [epsLi([=c1,+bl,+al,c1,-bl],dot)]
[sere] :: [c1,-bl,-al].
[sere] :: [c34sbl].%[sere] :: [c1,-bl,-al], [epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+bl,c34sbl],dot)]
[sere] :: [c25sbl].%[sere] :: [c1,-bl,-al], [epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+bl,c25sbl],dot)]
[sere] :: [c2bl].%[sere] :: [c1,-bl,-al], [epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+bl,c2bl],dot)]
[sere] :: [c3bl].%[sere] :: [c1,-bl,-al], [epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+bl,c3bl],dot)]
[sere] :: [c1].%[sere] :: [c1,-bl,-al], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+bl,c1],dot)]
[sere] :: [c2,-el].%[sere] :: [c1,-bl,-al], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-el],dot)]
[sere] :: [c2,-cl].%[sere] :: [c1,-bl,-al], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-cl],dot)]
[sere] :: [c3].%[sere] :: [c1,-bl,-al], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c3],dot)]
[sere] :: [cFin].%[sere] :: [c1,-bl,-al], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c3],dot),epsLi([=c3,cFin],dot)]
[sere] :: [c34scl].%[sere] :: [c1,-bl,-al], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-cl],dot),epsLi([=c2,+cl,c34scl],dot)]
[sere] :: [c3cl].%[sere] :: [c1,-bl,-al], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-cl],dot),epsLi([=c2,+cl,c3cl],dot)]
[sere] :: [c2].%[sere] :: [c1,-bl,-al], [epsLi([=c2,+el,c2],dot),epsLi([=c1,c2,-el],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-cl],dot),epsLi([=c2,+cl,c2],dot)]
[sere] :: [c31sel].%[sere] :: [c1,-bl,-al], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-el],dot),epsLi([=c2,+el,c31sel],dot)]
[sere] :: [c33sel].%[sere] :: [c1,-bl,-al], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-el],dot),epsLi([=c2,+el,c33sel],dot)]
[shanu] :: [c1,-bl].%[shanu] :: [c1,-bl,-al], [epsLi([=c1,+bl,+al,c1,-bl],dot)]
[shanu] :: [c1,-bl,-al].
[shanu] :: [c34sbl].%[shanu] :: [c1,-bl,-al], [epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+bl,c34sbl],dot)]
[shanu] :: [c25sbl].%[shanu] :: [c1,-bl,-al], [epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+bl,c25sbl],dot)]
[shanu] :: [c2bl].%[shanu] :: [c1,-bl,-al], [epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+bl,c2bl],dot)]
[shanu] :: [c3bl].%[shanu] :: [c1,-bl,-al], [epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+bl,c3bl],dot)]
[shanu] :: [c1].%[shanu] :: [c1,-bl,-al], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+bl,c1],dot)]
[shanu] :: [c2,-el].%[shanu] :: [c1,-bl,-al], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-el],dot)]
[shanu] :: [c2,-cl].%[shanu] :: [c1,-bl,-al], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-cl],dot)]
[shanu] :: [c3].%[shanu] :: [c1,-bl,-al], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c3],dot)]
[shanu] :: [cFin].%[shanu] :: [c1,-bl,-al], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c3],dot),epsLi([=c3,cFin],dot)]
[shanu] :: [c34scl].%[shanu] :: [c1,-bl,-al], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-cl],dot),epsLi([=c2,+cl,c34scl],dot)]
[shanu] :: [c3cl].%[shanu] :: [c1,-bl,-al], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-cl],dot),epsLi([=c2,+cl,c3cl],dot)]
[shanu] :: [c2].%[shanu] :: [c1,-bl,-al], [epsLi([=c2,+el,c2],dot),epsLi([=c1,c2,-el],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-cl],dot),epsLi([=c2,+cl,c2],dot)]
[shanu] :: [c31sel].%[shanu] :: [c1,-bl,-al], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-el],dot),epsLi([=c2,+el,c31sel],dot)]
[shanu] :: [c33sel].%[shanu] :: [c1,-bl,-al], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-el],dot),epsLi([=c2,+el,c33sel],dot)]
[tanhatu] :: [c34sbl].%[tanhatu] :: [c1,-bl], [epsLi([=c1,+bl,c34sbl],dot)]
[tanhatu] :: [c25sbl].%[tanhatu] :: [c1,-bl], [epsLi([=c1,+bl,c25sbl],dot)]
[tanhatu] :: [c2bl].%[tanhatu] :: [c1,-bl], [epsLi([=c1,+bl,c2bl],dot)]
[tanhatu] :: [c3bl].%[tanhatu] :: [c1,-bl], [epsLi([=c1,+bl,c3bl],dot)]
[tanhatu] :: [c1].%[tanhatu] :: [c1,-bl], [epsLi([=c1,+bl,c1],dot)]
[tanhatu] :: [c1,-bl].
[tanhatu] :: [c2,-el].%[tanhatu] :: [c1,-bl], [epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-el],dot)]
[tanhatu] :: [c2,-cl].%[tanhatu] :: [c1,-bl], [epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-cl],dot)]
[tanhatu] :: [c3].%[tanhatu] :: [c1,-bl], [epsLi([=c1,+bl,c1],dot),epsLi([=c1,c3],dot)]
[tanhatu] :: [c31sel].%[tanhatu] :: [c1,-bl], [epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-el],dot),epsLi([=c2,+el,c31sel],dot)]
[tanhatu] :: [c33sel].%[tanhatu] :: [c1,-bl], [epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-el],dot),epsLi([=c2,+el,c33sel],dot)]
[tanhatu] :: [c2].%[tanhatu] :: [c1,-bl], [epsLi([=c2,+cl,c2],dot),epsLi([=c1,c2,-cl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-el],dot),epsLi([=c2,+el,c2],dot)]
[tanhatu] :: [c34scl].%[tanhatu] :: [c1,-bl], [epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-cl],dot),epsLi([=c2,+cl,c34scl],dot)]
[tanhatu] :: [c3cl].%[tanhatu] :: [c1,-bl], [epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-cl],dot),epsLi([=c2,+cl,c3cl],dot)]
[tanhatu] :: [cFin].%[tanhatu] :: [c1,-bl], [epsLi([=c1,+bl,c1],dot),epsLi([=c1,c3],dot),epsLi([=c3,cFin],dot)]
[tatu] :: [c34sbl].%[tatu] :: [c1,-bl], [epsLi([=c1,+bl,c34sbl],dot)]
[tatu] :: [c25sbl].%[tatu] :: [c1,-bl], [epsLi([=c1,+bl,c25sbl],dot)]
[tatu] :: [c2bl].%[tatu] :: [c1,-bl], [epsLi([=c1,+bl,c2bl],dot)]
[tatu] :: [c3bl].%[tatu] :: [c1,-bl], [epsLi([=c1,+bl,c3bl],dot)]
[tatu] :: [c1].%[tatu] :: [c1,-bl], [epsLi([=c1,+bl,c1],dot)]
[tatu] :: [c1,-bl].
[tatu] :: [c2,-el].%[tatu] :: [c1,-bl], [epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-el],dot)]
[tatu] :: [c2,-cl].%[tatu] :: [c1,-bl], [epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-cl],dot)]
[tatu] :: [c3].%[tatu] :: [c1,-bl], [epsLi([=c1,+bl,c1],dot),epsLi([=c1,c3],dot)]
[tatu] :: [c31sel].%[tatu] :: [c1,-bl], [epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-el],dot),epsLi([=c2,+el,c31sel],dot)]
[tatu] :: [c33sel].%[tatu] :: [c1,-bl], [epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-el],dot),epsLi([=c2,+el,c33sel],dot)]
[tatu] :: [c2].%[tatu] :: [c1,-bl], [epsLi([=c2,+cl,c2],dot),epsLi([=c1,c2,-cl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-el],dot),epsLi([=c2,+el,c2],dot)]
[tatu] :: [c34scl].%[tatu] :: [c1,-bl], [epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-cl],dot),epsLi([=c2,+cl,c34scl],dot)]
[tatu] :: [c3cl].%[tatu] :: [c1,-bl], [epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-cl],dot),epsLi([=c2,+cl,c3cl],dot)]
[tatu] :: [cFin].%[tatu] :: [c1,-bl], [epsLi([=c1,+bl,c1],dot),epsLi([=c1,c3],dot),epsLi([=c3,cFin],dot)]
[zana] :: [c2,-dl].%[zana] :: [c2,-dl,-sl0], [epsLi([=c2,+dl,+sl0,c2,-dl],dot)]
[zana] :: [c2,-dl,-sl0].
[zana] :: [c2].%[zana] :: [c2,-dl,-sl0], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+dl,+sl0,c2,-dl],dot),epsLi([=c2,+dl,c2],dot)]
[zana] :: [c31sdl].%[zana] :: [c2,-dl,-sl0], [epsLi([=c2,+dl,+sl0,c2,-dl],dot),epsLi([=c2,+dl,c31sdl],dot)]
[zana] :: [c33sdl].%[zana] :: [c2,-dl,-sl0], [epsLi([=c2,+dl,+sl0,c2,-dl],dot),epsLi([=c2,+dl,c33sdl],dot)]
[zana_ne] :: [=c34scl,cFin].%[zana_ne] :: [=c34scl,c3], [epsLi([=c3,cFin],dot)]
[zana_ne] :: [=c34scl,c3].
[gumi] :: [c31sel].%[gumi] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c31sel],dot)]
[gumi] :: [c33sel].%[gumi] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c33sel],dot)]
[gumi] :: [c2,-el].%[gumi] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot)]
[gumi_neimwe] :: [c31sel].%[gumi_neimwe] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c31sel],dot)]
[gumi_neimwe] :: [c33sel].%[gumi_neimwe] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c33sel],dot)]
[gumi_neimwe] :: [c2,-el].%[gumi_neimwe] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot)]
[gumi_neina] :: [c31sel].%[gumi_neina] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c31sel],dot)]
[gumi_neina] :: [c33sel].%[gumi_neina] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c33sel],dot)]
[gumi_neina] :: [c2,-el].%[gumi_neina] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot)]
[gumi_nembiri] :: [c31sel].%[gumi_nembiri] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c31sel],dot)]
[gumi_nembiri] :: [c33sel].%[gumi_nembiri] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c33sel],dot)]
[gumi_nembiri] :: [c2,-el].%[gumi_nembiri] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot)]
[gumi_nenhanhatu] :: [c31sel].%[gumi_nenhanhatu] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c31sel],dot)]
[gumi_nenhanhatu] :: [c33sel].%[gumi_nenhanhatu] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c33sel],dot)]
[gumi_nenhanhatu] :: [c2,-el].%[gumi_nenhanhatu] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot)]
[gumi_nenhatu] :: [c31sel].%[gumi_nenhatu] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c31sel],dot)]
[gumi_nenhatu] :: [c33sel].%[gumi_nenhatu] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c33sel],dot)]
[gumi_nenhatu] :: [c2,-el].%[gumi_nenhatu] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot)]
[makumi_mana] :: [c31sel].%[makumi_mana] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c31sel],dot)]
[makumi_mana] :: [c33sel].%[makumi_mana] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c33sel],dot)]
[makumi_mana] :: [c2,-el].%[makumi_mana] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot)]
[makumi_mana_neimwe] :: [c31sel].%[makumi_mana_neimwe] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c31sel],dot)]
[makumi_mana_neimwe] :: [c33sel].%[makumi_mana_neimwe] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c33sel],dot)]
[makumi_mana_neimwe] :: [c2,-el].%[makumi_mana_neimwe] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot)]
[makumi_mana_nembiri] :: [c31sel].%[makumi_mana_nembiri] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c31sel],dot)]
[makumi_mana_nembiri] :: [c33sel].%[makumi_mana_nembiri] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c33sel],dot)]
[makumi_mana_nembiri] :: [c2,-el].%[makumi_mana_nembiri] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot)]
[makumi_mana_nena] :: [c31sel].%[makumi_mana_nena] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c31sel],dot)]
[makumi_mana_nena] :: [c33sel].%[makumi_mana_nena] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c33sel],dot)]
[makumi_mana_nena] :: [c2,-el].%[makumi_mana_nena] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot)]
[makumi_mana_nenhanhatu] :: [c31sel].%[makumi_mana_nenhanhatu] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c31sel],dot)]
[makumi_mana_nenhanhatu] :: [c33sel].%[makumi_mana_nenhanhatu] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c33sel],dot)]
[makumi_mana_nenhanhatu] :: [c2,-el].%[makumi_mana_nenhanhatu] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot)]
[makumi_mana_nenhatu] :: [c31sel].%[makumi_mana_nenhatu] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c31sel],dot)]
[makumi_mana_nenhatu] :: [c33sel].%[makumi_mana_nenhatu] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c33sel],dot)]
[makumi_mana_nenhatu] :: [c2,-el].%[makumi_mana_nenhatu] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot)]
[makumi_maviri] :: [c31sel].%[makumi_maviri] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c31sel],dot)]
[makumi_maviri] :: [c33sel].%[makumi_maviri] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c33sel],dot)]
[makumi_maviri] :: [c2,-el].%[makumi_maviri] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot)]
[makumi_maviri_neimwe] :: [c31sel].%[makumi_maviri_neimwe] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c31sel],dot)]
[makumi_maviri_neimwe] :: [c33sel].%[makumi_maviri_neimwe] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c33sel],dot)]
[makumi_maviri_neimwe] :: [c2,-el].%[makumi_maviri_neimwe] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot)]
[makumi_maviri_nembiri] :: [c31sel].%[makumi_maviri_nembiri] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c31sel],dot)]
[makumi_maviri_nembiri] :: [c33sel].%[makumi_maviri_nembiri] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c33sel],dot)]
[makumi_maviri_nembiri] :: [c2,-el].%[makumi_maviri_nembiri] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot)]
[makumi_maviri_nena] :: [c31sel].%[makumi_maviri_nena] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c31sel],dot)]
[makumi_maviri_nena] :: [c33sel].%[makumi_maviri_nena] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c33sel],dot)]
[makumi_maviri_nena] :: [c2,-el].%[makumi_maviri_nena] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot)]
[makumi_maviri_nenhanhatu] :: [c31sel].%[makumi_maviri_nenhanhatu] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c31sel],dot)]
[makumi_maviri_nenhanhatu] :: [c33sel].%[makumi_maviri_nenhanhatu] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c33sel],dot)]
[makumi_maviri_nenhanhatu] :: [c2,-el].%[makumi_maviri_nenhanhatu] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot)]
[makumi_maviri_nenhatu] :: [c31sel].%[makumi_maviri_nenhatu] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c31sel],dot)]
[makumi_maviri_nenhatu] :: [c33sel].%[makumi_maviri_nenhatu] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c33sel],dot)]
[makumi_maviri_nenhatu] :: [c2,-el].%[makumi_maviri_nenhatu] :: [c2,-cl,-el,-sl0], [epsLi([=c2,+cl,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot)]
[nomwe] :: [c25sal].%[nomwe] :: [c1,-bl,-al], [epsLi([=c1,+bl,c1],dot),epsLi([=c1,+al,c25sal],dot)]
[nomwe] :: [c2al].%[nomwe] :: [c1,-bl,-al], [epsLi([=c1,+bl,c1],dot),epsLi([=c1,+al,c2al],dot)]
[pfumbamwe] :: [c25sal].%[pfumbamwe] :: [c1,-bl,-al], [epsLi([=c1,+bl,c1],dot),epsLi([=c1,+al,c25sal],dot)]
[pfumbamwe] :: [c2al].%[pfumbamwe] :: [c1,-bl,-al], [epsLi([=c1,+bl,c1],dot),epsLi([=c1,+al,c2al],dot)]
[sere] :: [c25sal].%[sere] :: [c1,-bl,-al], [epsLi([=c1,+bl,c1],dot),epsLi([=c1,+al,c25sal],dot)]
[sere] :: [c2al].%[sere] :: [c1,-bl,-al], [epsLi([=c1,+bl,c1],dot),epsLi([=c1,+al,c2al],dot)]
[shanu] :: [c25sal].%[shanu] :: [c1,-bl,-al], [epsLi([=c1,+bl,c1],dot),epsLi([=c1,+al,c25sal],dot)]
[shanu] :: [c2al].%[shanu] :: [c1,-bl,-al], [epsLi([=c1,+bl,c1],dot),epsLi([=c1,+al,c2al],dot)]
[zana] :: [cFin].%[zana] :: [c2,-dl,-sl0], [epsLi([=c2,+dl,c2],dot),epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[zana] :: [c3].%[zana] :: [c2,-dl,-sl0], [epsLi([=c2,+dl,c2],dot),epsLi([=c2,+sl0,c3],dot)]
