startCategory(cfin).
[] :: ([=c1, cfin]).
[n-daam] :: ([c1]).
[n-yi] :: ([c1]).
[n-ta] :: ([c1]).
[n-nahi] :: ([c1]).
[n-nu] :: ([c1]).
[n-yobu] :: ([c1]).
[m-pɔi] :: ([c1]).
[n-nii] :: ([c1]).
[n-wei] :: ([c1]).
[pia] :: ([c1]).
[pia_ni_yini] :: ([c1]).
[pia_ni_ayi] :: ([c1]).
[pia_ni_ata] :: ([c1]).
[pia_ni_anahi] :: ([c1]).
[pia_ni_anu] :: ([c1]).
[pia_ni_ayobu] :: ([c1]).
[pia_ni_apɔi] :: ([c1]).
[pishi_ayi_ka] :: ([c1]).
[pishi_yini_ka] :: ([c1]).
[pishi] :: ([c1]).
[pishi_ni_yini] :: ([c1]).
[pishi_ni_yi] :: ([c1]).
[pishi_ni_ata] :: ([c1]).
[pishi_ni_anahi] :: ([c1]).
[pishi_ni_anu] :: ([c1]).
[pishi_ni_ayobu] :: ([c1]).
[pishi_ni_apɔi] :: ([c1]).
[pihita_ayi_ka] :: ([c1]).
[pihita_yini_ka] :: ([c1]).
[pihita] :: ([c1]).
[pihita_ni_yini] :: ([c1]).
[pihita_ni_yi] :: ([c1]).
[pihita_ni_ata] :: ([c1]).
[pihita_ni_anahi] :: ([c1]).
[pihita_ni_anu] :: ([c1]).
[pihita_ni_ayobu] :: ([c1]).
[pihita_ni_apɔi] :: ([c1]).
[pihinahi_ayi_ka] :: ([c1]).
[pihinahi_yini_ka] :: ([c1]).
[pihinahi] :: ([c1]).
[pihinahi_ni_yini] :: ([c1]).
[pihinahi_ni_yi] :: ([c1]).
[pihinahi_ni_ata] :: ([c1]).
[pihinahi_ni_anahi] :: ([c1]).
[pihinahi_ni_anu] :: ([c1]).
[pihinahi_ni_ayobu] :: ([c1]).
[pihinahi_ni_apɔi] :: ([c1]).
[pihinu_ayi_ka] :: ([c1]).
[pihinu_yini_ka] :: ([c1]).
[pihinu] :: ([c1]).
[pihinu_ni_yini] :: ([c1]).
[pihinu_ni_yi] :: ([c1]).
[pihinu_ni_ata] :: ([c1]).
[pihinu_ni_anahi] :: ([c1]).
[pihinu_ni_anu] :: ([c1]).
[pihinu_ni_ayobu] :: ([c1]).
[pihinu_ni_apɔi] :: ([c1]).
[pihiyobu_ayi_ka] :: ([c1]).
[pihiyobu_yini_ka] :: ([c1]).
[pihiyobu] :: ([c1]).
[pihiyobu_ni_yini] :: ([c1]).
[pihiyobu_ni_yi] :: ([c1]).
[pihiyobu_ni_ata] :: ([c1]).
[pihiyobu_ni_anahi] :: ([c1]).
[pihiyobu_ni_anu] :: ([c1]).
[pihiyobu_ni_ayobu] :: ([c1]).
[pihiyobu_ni_apɔi] :: ([c1]).
[pisopɔi_ayi_ka] :: ([c1]).
[pisopɔi_yini_ka] :: ([c1]).
[pisopɔi] :: ([c1]).
[pisopɔi_ni_yini] :: ([c1]).
[pisopɔi_ni_yi] :: ([c1]).
[pisopɔi_ni_ata] :: ([c1]).
[pisopɔi_ni_anahi] :: ([c1]).
[pisopɔi_ni_anu] :: ([c1]).
[pisopɔi_ni_ayobu] :: ([c1]).
[pisopɔi_ni_apɔi] :: ([c1]).
[pihinii_ayi_ka] :: ([c1]).
[pihinii_yini_ka] :: ([c1]).
[pihinii] :: ([c1]).
[pihinii_ni_yini] :: ([c1]).
[pihinii_ni_yi] :: ([c1]).
[pihinii_ni_ata] :: ([c1]).
[pihinii_ni_anahi] :: ([c1]).
[pihinii_ni_anu] :: ([c1]).
[pihinii_ni_ayobu] :: ([c1]).
[pihinii_ni_apɔi] :: ([c1]).
[pihiwei_ayi_ka] :: ([c1]).
[pihiwei_yini_ka] :: ([c1]).
[pihiwei] :: ([c1]).
[pihiwei_ni_yini] :: ([c1]).
[pihiwei_ni_yi] :: ([c1]).
[pihiwei_ni_ata] :: ([c1]).
[pihiwei_ni_anahi] :: ([c1]).
[pihiwei_ni_anu] :: ([c1]).
[pihiwei_ni_ayobu] :: ([c1]).
[pihiwei_ni_apɔi] :: ([c1]).
[kɔbiga_ayi_ka] :: ([c1]).
[kɔbiga_yini_ka] :: ([c1]).
[kɔbiga] :: ([c1]).
