startCategory(cFin(_)).
[trinta] :: [c3gl].%[trinta] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+fl,c2],dot),epsLi([=c2,+il,c2],dot),epsLi([=c2,+gl,c3gl],dot)]
[treze] :: [c3il].%[treze] :: [c2,-hl,-sl0,-fl,-il,-gl], [epsLi([=c2,+hl,c2],dot),epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+fl,c2],dot),epsLi([=c2,+il,+gl,c2,-il],dot),epsLi([=c2,+il,c3il],dot)]
[treze] :: [c2].%[treze] :: [c2,-hl,-sl0,-fl,-il,-gl], [epsLi([=c2,+gl,c2],dot),epsLi([=c2,+fl,+il,+gl,c2,-fl],dot),epsLi([=c2,+hl,+sl0,+fl,+il,+gl,c2,-hl],dot),epsLi([=c2,+sl0,+fl,+il,+gl,c2,-sl0],dot),epsLi([=c2,+hl,c2],dot),epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+fl,c2],dot),epsLi([=c2,+il,+gl,c2,-il],dot),epsLi([=c2,+il,c2],dot)]
[treze] :: [c2,-il].%[treze] :: [c2,-hl,-sl0,-fl,-il,-gl], [epsLi([=c2,+hl,c2],dot),epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+fl,c2],dot),epsLi([=c2,+il,+gl,c2,-il],dot)]
[sessenta] :: [c3gl].%[sessenta] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+fl,c2],dot),epsLi([=c2,+il,c2],dot),epsLi([=c2,+gl,c3gl],dot)]
[quinze] :: [c3gl].%[quinze] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+fl,c2],dot),epsLi([=c2,+il,c2],dot),epsLi([=c2,+gl,c3gl],dot)]
[quarenta] :: [c3gl].%[quarenta] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+fl,c2],dot),epsLi([=c2,+il,c2],dot),epsLi([=c2,+gl,c3gl],dot)]
[onze] :: [c3gl].%[onze] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+fl,c2],dot),epsLi([=c2,+il,c2],dot),epsLi([=c2,+gl,c3gl],dot)]
[oitenta] :: [c3gl].%[oitenta] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+fl,c2],dot),epsLi([=c2,+il,c2],dot),epsLi([=c2,+gl,c3gl],dot)]
[doze] :: [c3gl].%[doze] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+fl,c2],dot),epsLi([=c2,+il,c2],dot),epsLi([=c2,+gl,c3gl],dot)]
[dez] :: [c3gl].%[dez] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+fl,c2],dot),epsLi([=c2,+il,c2],dot),epsLi([=c2,+gl,c3gl],dot)]
[catorze] :: [c3gl].%[catorze] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+fl,c2],dot),epsLi([=c2,+il,c2],dot),epsLi([=c2,+gl,c3gl],dot)]
[vinte] :: [c3il].%[vinte] :: [c2,-sl0,-il,-gl], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+il,+gl,c2,-il],dot),epsLi([=c2,+il,c3il],dot)]
[vinte] :: [c2].%[vinte] :: [c2,-sl0,-il,-gl], [epsLi([=c2,+sl0,+il,+gl,c2,-sl0],dot),epsLi([=c2,+gl,c2],dot),epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+il,+gl,c2,-il],dot),epsLi([=c2,+il,c2],dot)]
[vinte] :: [c2,-il].%[vinte] :: [c2,-sl0,-il,-gl], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+il,+gl,c2,-il],dot)]
[trinta] :: [c3fl].%[trinta] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+fl,+il,+gl,c2,-fl],dot),epsLi([=c2,+fl,c3fl],dot)]
[trinta] :: [c2].%[trinta] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+gl,c2],dot),epsLi([=c2,+il,c2],dot),epsLi([=c2,+il,+gl,c2,-il],dot),epsLi([=c2,+sl0,+fl,+il,+gl,c2,-sl0],dot),epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+fl,+il,+gl,c2,-fl],dot),epsLi([=c2,+fl,c2],dot)]
[trinta] :: [c2,-fl].%[trinta] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+fl,+il,+gl,c2,-fl],dot)]
[treze] :: [cFin].%[treze] :: [c2,-hl,-sl0,-fl,-il,-gl], [epsLi([=c2,+hl,c2],dot),epsLi([=c2,+sl0,+fl,+il,+gl,c2,-sl0],dot),epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[treze] :: [c3].%[treze] :: [c2,-hl,-sl0,-fl,-il,-gl], [epsLi([=c2,+hl,c2],dot),epsLi([=c2,+sl0,+fl,+il,+gl,c2,-sl0],dot),epsLi([=c2,+sl0,c3],dot)]
[treze] :: [c2,-sl0].%[treze] :: [c2,-hl,-sl0,-fl,-il,-gl], [epsLi([=c2,+hl,c2],dot),epsLi([=c2,+sl0,+fl,+il,+gl,c2,-sl0],dot)]
[sete] :: [c2el].%[sete] :: [c1,-jl,-el,-al], [epsLi([=c1,+jl,c1],dot),epsLi([=c1,+el,+al,c1,-el],dot),epsLi([=c1,+el,c2el],dot)]
[sete] :: [c1].%[sete] :: [c1,-jl,-el,-al], [epsLi([=c1,+jl,+el,+al,c1,-jl],dot),epsLi([=c1,+jl,+al,c1,-jl],dot),epsLi([=c1,+jl,+el,c1,-jl],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,+jl,c1],dot),epsLi([=c1,+el,+al,c1,-el],dot),epsLi([=c1,+el,c1],dot)]
[sete] :: [c1,-el].%[sete] :: [c1,-jl,-el,-al], [epsLi([=c1,+jl,c1],dot),epsLi([=c1,+el,+al,c1,-el],dot)]
[sessenta] :: [c3fl].%[sessenta] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+fl,+il,+gl,c2,-fl],dot),epsLi([=c2,+fl,c3fl],dot)]
[sessenta] :: [c2].%[sessenta] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+gl,c2],dot),epsLi([=c2,+il,c2],dot),epsLi([=c2,+il,+gl,c2,-il],dot),epsLi([=c2,+sl0,+fl,+il,+gl,c2,-sl0],dot),epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+fl,+il,+gl,c2,-fl],dot),epsLi([=c2,+fl,c2],dot)]
[sessenta] :: [c2,-fl].%[sessenta] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+fl,+il,+gl,c2,-fl],dot)]
[seis] :: [c2al].%[seis] :: [c1,-jl,-al], [epsLi([=c1,+jl,c1],dot),epsLi([=c1,+al,c2al],dot)]
[quinze] :: [c3fl].%[quinze] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+fl,+il,+gl,c2,-fl],dot),epsLi([=c2,+fl,c3fl],dot)]
[quinze] :: [c2].%[quinze] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+gl,c2],dot),epsLi([=c2,+il,c2],dot),epsLi([=c2,+il,+gl,c2,-il],dot),epsLi([=c2,+sl0,+fl,+il,+gl,c2,-sl0],dot),epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+fl,+il,+gl,c2,-fl],dot),epsLi([=c2,+fl,c2],dot)]
[quinze] :: [c2,-fl].%[quinze] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+fl,+il,+gl,c2,-fl],dot)]
[quarenta] :: [c3fl].%[quarenta] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+fl,+il,+gl,c2,-fl],dot),epsLi([=c2,+fl,c3fl],dot)]
[quarenta] :: [c2].%[quarenta] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+gl,c2],dot),epsLi([=c2,+il,c2],dot),epsLi([=c2,+il,+gl,c2,-il],dot),epsLi([=c2,+sl0,+fl,+il,+gl,c2,-sl0],dot),epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+fl,+il,+gl,c2,-fl],dot),epsLi([=c2,+fl,c2],dot)]
[quarenta] :: [c2,-fl].%[quarenta] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+fl,+il,+gl,c2,-fl],dot)]
[onze] :: [c3fl].%[onze] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+fl,+il,+gl,c2,-fl],dot),epsLi([=c2,+fl,c3fl],dot)]
[onze] :: [c2].%[onze] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+gl,c2],dot),epsLi([=c2,+il,c2],dot),epsLi([=c2,+il,+gl,c2,-il],dot),epsLi([=c2,+sl0,+fl,+il,+gl,c2,-sl0],dot),epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+fl,+il,+gl,c2,-fl],dot),epsLi([=c2,+fl,c2],dot)]
[onze] :: [c2,-fl].%[onze] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+fl,+il,+gl,c2,-fl],dot)]
[oito] :: [c3jl].%[oito] :: [c1,-bl,-jl], [epsLi([=c1,+bl,c1],dot),epsLi([=c1,+jl,c3jl],dot)]
[oitenta] :: [c3fl].%[oitenta] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+fl,+il,+gl,c2,-fl],dot),epsLi([=c2,+fl,c3fl],dot)]
[oitenta] :: [c2].%[oitenta] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+gl,c2],dot),epsLi([=c2,+il,c2],dot),epsLi([=c2,+il,+gl,c2,-il],dot),epsLi([=c2,+sl0,+fl,+il,+gl,c2,-sl0],dot),epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+fl,+il,+gl,c2,-fl],dot),epsLi([=c2,+fl,c2],dot)]
[oitenta] :: [c2,-fl].%[oitenta] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+fl,+il,+gl,c2,-fl],dot)]
[nove] :: [c1].%[nove] :: [c1,-cl,-jl,-el], [epsLi([=c1,+cl,+jl,+el,c1,-cl],dot),epsLi([=c1,+el,c1],dot),epsLi([=c1,+cl,c1],dot),epsLi([=c1,+jl,+el,c1,-jl],dot),epsLi([=c1,+jl,c1],dot)]
[nove] :: [c3jl].%[nove] :: [c1,-cl,-jl,-el], [epsLi([=c1,+cl,c1],dot),epsLi([=c1,+jl,+el,c1,-jl],dot),epsLi([=c1,+jl,c3jl],dot)]
[nove] :: [c1,-jl].%[nove] :: [c1,-cl,-jl,-el], [epsLi([=c1,+cl,c1],dot),epsLi([=c1,+jl,+el,c1,-jl],dot)]
[doze] :: [c3fl].%[doze] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+fl,+il,+gl,c2,-fl],dot),epsLi([=c2,+fl,c3fl],dot)]
[doze] :: [c2].%[doze] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+gl,c2],dot),epsLi([=c2,+il,c2],dot),epsLi([=c2,+il,+gl,c2,-il],dot),epsLi([=c2,+sl0,+fl,+il,+gl,c2,-sl0],dot),epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+fl,+il,+gl,c2,-fl],dot),epsLi([=c2,+fl,c2],dot)]
[doze] :: [c2,-fl].%[doze] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+fl,+il,+gl,c2,-fl],dot)]
[dez] :: [c3fl].%[dez] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+fl,+il,+gl,c2,-fl],dot),epsLi([=c2,+fl,c3fl],dot)]
[dez] :: [c2].%[dez] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+gl,c2],dot),epsLi([=c2,+il,c2],dot),epsLi([=c2,+il,+gl,c2,-il],dot),epsLi([=c2,+sl0,+fl,+il,+gl,c2,-sl0],dot),epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+fl,+il,+gl,c2,-fl],dot),epsLi([=c2,+fl,c2],dot)]
[dez] :: [c2,-fl].%[dez] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+fl,+il,+gl,c2,-fl],dot)]
[cinquenta] :: [c3il].%[cinquenta] :: [c2,-sl0,-il,-gl], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+il,+gl,c2,-il],dot),epsLi([=c2,+il,c3il],dot)]
[cinquenta] :: [c2].%[cinquenta] :: [c2,-sl0,-il,-gl], [epsLi([=c2,+sl0,+il,+gl,c2,-sl0],dot),epsLi([=c2,+gl,c2],dot),epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+il,+gl,c2,-il],dot),epsLi([=c2,+il,c2],dot)]
[cinquenta] :: [c2,-il].%[cinquenta] :: [c2,-sl0,-il,-gl], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+il,+gl,c2,-il],dot)]
[catorze] :: [c3fl].%[catorze] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+fl,+il,+gl,c2,-fl],dot),epsLi([=c2,+fl,c3fl],dot)]
[catorze] :: [c2].%[catorze] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+gl,c2],dot),epsLi([=c2,+il,c2],dot),epsLi([=c2,+il,+gl,c2,-il],dot),epsLi([=c2,+sl0,+fl,+il,+gl,c2,-sl0],dot),epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+fl,+il,+gl,c2,-fl],dot),epsLi([=c2,+fl,c2],dot)]
[catorze] :: [c2,-fl].%[catorze] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+fl,+il,+gl,c2,-fl],dot)]
[vinte_e] :: [=c1,cFin].%[vinte_e] :: [=c1,c2,-sl0], [epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[vinte_e] :: [=c1,c3].%[vinte_e] :: [=c1,c2,-sl0], [epsLi([=c2,+sl0,c3],dot)]
[vinte_e] :: [=c1,c2].%[vinte_e] :: [=c1,c2,-sl0], [epsLi([=c2,+sl0,c2],dot)]
[vinte_e] :: [=c1,c2,-sl0].
[vinte] :: [cFin].%[vinte] :: [c2,-sl0,-il,-gl], [epsLi([=c2,+sl0,+il,+gl,c2,-sl0],dot),epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[vinte] :: [c3].%[vinte] :: [c2,-sl0,-il,-gl], [epsLi([=c2,+sl0,+il,+gl,c2,-sl0],dot),epsLi([=c2,+sl0,c3],dot)]
[vinte] :: [c2,-sl0].%[vinte] :: [c2,-sl0,-il,-gl], [epsLi([=c2,+sl0,+il,+gl,c2,-sl0],dot)]
[vinte] :: [c2,-sl0,-il,-gl].
[um] :: [cFin].%[um] :: [c1], [epsLi([=c1,c3],dot),epsLi([=c3,cFin],dot)]
[um] :: [c3fl].%[um] :: [c1], [epsLi([=c1,c2,-fl],dot),epsLi([=c2,+fl,c3fl],dot)]
[um] :: [c3il].%[um] :: [c1], [epsLi([=c1,c2,-il],dot),epsLi([=c2,+il,c3il],dot)]
[um] :: [c2].%[um] :: [c1], [epsLi([=c2,+fl,c2],dot),epsLi([=c1,c2,-fl],dot),epsLi([=c2,+il,c2],dot),epsLi([=c1,c2,-il],dot),epsLi([=c1,c2,-gl],dot),epsLi([=c2,+gl,c2],dot)]
[um] :: [c3gl].%[um] :: [c1], [epsLi([=c1,c2,-gl],dot),epsLi([=c2,+gl,c3gl],dot)]
[um] :: [c3].%[um] :: [c1], [epsLi([=c1,c3],dot)]
[um] :: [c2,-fl].%[um] :: [c1], [epsLi([=c1,c2,-fl],dot)]
[um] :: [c2,-il].%[um] :: [c1], [epsLi([=c1,c2,-il],dot)]
[um] :: [c2,-gl].%[um] :: [c1], [epsLi([=c1,c2,-gl],dot)]
[um] :: [c1].
[três] :: [cFin].%[três] :: [c1], [epsLi([=c1,c3],dot),epsLi([=c3,cFin],dot)]
[três] :: [c3fl].%[três] :: [c1], [epsLi([=c1,c2,-fl],dot),epsLi([=c2,+fl,c3fl],dot)]
[três] :: [c3il].%[três] :: [c1], [epsLi([=c1,c2,-il],dot),epsLi([=c2,+il,c3il],dot)]
[três] :: [c2].%[três] :: [c1], [epsLi([=c2,+fl,c2],dot),epsLi([=c1,c2,-fl],dot),epsLi([=c2,+il,c2],dot),epsLi([=c1,c2,-il],dot),epsLi([=c1,c2,-gl],dot),epsLi([=c2,+gl,c2],dot)]
[três] :: [c3gl].%[três] :: [c1], [epsLi([=c1,c2,-gl],dot),epsLi([=c2,+gl,c3gl],dot)]
[três] :: [c3].%[três] :: [c1], [epsLi([=c1,c3],dot)]
[três] :: [c2,-fl].%[três] :: [c1], [epsLi([=c1,c2,-fl],dot)]
[três] :: [c2,-il].%[três] :: [c1], [epsLi([=c1,c2,-il],dot)]
[três] :: [c2,-gl].%[três] :: [c1], [epsLi([=c1,c2,-gl],dot)]
[três] :: [c1].
[trinta_e] :: [=c1,cFin].%[trinta_e] :: [=c1,c2,-sl0], [epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[trinta_e] :: [=c1,c3].%[trinta_e] :: [=c1,c2,-sl0], [epsLi([=c2,+sl0,c3],dot)]
[trinta_e] :: [=c1,c2].%[trinta_e] :: [=c1,c2,-sl0], [epsLi([=c2,+sl0,c2],dot)]
[trinta_e] :: [=c1,c2,-sl0].
[trinta] :: [cFin].%[trinta] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,+fl,+il,+gl,c2,-sl0],dot),epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[trinta] :: [c3].%[trinta] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,+fl,+il,+gl,c2,-sl0],dot),epsLi([=c2,+sl0,c3],dot)]
[trinta] :: [c2,-sl0].%[trinta] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,+fl,+il,+gl,c2,-sl0],dot)]
[trinta] :: [c2,-sl0,-fl,-il,-gl].
[treze] :: [c3hl].%[treze] :: [c2,-hl,-sl0,-fl,-il,-gl], [epsLi([=c2,+hl,+sl0,+fl,+il,+gl,c2,-hl],dot),epsLi([=c2,+hl,c3hl],dot)]
[treze] :: [c2,-hl].%[treze] :: [c2,-hl,-sl0,-fl,-il,-gl], [epsLi([=c2,+hl,+sl0,+fl,+il,+gl,c2,-hl],dot)]
[treze] :: [c2,-hl,-sl0,-fl,-il,-gl].
[sete] :: [cFin].%[sete] :: [c1,-jl,-el,-al], [epsLi([=c1,+el,c1],dot),epsLi([=c1,+el,+al,c1,-el],dot),epsLi([=c1,+jl,+al,c1,-jl],dot),epsLi([=c1,+jl,+el,c1,-jl],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,+jl,+el,+al,c1,-jl],dot),epsLi([=c1,+jl,c1],dot),epsLi([=c1,c3],dot),epsLi([=c3,cFin],dot)]
[sete] :: [c3].%[sete] :: [c1,-jl,-el,-al], [epsLi([=c1,+el,c1],dot),epsLi([=c1,+el,+al,c1,-el],dot),epsLi([=c1,+jl,+al,c1,-jl],dot),epsLi([=c1,+jl,+el,c1,-jl],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,+jl,+el,+al,c1,-jl],dot),epsLi([=c1,+jl,c1],dot),epsLi([=c1,c3],dot)]
[sete] :: [c3fl].%[sete] :: [c1,-jl,-el,-al], [epsLi([=c1,+el,c1],dot),epsLi([=c1,+el,+al,c1,-el],dot),epsLi([=c1,+jl,+al,c1,-jl],dot),epsLi([=c1,+jl,+el,c1,-jl],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,+jl,+el,+al,c1,-jl],dot),epsLi([=c1,+jl,c1],dot),epsLi([=c1,c2,-fl],dot),epsLi([=c2,+fl,c3fl],dot)]
[sete] :: [c2].%[sete] :: [c1,-jl,-el,-al], [epsLi([=c2,+gl,c2],dot),epsLi([=c1,c2,-gl],dot),epsLi([=c2,+il,c2],dot),epsLi([=c1,c2,-il],dot),epsLi([=c1,+el,c1],dot),epsLi([=c1,+el,+al,c1,-el],dot),epsLi([=c1,+jl,+al,c1,-jl],dot),epsLi([=c1,+jl,+el,c1,-jl],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,+jl,+el,+al,c1,-jl],dot),epsLi([=c1,+jl,c1],dot),epsLi([=c1,c2,-fl],dot),epsLi([=c2,+fl,c2],dot)]
[sete] :: [c2,-fl].%[sete] :: [c1,-jl,-el,-al], [epsLi([=c1,+el,c1],dot),epsLi([=c1,+el,+al,c1,-el],dot),epsLi([=c1,+jl,+al,c1,-jl],dot),epsLi([=c1,+jl,+el,c1,-jl],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,+jl,+el,+al,c1,-jl],dot),epsLi([=c1,+jl,c1],dot),epsLi([=c1,c2,-fl],dot)]
[sete] :: [c3il].%[sete] :: [c1,-jl,-el,-al], [epsLi([=c1,+el,c1],dot),epsLi([=c1,+el,+al,c1,-el],dot),epsLi([=c1,+jl,+al,c1,-jl],dot),epsLi([=c1,+jl,+el,c1,-jl],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,+jl,+el,+al,c1,-jl],dot),epsLi([=c1,+jl,c1],dot),epsLi([=c1,c2,-il],dot),epsLi([=c2,+il,c3il],dot)]
[sete] :: [c2,-il].%[sete] :: [c1,-jl,-el,-al], [epsLi([=c1,+el,c1],dot),epsLi([=c1,+el,+al,c1,-el],dot),epsLi([=c1,+jl,+al,c1,-jl],dot),epsLi([=c1,+jl,+el,c1,-jl],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,+jl,+el,+al,c1,-jl],dot),epsLi([=c1,+jl,c1],dot),epsLi([=c1,c2,-il],dot)]
[sete] :: [c3gl].%[sete] :: [c1,-jl,-el,-al], [epsLi([=c1,+el,c1],dot),epsLi([=c1,+el,+al,c1,-el],dot),epsLi([=c1,+jl,+al,c1,-jl],dot),epsLi([=c1,+jl,+el,c1,-jl],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,+jl,+el,+al,c1,-jl],dot),epsLi([=c1,+jl,c1],dot),epsLi([=c1,c2,-gl],dot),epsLi([=c2,+gl,c3gl],dot)]
[sete] :: [c2,-gl].%[sete] :: [c1,-jl,-el,-al], [epsLi([=c1,+el,c1],dot),epsLi([=c1,+el,+al,c1,-el],dot),epsLi([=c1,+jl,+al,c1,-jl],dot),epsLi([=c1,+jl,+el,c1,-jl],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,+jl,+el,+al,c1,-jl],dot),epsLi([=c1,+jl,c1],dot),epsLi([=c1,c2,-gl],dot)]
[sete] :: [c3jl].%[sete] :: [c1,-jl,-el,-al], [epsLi([=c1,+jl,+el,c1,-jl],dot),epsLi([=c1,+jl,+al,c1,-jl],dot),epsLi([=c1,+jl,+el,+al,c1,-jl],dot),epsLi([=c1,+jl,c3jl],dot)]
[sete] :: [c1,-jl].%[sete] :: [c1,-jl,-el,-al], [epsLi([=c1,+jl,+el,c1,-jl],dot),epsLi([=c1,+jl,+al,c1,-jl],dot),epsLi([=c1,+jl,+el,+al,c1,-jl],dot)]
[sete] :: [c1,-jl,-el,-al].
[sessenta_e] :: [=c1,cFin].%[sessenta_e] :: [=c1,c2,-sl0], [epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[sessenta_e] :: [=c1,c3].%[sessenta_e] :: [=c1,c2,-sl0], [epsLi([=c2,+sl0,c3],dot)]
[sessenta_e] :: [=c1,c2].%[sessenta_e] :: [=c1,c2,-sl0], [epsLi([=c2,+sl0,c2],dot)]
[sessenta_e] :: [=c1,c2,-sl0].
[sessenta] :: [cFin].%[sessenta] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,+fl,+il,+gl,c2,-sl0],dot),epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[sessenta] :: [c3].%[sessenta] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,+fl,+il,+gl,c2,-sl0],dot),epsLi([=c2,+sl0,c3],dot)]
[sessenta] :: [c2,-sl0].%[sessenta] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,+fl,+il,+gl,c2,-sl0],dot)]
[sessenta] :: [c2,-sl0,-fl,-il,-gl].
[seis] :: [cFin].%[seis] :: [c1,-jl,-al], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+jl,+al,c1,-jl],dot),epsLi([=c1,+jl,c1],dot),epsLi([=c1,c3],dot),epsLi([=c3,cFin],dot)]
[seis] :: [c3fl].%[seis] :: [c1,-jl,-al], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+jl,+al,c1,-jl],dot),epsLi([=c1,+jl,c1],dot),epsLi([=c1,c2,-fl],dot),epsLi([=c2,+fl,c3fl],dot)]
[seis] :: [c3il].%[seis] :: [c1,-jl,-al], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+jl,+al,c1,-jl],dot),epsLi([=c1,+jl,c1],dot),epsLi([=c1,c2,-il],dot),epsLi([=c2,+il,c3il],dot)]
[seis] :: [c2].%[seis] :: [c1,-jl,-al], [epsLi([=c2,+fl,c2],dot),epsLi([=c1,c2,-fl],dot),epsLi([=c2,+il,c2],dot),epsLi([=c1,c2,-il],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,+jl,+al,c1,-jl],dot),epsLi([=c1,+jl,c1],dot),epsLi([=c1,c2,-gl],dot),epsLi([=c2,+gl,c2],dot)]
[seis] :: [c3gl].%[seis] :: [c1,-jl,-al], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+jl,+al,c1,-jl],dot),epsLi([=c1,+jl,c1],dot),epsLi([=c1,c2,-gl],dot),epsLi([=c2,+gl,c3gl],dot)]
[seis] :: [c2,-gl].%[seis] :: [c1,-jl,-al], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+jl,+al,c1,-jl],dot),epsLi([=c1,+jl,c1],dot),epsLi([=c1,c2,-gl],dot)]
[seis] :: [c2,-il].%[seis] :: [c1,-jl,-al], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+jl,+al,c1,-jl],dot),epsLi([=c1,+jl,c1],dot),epsLi([=c1,c2,-il],dot)]
[seis] :: [c2,-fl].%[seis] :: [c1,-jl,-al], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+jl,+al,c1,-jl],dot),epsLi([=c1,+jl,c1],dot),epsLi([=c1,c2,-fl],dot)]
[seis] :: [c3].%[seis] :: [c1,-jl,-al], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+jl,+al,c1,-jl],dot),epsLi([=c1,+jl,c1],dot),epsLi([=c1,c3],dot)]
[seis] :: [c3jl].%[seis] :: [c1,-jl,-al], [epsLi([=c1,+jl,+al,c1,-jl],dot),epsLi([=c1,+jl,c3jl],dot)]
[seis] :: [c1].%[seis] :: [c1,-jl,-al], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+jl,+al,c1,-jl],dot),epsLi([=c1,+jl,c1],dot)]
[seis] :: [c1,-jl].%[seis] :: [c1,-jl,-al], [epsLi([=c1,+jl,+al,c1,-jl],dot)]
[seis] :: [c1,-jl,-al].
[quinze] :: [cFin].%[quinze] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,+fl,+il,+gl,c2,-sl0],dot),epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[quinze] :: [c3].%[quinze] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,+fl,+il,+gl,c2,-sl0],dot),epsLi([=c2,+sl0,c3],dot)]
[quinze] :: [c2,-sl0].%[quinze] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,+fl,+il,+gl,c2,-sl0],dot)]
[quinze] :: [c2,-sl0,-fl,-il,-gl].
[quinhentos_e] :: [=c3gl,cFin].%[quinhentos_e] :: [=c3gl,c3], [epsLi([=c3,cFin],dot)]
[quinhentos_e] :: [=c3gl,c3].
[quinhentos] :: [cFin].%[quinhentos] :: [c3], [epsLi([=c3,cFin],dot)]
[quinhentos] :: [c3].
[quatro] :: [c3gl].%[quatro] :: [c1,-jl], [epsLi([=c1,+jl,c1],dot),epsLi([=c1,c2,-gl],dot),epsLi([=c2,+gl,c3gl],dot)]
[quatro] :: [c3il].%[quatro] :: [c1,-jl], [epsLi([=c1,+jl,c1],dot),epsLi([=c1,c2,-il],dot),epsLi([=c2,+il,c3il],dot)]
[quatro] :: [c2].%[quatro] :: [c1,-jl], [epsLi([=c2,+gl,c2],dot),epsLi([=c1,c2,-gl],dot),epsLi([=c2,+il,c2],dot),epsLi([=c1,c2,-il],dot),epsLi([=c1,+jl,c1],dot),epsLi([=c1,c2,-fl],dot),epsLi([=c2,+fl,c2],dot)]
[quatro] :: [c3fl].%[quatro] :: [c1,-jl], [epsLi([=c1,+jl,c1],dot),epsLi([=c1,c2,-fl],dot),epsLi([=c2,+fl,c3fl],dot)]
[quatro] :: [cFin].%[quatro] :: [c1,-jl], [epsLi([=c1,+jl,c1],dot),epsLi([=c1,c3],dot),epsLi([=c3,cFin],dot)]
[quatro] :: [c2,-gl].%[quatro] :: [c1,-jl], [epsLi([=c1,+jl,c1],dot),epsLi([=c1,c2,-gl],dot)]
[quatro] :: [c2,-il].%[quatro] :: [c1,-jl], [epsLi([=c1,+jl,c1],dot),epsLi([=c1,c2,-il],dot)]
[quatro] :: [c2,-fl].%[quatro] :: [c1,-jl], [epsLi([=c1,+jl,c1],dot),epsLi([=c1,c2,-fl],dot)]
[quatro] :: [c3].%[quatro] :: [c1,-jl], [epsLi([=c1,+jl,c1],dot),epsLi([=c1,c3],dot)]
[quatro] :: [c1].%[quatro] :: [c1,-jl], [epsLi([=c1,+jl,c1],dot)]
[quatro] :: [c3jl].%[quatro] :: [c1,-jl], [epsLi([=c1,+jl,c3jl],dot)]
[quatro] :: [c1,-jl].
[quarenta_e] :: [=c1,cFin].%[quarenta_e] :: [=c1,c2,-sl0], [epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[quarenta_e] :: [=c1,c3].%[quarenta_e] :: [=c1,c2,-sl0], [epsLi([=c2,+sl0,c3],dot)]
[quarenta_e] :: [=c1,c2].%[quarenta_e] :: [=c1,c2,-sl0], [epsLi([=c2,+sl0,c2],dot)]
[quarenta_e] :: [=c1,c2,-sl0].
[quarenta] :: [cFin].%[quarenta] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,+fl,+il,+gl,c2,-sl0],dot),epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[quarenta] :: [c3].%[quarenta] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,+fl,+il,+gl,c2,-sl0],dot),epsLi([=c2,+sl0,c3],dot)]
[quarenta] :: [c2,-sl0].%[quarenta] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,+fl,+il,+gl,c2,-sl0],dot)]
[quarenta] :: [c2,-sl0,-fl,-il,-gl].
[onze] :: [cFin].%[onze] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,+fl,+il,+gl,c2,-sl0],dot),epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[onze] :: [c3].%[onze] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,+fl,+il,+gl,c2,-sl0],dot),epsLi([=c2,+sl0,c3],dot)]
[onze] :: [c2,-sl0].%[onze] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,+fl,+il,+gl,c2,-sl0],dot)]
[onze] :: [c2,-sl0,-fl,-il,-gl].
[oito] :: [cFin].%[oito] :: [c1,-bl,-jl], [epsLi([=c1,+jl,c1],dot),epsLi([=c1,+bl,+jl,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c3],dot),epsLi([=c3,cFin],dot)]
[oito] :: [c3fl].%[oito] :: [c1,-bl,-jl], [epsLi([=c1,+jl,c1],dot),epsLi([=c1,+bl,+jl,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-fl],dot),epsLi([=c2,+fl,c3fl],dot)]
[oito] :: [c3il].%[oito] :: [c1,-bl,-jl], [epsLi([=c1,+jl,c1],dot),epsLi([=c1,+bl,+jl,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-il],dot),epsLi([=c2,+il,c3il],dot)]
[oito] :: [c2].%[oito] :: [c1,-bl,-jl], [epsLi([=c2,+fl,c2],dot),epsLi([=c1,c2,-fl],dot),epsLi([=c2,+il,c2],dot),epsLi([=c1,c2,-il],dot),epsLi([=c1,+jl,c1],dot),epsLi([=c1,+bl,+jl,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-gl],dot),epsLi([=c2,+gl,c2],dot)]
[oito] :: [c3gl].%[oito] :: [c1,-bl,-jl], [epsLi([=c1,+jl,c1],dot),epsLi([=c1,+bl,+jl,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-gl],dot),epsLi([=c2,+gl,c3gl],dot)]
[oito] :: [c2,-gl].%[oito] :: [c1,-bl,-jl], [epsLi([=c1,+jl,c1],dot),epsLi([=c1,+bl,+jl,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-gl],dot)]
[oito] :: [c2,-il].%[oito] :: [c1,-bl,-jl], [epsLi([=c1,+jl,c1],dot),epsLi([=c1,+bl,+jl,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-il],dot)]
[oito] :: [c2,-fl].%[oito] :: [c1,-bl,-jl], [epsLi([=c1,+jl,c1],dot),epsLi([=c1,+bl,+jl,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-fl],dot)]
[oito] :: [c3].%[oito] :: [c1,-bl,-jl], [epsLi([=c1,+jl,c1],dot),epsLi([=c1,+bl,+jl,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c3],dot)]
[oito] :: [c1].%[oito] :: [c1,-bl,-jl], [epsLi([=c1,+jl,c1],dot),epsLi([=c1,+bl,+jl,c1,-bl],dot),epsLi([=c1,+bl,c1],dot)]
[oito] :: [c2bl].%[oito] :: [c1,-bl,-jl], [epsLi([=c1,+bl,+jl,c1,-bl],dot),epsLi([=c1,+bl,c2bl],dot)]
[oito] :: [c1,-bl].%[oito] :: [c1,-bl,-jl], [epsLi([=c1,+bl,+jl,c1,-bl],dot)]
[oito] :: [c1,-bl,-jl].
[oitenta_e] :: [=c1,cFin].%[oitenta_e] :: [=c1,c2,-sl0], [epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[oitenta_e] :: [=c1,c3].%[oitenta_e] :: [=c1,c2,-sl0], [epsLi([=c2,+sl0,c3],dot)]
[oitenta_e] :: [=c1,c2].%[oitenta_e] :: [=c1,c2,-sl0], [epsLi([=c2,+sl0,c2],dot)]
[oitenta_e] :: [=c1,c2,-sl0].
[oitenta] :: [cFin].%[oitenta] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,+fl,+il,+gl,c2,-sl0],dot),epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[oitenta] :: [c3].%[oitenta] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,+fl,+il,+gl,c2,-sl0],dot),epsLi([=c2,+sl0,c3],dot)]
[oitenta] :: [c2,-sl0].%[oitenta] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,+fl,+il,+gl,c2,-sl0],dot)]
[oitenta] :: [c2,-sl0,-fl,-il,-gl].
[ntos_e_vinte_e_cinco] :: [=c2,+hl,cFin].%[ntos_e_vinte_e_cinco] :: [=c2,+hl,c3], [epsLi([=c3,cFin],dot)]
[ntos_e_vinte_e_cinco] :: [=c2,+hl,c3].
[ntos_e] :: [=c3il,=c3hl,cFin].%[ntos_e] :: [=c3il,=c3hl,c3], [epsLi([=c3,cFin],dot)]
[ntos_e] :: [=c3il,=c3hl,c3].
[ntos] :: [=c2,+hl,cFin].%[ntos] :: [=c2,+hl,c3], [epsLi([=c3,cFin],dot)]
[ntos] :: [=c2,+hl,c3].
[nta_e] :: [=c1,=c2el,cFin].%[nta_e] :: [=c1,=c2el,c2,-sl0], [epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[nta_e] :: [=c1,=c2el,c3].%[nta_e] :: [=c1,=c2el,c2,-sl0], [epsLi([=c2,+sl0,c3],dot)]
[nta_e] :: [=c1,=c2el,c2].%[nta_e] :: [=c1,=c2el,c2,-sl0], [epsLi([=c2,+sl0,c2],dot)]
[nta_e] :: [=c1,=c2el,c2,-sl0].
[nta] :: [=c1,+el,cFin].%[nta] :: [=c1,+el,c2,-sl0], [epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[nta] :: [=c1,+el,c3].%[nta] :: [=c1,+el,c2,-sl0], [epsLi([=c2,+sl0,c3],dot)]
[nta] :: [=c1,+el,c2].%[nta] :: [=c1,+el,c2,-sl0], [epsLi([=c2,+sl0,c2],dot)]
[nta] :: [=c1,+el,c2,-sl0].
[nove] :: [cFin].%[nove] :: [c1,-cl,-jl,-el], [epsLi([=c1,+jl,c1],dot),epsLi([=c1,+jl,+el,c1,-jl],dot),epsLi([=c1,+el,c1],dot),epsLi([=c1,+cl,+jl,+el,c1,-cl],dot),epsLi([=c1,+cl,c1],dot),epsLi([=c1,c3],dot),epsLi([=c3,cFin],dot)]
[nove] :: [c3].%[nove] :: [c1,-cl,-jl,-el], [epsLi([=c1,+jl,c1],dot),epsLi([=c1,+jl,+el,c1,-jl],dot),epsLi([=c1,+el,c1],dot),epsLi([=c1,+cl,+jl,+el,c1,-cl],dot),epsLi([=c1,+cl,c1],dot),epsLi([=c1,c3],dot)]
[nove] :: [c3fl].%[nove] :: [c1,-cl,-jl,-el], [epsLi([=c1,+jl,c1],dot),epsLi([=c1,+jl,+el,c1,-jl],dot),epsLi([=c1,+el,c1],dot),epsLi([=c1,+cl,+jl,+el,c1,-cl],dot),epsLi([=c1,+cl,c1],dot),epsLi([=c1,c2,-fl],dot),epsLi([=c2,+fl,c3fl],dot)]
[nove] :: [c2].%[nove] :: [c1,-cl,-jl,-el], [epsLi([=c2,+gl,c2],dot),epsLi([=c1,c2,-gl],dot),epsLi([=c2,+il,c2],dot),epsLi([=c1,c2,-il],dot),epsLi([=c1,+jl,c1],dot),epsLi([=c1,+jl,+el,c1,-jl],dot),epsLi([=c1,+el,c1],dot),epsLi([=c1,+cl,+jl,+el,c1,-cl],dot),epsLi([=c1,+cl,c1],dot),epsLi([=c1,c2,-fl],dot),epsLi([=c2,+fl,c2],dot)]
[nove] :: [c2,-fl].%[nove] :: [c1,-cl,-jl,-el], [epsLi([=c1,+jl,c1],dot),epsLi([=c1,+jl,+el,c1,-jl],dot),epsLi([=c1,+el,c1],dot),epsLi([=c1,+cl,+jl,+el,c1,-cl],dot),epsLi([=c1,+cl,c1],dot),epsLi([=c1,c2,-fl],dot)]
[nove] :: [c3il].%[nove] :: [c1,-cl,-jl,-el], [epsLi([=c1,+jl,c1],dot),epsLi([=c1,+jl,+el,c1,-jl],dot),epsLi([=c1,+el,c1],dot),epsLi([=c1,+cl,+jl,+el,c1,-cl],dot),epsLi([=c1,+cl,c1],dot),epsLi([=c1,c2,-il],dot),epsLi([=c2,+il,c3il],dot)]
[nove] :: [c2,-il].%[nove] :: [c1,-cl,-jl,-el], [epsLi([=c1,+jl,c1],dot),epsLi([=c1,+jl,+el,c1,-jl],dot),epsLi([=c1,+el,c1],dot),epsLi([=c1,+cl,+jl,+el,c1,-cl],dot),epsLi([=c1,+cl,c1],dot),epsLi([=c1,c2,-il],dot)]
[nove] :: [c3gl].%[nove] :: [c1,-cl,-jl,-el], [epsLi([=c1,+jl,c1],dot),epsLi([=c1,+jl,+el,c1,-jl],dot),epsLi([=c1,+el,c1],dot),epsLi([=c1,+cl,+jl,+el,c1,-cl],dot),epsLi([=c1,+cl,c1],dot),epsLi([=c1,c2,-gl],dot),epsLi([=c2,+gl,c3gl],dot)]
[nove] :: [c2,-gl].%[nove] :: [c1,-cl,-jl,-el], [epsLi([=c1,+jl,c1],dot),epsLi([=c1,+jl,+el,c1,-jl],dot),epsLi([=c1,+el,c1],dot),epsLi([=c1,+cl,+jl,+el,c1,-cl],dot),epsLi([=c1,+cl,c1],dot),epsLi([=c1,c2,-gl],dot)]
[nove] :: [c2cl].%[nove] :: [c1,-cl,-jl,-el], [epsLi([=c1,+cl,+jl,+el,c1,-cl],dot),epsLi([=c1,+cl,c2cl],dot)]
[nove] :: [c1,-cl].%[nove] :: [c1,-cl,-jl,-el], [epsLi([=c1,+cl,+jl,+el,c1,-cl],dot)]
[nove] :: [c1,-cl,-jl,-el].
[duzentos_e] :: [=c3gl,cFin].%[duzentos_e] :: [=c3gl,c3], [epsLi([=c3,cFin],dot)]
[duzentos_e] :: [=c3gl,c3].
[duzentos] :: [cFin].%[duzentos] :: [c3], [epsLi([=c3,cFin],dot)]
[duzentos] :: [c3].
[doze] :: [cFin].%[doze] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,+fl,+il,+gl,c2,-sl0],dot),epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[doze] :: [c3].%[doze] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,+fl,+il,+gl,c2,-sl0],dot),epsLi([=c2,+sl0,c3],dot)]
[doze] :: [c2,-sl0].%[doze] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,+fl,+il,+gl,c2,-sl0],dot)]
[doze] :: [c2,-sl0,-fl,-il,-gl].
[dois] :: [cFin].%[dois] :: [c1], [epsLi([=c1,c3],dot),epsLi([=c3,cFin],dot)]
[dois] :: [c3fl].%[dois] :: [c1], [epsLi([=c1,c2,-fl],dot),epsLi([=c2,+fl,c3fl],dot)]
[dois] :: [c3il].%[dois] :: [c1], [epsLi([=c1,c2,-il],dot),epsLi([=c2,+il,c3il],dot)]
[dois] :: [c2].%[dois] :: [c1], [epsLi([=c2,+fl,c2],dot),epsLi([=c1,c2,-fl],dot),epsLi([=c2,+il,c2],dot),epsLi([=c1,c2,-il],dot),epsLi([=c1,c2,-gl],dot),epsLi([=c2,+gl,c2],dot)]
[dois] :: [c3gl].%[dois] :: [c1], [epsLi([=c1,c2,-gl],dot),epsLi([=c2,+gl,c3gl],dot)]
[dois] :: [c3].%[dois] :: [c1], [epsLi([=c1,c3],dot)]
[dois] :: [c2,-fl].%[dois] :: [c1], [epsLi([=c1,c2,-fl],dot)]
[dois] :: [c2,-il].%[dois] :: [c1], [epsLi([=c1,c2,-il],dot)]
[dois] :: [c2,-gl].%[dois] :: [c1], [epsLi([=c1,c2,-gl],dot)]
[dois] :: [c1].
[dezas] :: [=c2al,cFin].%[dezas] :: [=c2al,c2,-sl0], [epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[dezas] :: [=c2al,c3].%[dezas] :: [=c2al,c2,-sl0], [epsLi([=c2,+sl0,c3],dot)]
[dezas] :: [=c2al,c2].%[dezas] :: [=c2al,c2,-sl0], [epsLi([=c2,+sl0,c2],dot)]
[dezas] :: [=c2al,c2,-sl0].
[deza] :: [=c2cl,cFin].%[deza] :: [=c2cl,c2,-sl0], [epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[deza] :: [=c2cl,c3].%[deza] :: [=c2cl,c2,-sl0], [epsLi([=c2,+sl0,c3],dot)]
[deza] :: [=c2cl,c2].%[deza] :: [=c2cl,c2,-sl0], [epsLi([=c2,+sl0,c2],dot)]
[deza] :: [=c2cl,c2,-sl0].
[dez] :: [=c2bl,cFin].%[dez] :: [=c2bl,c2,-sl0], [epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[dez] :: [=c2bl,c3].%[dez] :: [=c2bl,c2,-sl0], [epsLi([=c2,+sl0,c3],dot)]
[dez] :: [=c2bl,c2].%[dez] :: [=c2bl,c2,-sl0], [epsLi([=c2,+sl0,c2],dot)]
[dez] :: [=c2bl,c2,-sl0].
[dez] :: [cFin].%[dez] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,+fl,+il,+gl,c2,-sl0],dot),epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[dez] :: [c3].%[dez] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,+fl,+il,+gl,c2,-sl0],dot),epsLi([=c2,+sl0,c3],dot)]
[dez] :: [c2,-sl0].%[dez] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,+fl,+il,+gl,c2,-sl0],dot)]
[dez] :: [c2,-sl0,-fl,-il,-gl].
[cinquenta_e] :: [=c1,cFin].%[cinquenta_e] :: [=c1,c2,-sl0], [epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[cinquenta_e] :: [=c1,c3].%[cinquenta_e] :: [=c1,c2,-sl0], [epsLi([=c2,+sl0,c3],dot)]
[cinquenta_e] :: [=c1,c2].%[cinquenta_e] :: [=c1,c2,-sl0], [epsLi([=c2,+sl0,c2],dot)]
[cinquenta_e] :: [=c1,c2,-sl0].
[cinquenta] :: [cFin].%[cinquenta] :: [c2,-sl0,-il,-gl], [epsLi([=c2,+sl0,+il,+gl,c2,-sl0],dot),epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[cinquenta] :: [c3].%[cinquenta] :: [c2,-sl0,-il,-gl], [epsLi([=c2,+sl0,+il,+gl,c2,-sl0],dot),epsLi([=c2,+sl0,c3],dot)]
[cinquenta] :: [c2,-sl0].%[cinquenta] :: [c2,-sl0,-il,-gl], [epsLi([=c2,+sl0,+il,+gl,c2,-sl0],dot)]
[cinquenta] :: [c2,-sl0,-il,-gl].
[cinco] :: [cFin].%[cinco] :: [c1], [epsLi([=c1,c3],dot),epsLi([=c3,cFin],dot)]
[cinco] :: [c3fl].%[cinco] :: [c1], [epsLi([=c1,c2,-fl],dot),epsLi([=c2,+fl,c3fl],dot)]
[cinco] :: [c3il].%[cinco] :: [c1], [epsLi([=c1,c2,-il],dot),epsLi([=c2,+il,c3il],dot)]
[cinco] :: [c2].%[cinco] :: [c1], [epsLi([=c2,+fl,c2],dot),epsLi([=c1,c2,-fl],dot),epsLi([=c2,+il,c2],dot),epsLi([=c1,c2,-il],dot),epsLi([=c1,c2,-gl],dot),epsLi([=c2,+gl,c2],dot)]
[cinco] :: [c3gl].%[cinco] :: [c1], [epsLi([=c1,c2,-gl],dot),epsLi([=c2,+gl,c3gl],dot)]
[cinco] :: [c3].%[cinco] :: [c1], [epsLi([=c1,c3],dot)]
[cinco] :: [c2,-fl].%[cinco] :: [c1], [epsLi([=c1,c2,-fl],dot)]
[cinco] :: [c2,-il].%[cinco] :: [c1], [epsLi([=c1,c2,-il],dot)]
[cinco] :: [c2,-gl].%[cinco] :: [c1], [epsLi([=c1,c2,-gl],dot)]
[cinco] :: [c1].
[centos_e] :: [=c3gl,=c3jl,cFin].%[centos_e] :: [=c3gl,=c3jl,c3], [epsLi([=c3,cFin],dot)]
[centos_e] :: [=c3gl,=c3jl,c3].
[centos] :: [=c1,+jl,cFin].%[centos] :: [=c1,+jl,c3], [epsLi([=c3,cFin],dot)]
[centos] :: [=c1,+jl,c3].
[cento_e_vinte_e] :: [=c1,cFin].%[cento_e_vinte_e] :: [=c1,c3], [epsLi([=c3,cFin],dot)]
[cento_e_vinte_e] :: [=c1,c3].
[cento_e_vinte] :: [cFin].%[cento_e_vinte] :: [c3], [epsLi([=c3,cFin],dot)]
[cento_e_vinte] :: [c3].
[cento_e_cinquenta_e] :: [=c1,cFin].%[cento_e_cinquenta_e] :: [=c1,c3], [epsLi([=c3,cFin],dot)]
[cento_e_cinquenta_e] :: [=c1,c3].
[cento_e_cinquenta] :: [cFin].%[cento_e_cinquenta] :: [c3], [epsLi([=c3,cFin],dot)]
[cento_e_cinquenta] :: [c3].
[cento_e] :: [=c3fl,cFin].%[cento_e] :: [=c3fl,c3], [epsLi([=c3,cFin],dot)]
[cento_e] :: [=c3fl,c3].
[cem] :: [cFin].%[cem] :: [c3], [epsLi([=c3,cFin],dot)]
[cem] :: [c3].
[catorze] :: [cFin].%[catorze] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,+fl,+il,+gl,c2,-sl0],dot),epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[catorze] :: [c3].%[catorze] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,+fl,+il,+gl,c2,-sl0],dot),epsLi([=c2,+sl0,c3],dot)]
[catorze] :: [c2,-sl0].%[catorze] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,+fl,+il,+gl,c2,-sl0],dot)]
[catorze] :: [c2,-sl0,-fl,-il,-gl].
[catorze] :: [c3il].%[catorze] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+fl,c2],dot),epsLi([=c2,+il,+gl,c2,-il],dot),epsLi([=c2,+il,c3il],dot)]
[catorze] :: [c2,-il].%[catorze] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+fl,c2],dot),epsLi([=c2,+il,+gl,c2,-il],dot)]
[cinquenta] :: [c3gl].%[cinquenta] :: [c2,-sl0,-il,-gl], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+il,c2],dot),epsLi([=c2,+gl,c3gl],dot)]
[dez] :: [c3il].%[dez] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+fl,c2],dot),epsLi([=c2,+il,+gl,c2,-il],dot),epsLi([=c2,+il,c3il],dot)]
[dez] :: [c2,-il].%[dez] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+fl,c2],dot),epsLi([=c2,+il,+gl,c2,-il],dot)]
[doze] :: [c3il].%[doze] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+fl,c2],dot),epsLi([=c2,+il,+gl,c2,-il],dot),epsLi([=c2,+il,c3il],dot)]
[doze] :: [c2,-il].%[doze] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+fl,c2],dot),epsLi([=c2,+il,+gl,c2,-il],dot)]
[nove] :: [c2el].%[nove] :: [c1,-cl,-jl,-el], [epsLi([=c1,+cl,c1],dot),epsLi([=c1,+jl,c1],dot),epsLi([=c1,+el,c2el],dot)]
[oitenta] :: [c3il].%[oitenta] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+fl,c2],dot),epsLi([=c2,+il,+gl,c2,-il],dot),epsLi([=c2,+il,c3il],dot)]
[oitenta] :: [c2,-il].%[oitenta] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+fl,c2],dot),epsLi([=c2,+il,+gl,c2,-il],dot)]
[onze] :: [c3il].%[onze] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+fl,c2],dot),epsLi([=c2,+il,+gl,c2,-il],dot),epsLi([=c2,+il,c3il],dot)]
[onze] :: [c2,-il].%[onze] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+fl,c2],dot),epsLi([=c2,+il,+gl,c2,-il],dot)]
[quarenta] :: [c3il].%[quarenta] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+fl,c2],dot),epsLi([=c2,+il,+gl,c2,-il],dot),epsLi([=c2,+il,c3il],dot)]
[quarenta] :: [c2,-il].%[quarenta] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+fl,c2],dot),epsLi([=c2,+il,+gl,c2,-il],dot)]
[quinze] :: [c3il].%[quinze] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+fl,c2],dot),epsLi([=c2,+il,+gl,c2,-il],dot),epsLi([=c2,+il,c3il],dot)]
[quinze] :: [c2,-il].%[quinze] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+fl,c2],dot),epsLi([=c2,+il,+gl,c2,-il],dot)]
[sessenta] :: [c3il].%[sessenta] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+fl,c2],dot),epsLi([=c2,+il,+gl,c2,-il],dot),epsLi([=c2,+il,c3il],dot)]
[sessenta] :: [c2,-il].%[sessenta] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+fl,c2],dot),epsLi([=c2,+il,+gl,c2,-il],dot)]
[sete] :: [c2al].%[sete] :: [c1,-jl,-el,-al], [epsLi([=c1,+jl,c1],dot),epsLi([=c1,+el,c1],dot),epsLi([=c1,+al,c2al],dot)]
[treze] :: [c3fl].%[treze] :: [c2,-hl,-sl0,-fl,-il,-gl], [epsLi([=c2,+hl,c2],dot),epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+fl,+il,+gl,c2,-fl],dot),epsLi([=c2,+fl,c3fl],dot)]
[treze] :: [c2,-fl].%[treze] :: [c2,-hl,-sl0,-fl,-il,-gl], [epsLi([=c2,+hl,c2],dot),epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+fl,+il,+gl,c2,-fl],dot)]
[trinta] :: [c3il].%[trinta] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+fl,c2],dot),epsLi([=c2,+il,+gl,c2,-il],dot),epsLi([=c2,+il,c3il],dot)]
[trinta] :: [c2,-il].%[trinta] :: [c2,-sl0,-fl,-il,-gl], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+fl,c2],dot),epsLi([=c2,+il,+gl,c2,-il],dot)]
[vinte] :: [c3gl].%[vinte] :: [c2,-sl0,-il,-gl], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+il,c2],dot),epsLi([=c2,+gl,c3gl],dot)]
[treze] :: [c3gl].%[treze] :: [c2,-hl,-sl0,-fl,-il,-gl], [epsLi([=c2,+hl,c2],dot),epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+fl,c2],dot),epsLi([=c2,+il,c2],dot),epsLi([=c2,+gl,c3gl],dot)]
