startCategory(c4(_)).
[vier] :: [c1].
[vier] :: [c1].
[vier] :: [c1].
[vier] :: [c1].
[vier] :: [c1].
[vier] :: [c1].
[vier] :: [c1,-zeh].
[neun] :: [c1].
[neun] :: [c1,-zeh].
[fuenf] :: [c1].
[fuenf] :: [c1,-zeh].
[drei] :: [c1].
[drei] :: [c1,-zeh].
[acht] :: [c1].
[acht] :: [c1,-zeh].
[zwoelf] :: [c4].
[zwoelf] :: [c3].
[zwoelf] :: [c2].
[zwoelf] :: [c3,-taus].
[zwoelf] :: [c2,-tausU].
[zwei] :: [c4].
[zwei] :: [c3].
[zwei] :: [c3,-taus].
[zwei] :: [c2].
[zwei] :: [cun].
[zwei] :: [c1,-un].
[zwei] :: [c1].
[zwei] :: [c2,-tausU].
[zwei] :: [c1,-unU].
[zwanzig] :: [c4].
[zwanzig] :: [c3].
[zwanzig] :: [c2].
[zwanzig] :: [c3,-taus].
[zwanzig] :: [c2,-tausU].
[zig] :: [=c1,+zi,cundZIG].
[zig] :: [=c1,+zi,c4].
[zig] :: [=c1,+zi,c3].
[zig] :: [=c1,+zi,c2].
[zig] :: [=c1,+zi,c3,-taus].
[zig] :: [=c1,+zi,c2,-tausU].
[zehn] :: [=c1,+zeh,c4].
[zehn] :: [=c1,+zeh,c3].
[zehn] :: [=c1,+zeh,c2].
[zehn] :: [=c1,+zeh,c3,-taus].
[zehn] :: [=c1,+zeh,c2,-tausU].
[zehn] :: [c4].
[zehn] :: [c3].
[zehn] :: [c2].
[zehn] :: [c3,-taus].
[zehn] :: [c2,-tausU].
[vier] :: [c4].
[vier] :: [c3].
[vier] :: [c2].
[vier] :: [c1,-zi].
[vier] :: [c1,-zi,-zeh,-unU].
[undzwanzig] :: [=c1,+un,c4].
[undzwanzig] :: [=c1,+un,c3].
[undzwanzig] :: [=c1,+un,c2].
[undzwanzig] :: [=c1,+un,c3,-taus].
[undzwanzig] :: [=c1,+un,c2,-tausU].
[undsiebzig] :: [=c1,+un,c4].
[undsiebzig] :: [=c1,+un,c3].
[undsiebzig] :: [=c1,+un,c2].
[undsiebzig] :: [=c1,+un,c3,-taus].
[undsiebzig] :: [=c1,+un,c2,-tausU].
[undsechzig] :: [=c1,+un,c4].
[undsechzig] :: [=c1,+un,c3].
[undsechzig] :: [=c1,+un,c2].
[undsechzig] :: [=c1,+un,c3,-taus].
[undsechzig] :: [=c1,+un,c2,-tausU].
[und] :: [=cundZIG,=cun,c4].
[und] :: [=cundZIG,=cun,c3].
[und] :: [=cundZIG,=cun,c2].
[und] :: [=cundZIG,=cun,c3,-taus].
[und] :: [=cundZIG,=cun,c2,-tausU].
[tausend] :: [=c3,=c3,+taus,c4].
[tausend] :: [=c3,+taus,c4].
[ssig] :: [=c1,+ssi,cundZIG].
[ssig] :: [=c1,+ssi,c4].
[ssig] :: [=c1,+ssi,c3].
[ssig] :: [=c1,+ssi,c2].
[ssig] :: [=c1,+ssi,c3,-taus].
[ssig] :: [=c1,+ssi,c2,-tausU].
[siebzig] :: [c4].
[siebzig] :: [c3].
[siebzig] :: [c2].
[siebzig] :: [c3,-taus].
[siebzig] :: [c2,-tausU].
[siebzehn] :: [c4].
[siebzehn] :: [c3].
[siebzehn] :: [c2].
[siebzehn] :: [c3,-taus].
[siebzehn] :: [c2,-tausU].
[sieben] :: [c4].
[sieben] :: [c3].
[sieben] :: [c3,-taus].
[sieben] :: [c2].
[sieben] :: [cun].
[sieben] :: [c1,-un].
[sieben] :: [c1].
[sieben] :: [c2,-tausU].
[sieben] :: [c1,-unU].
[sechzig] :: [c4].
[sechzig] :: [c3].
[sechzig] :: [c2].
[sechzig] :: [c3,-taus].
[sechzig] :: [c2,-tausU].
[sechzehn] :: [c4].
[sechzehn] :: [c3].
[sechzehn] :: [c2].
[sechzehn] :: [c3,-taus].
[sechzehn] :: [c2,-tausU].
[sechs] :: [c4].
[sechs] :: [c3].
[sechs] :: [c3,-taus].
[sechs] :: [c2].
[sechs] :: [cun].
[sechs] :: [c1,-un].
[sechs] :: [c1].
[sechs] :: [c2,-tausU].
[sechs] :: [c1,-unU].
[neun] :: [c4].
[neun] :: [c3].
[neun] :: [c2].
[neun] :: [c1,-zi].
[neun] :: [c1,-zi,-zeh,-unU].
[hundert] :: [=c2,=cun,c4].
[hundert] :: [=c2,=cun,c3].
[hundert] :: [=c2,=cun,c3,-taus].
[hundert] :: [=c1,+un,c4].
[hundert] :: [=c1,+un,c3].
[hundert] :: [=c1,+un,c3,-taus].
[fuenf] :: [c4].
[fuenf] :: [c3].
[fuenf] :: [c2].
[fuenf] :: [c1,-zi].
[fuenf] :: [c1,-zi,-zeh,-unU].
[elf] :: [c4].
[elf] :: [c3].
[elf] :: [c2].
[elf] :: [c3,-taus].
[elf] :: [c2,-tausU].
[einundzwanzig] :: [c4].
[einundzwanzig] :: [c3].
[einundzwanzig] :: [c2].
[einundzwanzig] :: [c3,-taus].
[einundzwanzig] :: [c2,-tausU].
[einundsiebzig] :: [c4].
[einundsiebzig] :: [c3].
[einundsiebzig] :: [c2].
[einundsiebzig] :: [c3,-taus].
[einundsiebzig] :: [c2,-tausU].
[einundsechzig] :: [c4].
[einundsechzig] :: [c3].
[einundsechzig] :: [c2].
[einundsechzig] :: [c3,-taus].
[einundsechzig] :: [c2,-tausU].
[einund] :: [=cundZIG,c4].
[einund] :: [=cundZIG,c3].
[einund] :: [=cundZIG,c2].
[einund] :: [=cundZIG,c3,-taus].
[einund] :: [=cundZIG,c2,-tausU].
[eintausend] :: [=c3,c4].
[eintausend] :: [c4].
[eins] :: [c4].
[eins] :: [c3].
[eins] :: [c2].
[eins] :: [c1].
[einhundert] :: [=c2,c4].
[einhundert] :: [=c2,c3].
[einhundert] :: [=c2,c3,-taus].
[einhundert] :: [c4].
[einhundert] :: [c3].
[einhundert] :: [c3,-taus].
[drei] :: [c4].
[drei] :: [c3].
[drei] :: [c2].
[drei] :: [c1,-ssi].
[drei] :: [c1,-ssi,-zeh,-unU].
[acht] :: [c4].
[acht] :: [c3].
[acht] :: [c2].
[acht] :: [c1,-zi].
[acht] :: [c1,-zi,-zeh,-unU].
[acht] :: [cun].
[acht] :: [c1,-un].
[acht] :: [c3,-taus].
[acht] :: [c2,-tausU].
[drei] :: [cun].
[drei] :: [c1,-un].
[drei] :: [c3,-taus].
[drei] :: [c2,-tausU].
[fuenf] :: [cun].
[fuenf] :: [c1,-un].
[fuenf] :: [c3,-taus].
[fuenf] :: [c2,-tausU].
[neun] :: [cun].
[neun] :: [c1,-un].
[neun] :: [c3,-taus].
[neun] :: [c2,-tausU].
[vier] :: [cun].
[vier] :: [c1,-un].
[vier] :: [c3,-taus].
[vier] :: [c2,-tausU].
