startCategory(cFin(_)).
[acht] :: [c1,-bl].%[acht] :: [c1,-bl,-al,-dl], [epsLi([=c1,+bl,+al,+dl,c1,-bl],dot)]
[acht] :: [c1,-bl,-al,-dl].
[acht] :: [c1].%[acht] :: [c1,-bl,-al,-dl], [epsLi([=c1,+dl,c1],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,+al,+dl,c1,-al],dot),epsLi([=c1,+bl,+al,+dl,c1,-bl],dot),epsLi([=c1,+bl,c1],dot)]
[acht] :: [c3bl].%[acht] :: [c1,-bl,-al,-dl], [epsLi([=c1,+bl,+al,+dl,c1,-bl],dot),epsLi([=c1,+bl,c3bl],dot)]
[acht] :: [c2bl].%[acht] :: [c1,-bl,-al,-dl], [epsLi([=c1,+bl,+al,+dl,c1,-bl],dot),epsLi([=c1,+bl,c2bl],dot)]
[acht] :: [cFin].%[acht] :: [c1,-bl,-al,-dl], [epsLi([=c1,+bl,+al,+dl,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c3],dot),epsLi([=c3,cFin],dot)]
[acht] :: [c3].%[acht] :: [c1,-bl,-al,-dl], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+al,+dl,c1,-al],dot),epsLi([=c1,+dl,c1],dot),epsLi([=c1,+bl,+al,+dl,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c3],dot)]
[acht] :: [c3el].%[acht] :: [c1,-bl,-al,-dl], [epsLi([=c1,+bl,+al,+dl,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-el],dot),epsLi([=c2,+el,c3el],dot)]
[acht] :: [c2].%[acht] :: [c1,-bl,-al,-dl], [epsLi([=c1,+bl,+al,+dl,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-el],dot),epsLi([=c2,+el,c2],dot)]
[acht] :: [c2,-el].%[acht] :: [c1,-bl,-al,-dl], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+al,+dl,c1,-al],dot),epsLi([=c1,+dl,c1],dot),epsLi([=c1,+bl,+al,+dl,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-el],dot)]
[drei] :: [c1,-cl].%[drei] :: [c1,-cl,-bl,-al], [epsLi([=c1,+cl,+bl,+al,c1,-cl],dot)]
[drei] :: [c1,-cl,-bl,-al].
[drei] :: [c1].%[drei] :: [c1,-cl,-bl,-al], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+cl,+bl,+al,c1,-cl],dot),epsLi([=c1,+cl,c1],dot)]
[drei] :: [cFin].%[drei] :: [c1,-cl,-bl,-al], [epsLi([=c1,+cl,+bl,+al,c1,-cl],dot),epsLi([=c1,+cl,c1],dot),epsLi([=c1,c3],dot),epsLi([=c3,cFin],dot)]
[drei] :: [c3].%[drei] :: [c1,-cl,-bl,-al], [epsLi([=c1,+bl,c1],dot),epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,+cl,+bl,+al,c1,-cl],dot),epsLi([=c1,+cl,c1],dot),epsLi([=c1,c3],dot)]
[drei] :: [c3el].%[drei] :: [c1,-cl,-bl,-al], [epsLi([=c1,+cl,+bl,+al,c1,-cl],dot),epsLi([=c1,+cl,c1],dot),epsLi([=c1,c2,-el],dot),epsLi([=c2,+el,c3el],dot)]
[drei] :: [c2].%[drei] :: [c1,-cl,-bl,-al], [epsLi([=c1,+cl,+bl,+al,c1,-cl],dot),epsLi([=c1,+cl,c1],dot),epsLi([=c1,c2,-el],dot),epsLi([=c2,+el,c2],dot)]
[drei] :: [c2,-el].%[drei] :: [c1,-cl,-bl,-al], [epsLi([=c1,+bl,c1],dot),epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,+cl,+bl,+al,c1,-cl],dot),epsLi([=c1,+cl,c1],dot),epsLi([=c1,c2,-el],dot)]
[eins] :: [c2,-el].%[eins] :: [c1], [epsLi([=c1,c2,-el],dot)]
[eins] :: [c3].%[eins] :: [c1], [epsLi([=c1,c3],dot)]
[eins] :: [c1].
[eins] :: [cFin].%[eins] :: [c1], [epsLi([=c1,c3],dot),epsLi([=c3,cFin],dot)]
[eins] :: [c3el].%[eins] :: [c1], [epsLi([=c1,c2,-el],dot),epsLi([=c2,+el,c3el],dot)]
[eins] :: [c2].%[eins] :: [c1], [epsLi([=c1,c2,-el],dot),epsLi([=c2,+el,c2],dot)]
[einund] :: [=c21s,c3].%[einund] :: [=c21s,c2,-sl0], [epsLi([=c2,+sl0,c3],dot)]
[einund] :: [=c21s,c2].%[einund] :: [=c21s,c2,-sl0], [epsLi([=c2,+sl0,c2],dot)]
[einund] :: [=c21s,c2,-sl0].
[einund] :: [=c21s,cFin].%[einund] :: [=c21s,c2,-sl0], [epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[einund] :: [=c23s,c3].%[einund] :: [=c23s,c2,-sl0], [epsLi([=c2,+sl0,c3],dot)]
[einund] :: [=c23s,c2].%[einund] :: [=c23s,c2,-sl0], [epsLi([=c2,+sl0,c2],dot)]
[einund] :: [=c23s,c2,-sl0].
[einund] :: [=c23s,cFin].%[einund] :: [=c23s,c2,-sl0], [epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[einundsechzig] :: [c2,-el].%[einundsechzig] :: [c2,-el,-sl0], [epsLi([=c2,+el,+sl0,c2,-el],dot)]
[einundsechzig] :: [c2,-el,-sl0].
[einundsechzig] :: [c3el].%[einundsechzig] :: [c2,-el,-sl0], [epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c3el],dot)]
[einundsechzig] :: [c2].%[einundsechzig] :: [c2,-el,-sl0], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c2],dot)]
[einundsiebzig] :: [c2,-el].%[einundsiebzig] :: [c2,-el,-sl0], [epsLi([=c2,+el,+sl0,c2,-el],dot)]
[einundsiebzig] :: [c2,-el,-sl0].
[einundsiebzig] :: [c3el].%[einundsiebzig] :: [c2,-el,-sl0], [epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c3el],dot)]
[einundsiebzig] :: [c2].%[einundsiebzig] :: [c2,-el,-sl0], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c2],dot)]
[einundzwanzig] :: [c2,-el].%[einundzwanzig] :: [c2,-el,-sl0], [epsLi([=c2,+el,+sl0,c2,-el],dot)]
[einundzwanzig] :: [c2,-el,-sl0].
[einundzwanzig] :: [c3el].%[einundzwanzig] :: [c2,-el,-sl0], [epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c3el],dot)]
[einundzwanzig] :: [c2].%[einundzwanzig] :: [c2,-el,-sl0], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c2],dot)]
[elf] :: [c2,-el].%[elf] :: [c2,-el,-sl0], [epsLi([=c2,+el,+sl0,c2,-el],dot)]
[elf] :: [c2,-el,-sl0].
[elf] :: [c3el].%[elf] :: [c2,-el,-sl0], [epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c3el],dot)]
[elf] :: [c2].%[elf] :: [c2,-el,-sl0], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c2],dot)]
[fuenf] :: [c1,-bl].%[fuenf] :: [c1,-bl,-al,-dl], [epsLi([=c1,+bl,+al,+dl,c1,-bl],dot)]
[fuenf] :: [c1,-bl,-al,-dl].
[fuenf] :: [c1].%[fuenf] :: [c1,-bl,-al,-dl], [epsLi([=c1,+dl,c1],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,+al,+dl,c1,-al],dot),epsLi([=c1,+bl,+al,+dl,c1,-bl],dot),epsLi([=c1,+bl,c1],dot)]
[fuenf] :: [c3bl].%[fuenf] :: [c1,-bl,-al,-dl], [epsLi([=c1,+bl,+al,+dl,c1,-bl],dot),epsLi([=c1,+bl,c3bl],dot)]
[fuenf] :: [c2bl].%[fuenf] :: [c1,-bl,-al,-dl], [epsLi([=c1,+bl,+al,+dl,c1,-bl],dot),epsLi([=c1,+bl,c2bl],dot)]
[fuenf] :: [cFin].%[fuenf] :: [c1,-bl,-al,-dl], [epsLi([=c1,+bl,+al,+dl,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c3],dot),epsLi([=c3,cFin],dot)]
[fuenf] :: [c3].%[fuenf] :: [c1,-bl,-al,-dl], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+al,+dl,c1,-al],dot),epsLi([=c1,+dl,c1],dot),epsLi([=c1,+bl,+al,+dl,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c3],dot)]
[fuenf] :: [c3el].%[fuenf] :: [c1,-bl,-al,-dl], [epsLi([=c1,+bl,+al,+dl,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-el],dot),epsLi([=c2,+el,c3el],dot)]
[fuenf] :: [c2].%[fuenf] :: [c1,-bl,-al,-dl], [epsLi([=c1,+bl,+al,+dl,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-el],dot),epsLi([=c2,+el,c2],dot)]
[fuenf] :: [c2,-el].%[fuenf] :: [c1,-bl,-al,-dl], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+al,+dl,c1,-al],dot),epsLi([=c1,+dl,c1],dot),epsLi([=c1,+bl,+al,+dl,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-el],dot)]
[hundert] :: [cFin].%[hundert] :: [c3], [epsLi([=c3,cFin],dot)]
[hundert] :: [c3].
[hundert] :: [=c1,+bl,cFin].%[hundert] :: [=c1,+bl,c3], [epsLi([=c3,cFin],dot)]
[hundert] :: [=c1,+bl,c3].
[hundert] :: [=c3el,cFin].%[hundert] :: [=c3el,c3], [epsLi([=c3,cFin],dot)]
[hundert] :: [=c3el,c3].
[hundert] :: [=c3el,=c2bl,cFin].%[hundert] :: [=c3el,=c2bl,c3], [epsLi([=c3,cFin],dot)]
[hundert] :: [=c3el,=c2bl,c3].
[neun] :: [c1,-bl].%[neun] :: [c1,-bl,-al,-dl], [epsLi([=c1,+bl,+al,+dl,c1,-bl],dot)]
[neun] :: [c1,-bl,-al,-dl].
[neun] :: [c1].%[neun] :: [c1,-bl,-al,-dl], [epsLi([=c1,+dl,c1],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,+al,+dl,c1,-al],dot),epsLi([=c1,+bl,+al,+dl,c1,-bl],dot),epsLi([=c1,+bl,c1],dot)]
[neun] :: [c3bl].%[neun] :: [c1,-bl,-al,-dl], [epsLi([=c1,+bl,+al,+dl,c1,-bl],dot),epsLi([=c1,+bl,c3bl],dot)]
[neun] :: [c2bl].%[neun] :: [c1,-bl,-al,-dl], [epsLi([=c1,+bl,+al,+dl,c1,-bl],dot),epsLi([=c1,+bl,c2bl],dot)]
[neun] :: [cFin].%[neun] :: [c1,-bl,-al,-dl], [epsLi([=c1,+bl,+al,+dl,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c3],dot),epsLi([=c3,cFin],dot)]
[neun] :: [c3].%[neun] :: [c1,-bl,-al,-dl], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+al,+dl,c1,-al],dot),epsLi([=c1,+dl,c1],dot),epsLi([=c1,+bl,+al,+dl,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c3],dot)]
[neun] :: [c3el].%[neun] :: [c1,-bl,-al,-dl], [epsLi([=c1,+bl,+al,+dl,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-el],dot),epsLi([=c2,+el,c3el],dot)]
[neun] :: [c2].%[neun] :: [c1,-bl,-al,-dl], [epsLi([=c1,+bl,+al,+dl,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-el],dot),epsLi([=c2,+el,c2],dot)]
[neun] :: [c2,-el].%[neun] :: [c1,-bl,-al,-dl], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+al,+dl,c1,-al],dot),epsLi([=c1,+dl,c1],dot),epsLi([=c1,+bl,+al,+dl,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-el],dot)]
[sechs] :: [c1].%[sechs] :: [c1,-bl], [epsLi([=c1,+bl,c1],dot)]
[sechs] :: [c3bl].%[sechs] :: [c1,-bl], [epsLi([=c1,+bl,c3bl],dot)]
[sechs] :: [c2bl].%[sechs] :: [c1,-bl], [epsLi([=c1,+bl,c2bl],dot)]
[sechs] :: [c1,-bl].
[sechs] :: [c2,-el].%[sechs] :: [c1,-bl], [epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-el],dot)]
[sechs] :: [c3].%[sechs] :: [c1,-bl], [epsLi([=c1,+bl,c1],dot),epsLi([=c1,c3],dot)]
[sechs] :: [c3el].%[sechs] :: [c1,-bl], [epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-el],dot),epsLi([=c2,+el,c3el],dot)]
[sechs] :: [c2].%[sechs] :: [c1,-bl], [epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-el],dot),epsLi([=c2,+el,c2],dot)]
[sechs] :: [cFin].%[sechs] :: [c1,-bl], [epsLi([=c1,+bl,c1],dot),epsLi([=c1,c3],dot),epsLi([=c3,cFin],dot)]
[sechzehn] :: [c2,-el].%[sechzehn] :: [c2,-el,-sl0], [epsLi([=c2,+el,+sl0,c2,-el],dot)]
[sechzehn] :: [c2,-el,-sl0].
[sechzehn] :: [c3el].%[sechzehn] :: [c2,-el,-sl0], [epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c3el],dot)]
[sechzehn] :: [c2].%[sechzehn] :: [c2,-el,-sl0], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c2],dot)]
[sechzig] :: [c2,-el].%[sechzig] :: [c2,-el,-sl0], [epsLi([=c2,+el,+sl0,c2,-el],dot)]
[sechzig] :: [c2,-el,-sl0].
[sechzig] :: [c3el].%[sechzig] :: [c2,-el,-sl0], [epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c3el],dot)]
[sechzig] :: [c2].%[sechzig] :: [c2,-el,-sl0], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c2],dot)]
[sieben] :: [c1].%[sieben] :: [c1,-bl], [epsLi([=c1,+bl,c1],dot)]
[sieben] :: [c3bl].%[sieben] :: [c1,-bl], [epsLi([=c1,+bl,c3bl],dot)]
[sieben] :: [c2bl].%[sieben] :: [c1,-bl], [epsLi([=c1,+bl,c2bl],dot)]
[sieben] :: [c1,-bl].
[sieben] :: [c2,-el].%[sieben] :: [c1,-bl], [epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-el],dot)]
[sieben] :: [c3].%[sieben] :: [c1,-bl], [epsLi([=c1,+bl,c1],dot),epsLi([=c1,c3],dot)]
[sieben] :: [c3el].%[sieben] :: [c1,-bl], [epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-el],dot),epsLi([=c2,+el,c3el],dot)]
[sieben] :: [c2].%[sieben] :: [c1,-bl], [epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-el],dot),epsLi([=c2,+el,c2],dot)]
[sieben] :: [cFin].%[sieben] :: [c1,-bl], [epsLi([=c1,+bl,c1],dot),epsLi([=c1,c3],dot),epsLi([=c3,cFin],dot)]
[siebzehn] :: [c2,-el].%[siebzehn] :: [c2,-el,-sl0], [epsLi([=c2,+el,+sl0,c2,-el],dot)]
[siebzehn] :: [c2,-el,-sl0].
[siebzehn] :: [c3el].%[siebzehn] :: [c2,-el,-sl0], [epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c3el],dot)]
[siebzehn] :: [c2].%[siebzehn] :: [c2,-el,-sl0], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c2],dot)]
[siebzig] :: [c2,-el].%[siebzig] :: [c2,-el,-sl0], [epsLi([=c2,+el,+sl0,c2,-el],dot)]
[siebzig] :: [c2,-el,-sl0].
[siebzig] :: [c3el].%[siebzig] :: [c2,-el,-sl0], [epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c3el],dot)]
[siebzig] :: [c2].%[siebzig] :: [c2,-el,-sl0], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c2],dot)]
[ssig] :: [=c1,+cl,c3].%[ssig] :: [=c1,+cl,c2,-sl0], [epsLi([=c2,+sl0,c3],dot)]
[ssig] :: [=c1,+cl,c2].%[ssig] :: [=c1,+cl,c2,-sl0], [epsLi([=c2,+sl0,c2],dot)]
[ssig] :: [=c1,+cl,c2,-sl0].
[ssig] :: [=c1,+cl,cFin].%[ssig] :: [=c1,+cl,c2,-sl0], [epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[ssig] :: [=c1,+cl,c21s].
[ssig] :: [=c1,+cl,c22s].
[und] :: [=c22s,=c2bl,c3].%[und] :: [=c22s,=c2bl,c2,-sl0], [epsLi([=c2,+sl0,c3],dot)]
[und] :: [=c22s,=c2bl,c2].%[und] :: [=c22s,=c2bl,c2,-sl0], [epsLi([=c2,+sl0,c2],dot)]
[und] :: [=c22s,=c2bl,c2,-sl0].
[und] :: [=c22s,=c2bl,cFin].%[und] :: [=c22s,=c2bl,c2,-sl0], [epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[und] :: [=c24s,=c2bl,c3].%[und] :: [=c24s,=c2bl,c2,-sl0], [epsLi([=c2,+sl0,c3],dot)]
[und] :: [=c24s,=c2bl,c2].%[und] :: [=c24s,=c2bl,c2,-sl0], [epsLi([=c2,+sl0,c2],dot)]
[und] :: [=c24s,=c2bl,c2,-sl0].
[und] :: [=c24s,=c2bl,cFin].%[und] :: [=c24s,=c2bl,c2,-sl0], [epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[undsechzig] :: [=c1,+bl,c3].%[undsechzig] :: [=c1,+bl,c2,-sl0], [epsLi([=c2,+sl0,c3],dot)]
[undsechzig] :: [=c1,+bl,c2].%[undsechzig] :: [=c1,+bl,c2,-sl0], [epsLi([=c2,+sl0,c2],dot)]
[undsechzig] :: [=c1,+bl,c2,-sl0].
[undsechzig] :: [=c1,+bl,cFin].%[undsechzig] :: [=c1,+bl,c2,-sl0], [epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[undsiebzig] :: [=c1,+bl,c3].%[undsiebzig] :: [=c1,+bl,c2,-sl0], [epsLi([=c2,+sl0,c3],dot)]
[undsiebzig] :: [=c1,+bl,c2].%[undsiebzig] :: [=c1,+bl,c2,-sl0], [epsLi([=c2,+sl0,c2],dot)]
[undsiebzig] :: [=c1,+bl,c2,-sl0].
[undsiebzig] :: [=c1,+bl,cFin].%[undsiebzig] :: [=c1,+bl,c2,-sl0], [epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[undzwanzig] :: [=c1,+bl,c3].%[undzwanzig] :: [=c1,+bl,c2,-sl0], [epsLi([=c2,+sl0,c3],dot)]
[undzwanzig] :: [=c1,+bl,c2].%[undzwanzig] :: [=c1,+bl,c2,-sl0], [epsLi([=c2,+sl0,c2],dot)]
[undzwanzig] :: [=c1,+bl,c2,-sl0].
[undzwanzig] :: [=c1,+bl,cFin].%[undzwanzig] :: [=c1,+bl,c2,-sl0], [epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[vier] :: [c1,-bl].%[vier] :: [c1,-bl,-al,-dl], [epsLi([=c1,+bl,+al,+dl,c1,-bl],dot)]
[vier] :: [c1,-bl,-al,-dl].
[vier] :: [c1].%[vier] :: [c1,-bl,-al,-dl], [epsLi([=c1,+dl,c1],dot),epsLi([=c1,+al,c1],dot),epsLi([=c1,+al,+dl,c1,-al],dot),epsLi([=c1,+bl,+al,+dl,c1,-bl],dot),epsLi([=c1,+bl,c1],dot)]
[vier] :: [c3bl].%[vier] :: [c1,-bl,-al,-dl], [epsLi([=c1,+bl,+al,+dl,c1,-bl],dot),epsLi([=c1,+bl,c3bl],dot)]
[vier] :: [c2bl].%[vier] :: [c1,-bl,-al,-dl], [epsLi([=c1,+bl,+al,+dl,c1,-bl],dot),epsLi([=c1,+bl,c2bl],dot)]
[vier] :: [cFin].%[vier] :: [c1,-bl,-al,-dl], [epsLi([=c1,+bl,+al,+dl,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c3],dot),epsLi([=c3,cFin],dot)]
[vier] :: [c3].%[vier] :: [c1,-bl,-al,-dl], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+al,+dl,c1,-al],dot),epsLi([=c1,+dl,c1],dot),epsLi([=c1,+bl,+al,+dl,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c3],dot)]
[vier] :: [c3el].%[vier] :: [c1,-bl,-al,-dl], [epsLi([=c1,+bl,+al,+dl,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-el],dot),epsLi([=c2,+el,c3el],dot)]
[vier] :: [c2].%[vier] :: [c1,-bl,-al,-dl], [epsLi([=c1,+bl,+al,+dl,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-el],dot),epsLi([=c2,+el,c2],dot)]
[vier] :: [c2,-el].%[vier] :: [c1,-bl,-al,-dl], [epsLi([=c1,+al,c1],dot),epsLi([=c1,+al,+dl,c1,-al],dot),epsLi([=c1,+dl,c1],dot),epsLi([=c1,+bl,+al,+dl,c1,-bl],dot),epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-el],dot)]
[zehn] :: [c2,-el].%[zehn] :: [c2,-el,-sl0], [epsLi([=c2,+el,+sl0,c2,-el],dot)]
[zehn] :: [c2,-el,-sl0].
[zehn] :: [c3el].%[zehn] :: [c2,-el,-sl0], [epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c3el],dot)]
[zehn] :: [c2].%[zehn] :: [c2,-el,-sl0], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c2],dot)]
[zehn] :: [=c1,+al,c3].%[zehn] :: [=c1,+al,c2,-sl0], [epsLi([=c2,+sl0,c3],dot)]
[zehn] :: [=c1,+al,c2].%[zehn] :: [=c1,+al,c2,-sl0], [epsLi([=c2,+sl0,c2],dot)]
[zehn] :: [=c1,+al,c2,-sl0].
[zehn] :: [=c1,+al,cFin].%[zehn] :: [=c1,+al,c2,-sl0], [epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[zig] :: [=c1,+dl,c3].%[zig] :: [=c1,+dl,c2,-sl0], [epsLi([=c2,+sl0,c3],dot)]
[zig] :: [=c1,+dl,c2].%[zig] :: [=c1,+dl,c2,-sl0], [epsLi([=c2,+sl0,c2],dot)]
[zig] :: [=c1,+dl,c2,-sl0].
[zig] :: [=c1,+dl,cFin].%[zig] :: [=c1,+dl,c2,-sl0], [epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[zig] :: [=c1,+dl,c23s].
[zig] :: [=c1,+dl,c24s].
[zwanzig] :: [c2,-el].%[zwanzig] :: [c2,-el,-sl0], [epsLi([=c2,+el,+sl0,c2,-el],dot)]
[zwanzig] :: [c2,-el,-sl0].
[zwanzig] :: [c3el].%[zwanzig] :: [c2,-el,-sl0], [epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c3el],dot)]
[zwanzig] :: [c2].%[zwanzig] :: [c2,-el,-sl0], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c2],dot)]
[zwei] :: [c1].%[zwei] :: [c1,-bl], [epsLi([=c1,+bl,c1],dot)]
[zwei] :: [c3bl].%[zwei] :: [c1,-bl], [epsLi([=c1,+bl,c3bl],dot)]
[zwei] :: [c2bl].%[zwei] :: [c1,-bl], [epsLi([=c1,+bl,c2bl],dot)]
[zwei] :: [c1,-bl].
[zwei] :: [c2,-el].%[zwei] :: [c1,-bl], [epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-el],dot)]
[zwei] :: [c3].%[zwei] :: [c1,-bl], [epsLi([=c1,+bl,c1],dot),epsLi([=c1,c3],dot)]
[zwei] :: [c3el].%[zwei] :: [c1,-bl], [epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-el],dot),epsLi([=c2,+el,c3el],dot)]
[zwei] :: [c2].%[zwei] :: [c1,-bl], [epsLi([=c1,+bl,c1],dot),epsLi([=c1,c2,-el],dot),epsLi([=c2,+el,c2],dot)]
[zwei] :: [cFin].%[zwei] :: [c1,-bl], [epsLi([=c1,+bl,c1],dot),epsLi([=c1,c3],dot),epsLi([=c3,cFin],dot)]
[zwoelf] :: [c2,-el].%[zwoelf] :: [c2,-el,-sl0], [epsLi([=c2,+el,+sl0,c2,-el],dot)]
[zwoelf] :: [c2,-el,-sl0].
[zwoelf] :: [c3el].%[zwoelf] :: [c2,-el,-sl0], [epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c3el],dot)]
[zwoelf] :: [c2].%[zwoelf] :: [c2,-el,-sl0], [epsLi([=c2,+sl0,c2],dot),epsLi([=c2,+el,+sl0,c2,-el],dot),epsLi([=c2,+el,c2],dot)]
[acht] :: [c1,-al].%[acht] :: [c1,-bl,-al,-dl], [epsLi([=c1,+bl,c1],dot),epsLi([=c1,+al,+dl,c1,-al],dot)]
[drei] :: [c3bl].%[drei] :: [c1,-cl,-bl,-al], [epsLi([=c1,+cl,c1],dot),epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+bl,c3bl],dot)]
[drei] :: [c2bl].%[drei] :: [c1,-cl,-bl,-al], [epsLi([=c1,+cl,c1],dot),epsLi([=c1,+bl,+al,c1,-bl],dot),epsLi([=c1,+bl,c2bl],dot)]
[drei] :: [c1,-bl].%[drei] :: [c1,-cl,-bl,-al], [epsLi([=c1,+cl,c1],dot),epsLi([=c1,+bl,+al,c1,-bl],dot)]
[einundsechzig] :: [cFin].%[einundsechzig] :: [c2,-el,-sl0], [epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[einundsechzig] :: [c3].%[einundsechzig] :: [c2,-el,-sl0], [epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot)]
[einundsiebzig] :: [cFin].%[einundsiebzig] :: [c2,-el,-sl0], [epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[einundsiebzig] :: [c3].%[einundsiebzig] :: [c2,-el,-sl0], [epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot)]
[einundzwanzig] :: [cFin].%[einundzwanzig] :: [c2,-el,-sl0], [epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[einundzwanzig] :: [c3].%[einundzwanzig] :: [c2,-el,-sl0], [epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot)]
[elf] :: [cFin].%[elf] :: [c2,-el,-sl0], [epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[elf] :: [c3].%[elf] :: [c2,-el,-sl0], [epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot)]
[fuenf] :: [c1,-al].%[fuenf] :: [c1,-bl,-al,-dl], [epsLi([=c1,+bl,c1],dot),epsLi([=c1,+al,+dl,c1,-al],dot)]
[neun] :: [c1,-al].%[neun] :: [c1,-bl,-al,-dl], [epsLi([=c1,+bl,c1],dot),epsLi([=c1,+al,+dl,c1,-al],dot)]
[sechzehn] :: [cFin].%[sechzehn] :: [c2,-el,-sl0], [epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[sechzehn] :: [c3].%[sechzehn] :: [c2,-el,-sl0], [epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot)]
[sechzig] :: [cFin].%[sechzig] :: [c2,-el,-sl0], [epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[sechzig] :: [c3].%[sechzig] :: [c2,-el,-sl0], [epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot)]
[siebzehn] :: [cFin].%[siebzehn] :: [c2,-el,-sl0], [epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[siebzehn] :: [c3].%[siebzehn] :: [c2,-el,-sl0], [epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot)]
[siebzig] :: [cFin].%[siebzig] :: [c2,-el,-sl0], [epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[siebzig] :: [c3].%[siebzig] :: [c2,-el,-sl0], [epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot)]
[vier] :: [c1,-al].%[vier] :: [c1,-bl,-al,-dl], [epsLi([=c1,+bl,c1],dot),epsLi([=c1,+al,+dl,c1,-al],dot)]
[zehn] :: [cFin].%[zehn] :: [c2,-el,-sl0], [epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[zehn] :: [c3].%[zehn] :: [c2,-el,-sl0], [epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot)]
[zwanzig] :: [cFin].%[zwanzig] :: [c2,-el,-sl0], [epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[zwanzig] :: [c3].%[zwanzig] :: [c2,-el,-sl0], [epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot)]
[zwoelf] :: [cFin].%[zwoelf] :: [c2,-el,-sl0], [epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot),epsLi([=c3,cFin],dot)]
[zwoelf] :: [c3].%[zwoelf] :: [c2,-el,-sl0], [epsLi([=c2,+el,c2],dot),epsLi([=c2,+sl0,c3],dot)]
